# GENERATED by python-multiplatform-gradle-plugin. Do not edit.

import typing as _t
import androidx.compose.ui.unit

class _Modifier_fillMaxWidth(_t.Protocol):
    def __call__(self, fraction: float = ...) -> Modifier: ...

class _Modifier_onClick(_t.Protocol):
    def __call__(self, enabled: bool = ..., on_click: _t.Callable[[], None] = ...) -> Modifier: ...

class Modifier:
    """Kotlin: androidx.compose.ui.Modifier"""
    fillMaxWidth: _t.ClassVar[_Modifier_fillMaxWidth]
    onClick: _t.ClassVar[_Modifier_onClick]
    fill_max_width: _t.ClassVar[_Modifier_fillMaxWidth]
    on_click: _t.ClassVar[_Modifier_onClick]

class Scene:
    """Kotlin: androidx.compose.ui.Scene"""
    @property
    def layoutDirection(self) -> androidx.compose.ui.unit.LayoutDirection:
        """Kotlin property: androidx.compose.ui.Scene.layoutDirection (androidx.compose.ui.Scene.layoutDirection: androidx.compose.ui.unit.LayoutDirection)"""
        ...
    @layoutDirection.setter
    def layoutDirection(self, value: androidx.compose.ui.unit.LayoutDirection) -> None:
        """Kotlin property: androidx.compose.ui.Scene.layoutDirection="""
        ...
    @property
    def isMinimized(self) -> bool:
        """Kotlin property: androidx.compose.ui.Scene.isMinimized (androidx.compose.ui.Scene.isMinimized: kotlin.Boolean)"""
        ...
    @property
    def layout_direction(self) -> androidx.compose.ui.unit.LayoutDirection:
        """Kotlin property: androidx.compose.ui.Scene.layoutDirection (androidx.compose.ui.Scene.layoutDirection: androidx.compose.ui.unit.LayoutDirection)"""
        ...
    @layout_direction.setter
    def layout_direction(self, value: androidx.compose.ui.unit.LayoutDirection) -> None:
        """Kotlin property: androidx.compose.ui.Scene.layoutDirection="""
        ...
    @property
    def is_minimized(self) -> bool:
        """Kotlin property: androidx.compose.ui.Scene.isMinimized (androidx.compose.ui.Scene.isMinimized: kotlin.Boolean)"""
        ...
