# GENERATED by python-multiplatform-gradle-plugin. Do not edit.

import typing as _t
import androidx.compose.ui
import androidx.compose.ui.text
import kotlin.collections

def Text(text: str, modifier: androidx.compose.ui.Modifier = ..., fontSize: _t.Any = ..., inlineContent: kotlin.collections.Map = ..., onTextLayout: _t.Callable[[androidx.compose.ui.text.TextLayoutResult], None] | None = ..., style: androidx.compose.ui.text.ParagraphStyle = ...) -> None:
    """Kotlin: androidx.compose.material3.Text(text: kotlin.String, modifier: androidx.compose.ui.Modifier, fontSize: androidx.compose.ui.unit.TextUnit, inlineContent: kotlin.collections.Map, onTextLayout: kotlin.Function1, style: androidx.compose.ui.text.ParagraphStyle): kotlin.Unit"""
    ...
