# GENERATED by python-multiplatform-gradle-plugin. Do not edit.

def describeModifier(modifier: int) -> str:
    """Kotlin: androidx.compose.ui.describeModifier(modifier: androidx.compose.ui.Modifier): kotlin.String"""
    ...

def toURLString(raw: str) -> str:
    """Kotlin: androidx.compose.ui.toURLString(raw: kotlin.String): kotlin.String"""
    ...
