# GENERATED by pythonx/_build/gen_stubs.py from python-multiplatform's Kotlin-named stubs (artifact kotlin-stubs, workflow run 37103737430, commit a5028618, Compose 1.11.1). Do not edit.
import typing as _t

class BorderStroke:
    """Kotlin: androidx.compose.foundation.BorderStroke"""

class Indication:
    """Kotlin: androidx.compose.foundation.Indication"""

class IndicationNodeFactory(Indication):
    """Kotlin: androidx.compose.foundation.IndicationNodeFactory"""

class MutatorMutex:
    """Kotlin: androidx.compose.foundation.MutatorMutex"""

class ScrollState:
    """Kotlin: androidx.compose.foundation.ScrollState"""
