# GENERATED by tools/gen_stubs.py from python-multiplatform's Kotlin-named stubs (artifact kotlin-stubs, workflow run 37077627980, commit 86012ca0, Compose 1.11.1). Do not edit.
# Methods are reached by snake_case names, but their keyword arguments keep Kotlin's names: the runtime does not translate a method's keywords yet.
import typing as _t

class BorderStroke:
    """Kotlin: androidx.compose.foundation.BorderStroke"""

class Indication:
    """Kotlin: androidx.compose.foundation.Indication"""

class IndicationNodeFactory(Indication):
    """Kotlin: androidx.compose.foundation.IndicationNodeFactory"""

class MutatorMutex:
    """Kotlin: androidx.compose.foundation.MutatorMutex"""

class ScrollState:
    """Kotlin: androidx.compose.foundation.ScrollState"""
