# GENERATED by python-multiplatform-gradle-plugin. Do not edit.

import typing as _t
import androidx.compose.ui.graphics.vector

def materialIcon(name: str) -> androidx.compose.ui.graphics.vector.ImageVector:
    """Kotlin: androidx.compose.material.icons.materialIcon(name: kotlin.String): androidx.compose.ui.graphics.vector.ImageVector"""
    ...
