# GENERATED by python-multiplatform-gradle-plugin. Do not edit.

import typing as _t

class TextLayoutResult:
    """Kotlin: androidx.compose.ui.text.TextLayoutResult"""

def TextStyle(fontSize: _t.Any = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.TextStyle(fontSize: androidx.compose.ui.unit.TextUnit): androidx.compose.ui.text.TextStyle"""
    ...
