# GENERATED by python-multiplatform-gradle-plugin. Do not edit.

def padding__Dp(receiver: int, /, all: float) -> int:
    """Kotlin: androidx.compose.foundation.layout.padding(all: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def padding__Dp_Dp(receiver: int, /, horizontal: float = ..., vertical: float = ...) -> int:
    """Kotlin: androidx.compose.foundation.layout.padding(horizontal: androidx.compose.ui.unit.Dp, vertical: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def padding__Dp_Dp_Dp_Dp(receiver: int, /, start: float = ..., top: float = ..., end: float = ..., bottom: float = ...) -> int:
    """Kotlin: androidx.compose.foundation.layout.padding(start, top, end, bottom): androidx.compose.ui.Modifier"""
    ...

def padding__PaddingValues(receiver: int, /, paddingValues: int) -> int:
    """Kotlin: androidx.compose.foundation.layout.padding(paddingValues: androidx.compose.foundation.layout.PaddingValues): androidx.compose.ui.Modifier"""
    ...

def paddingValuesOf(all: float) -> int:
    """Kotlin: androidx.compose.foundation.layout.paddingValuesOf(all: androidx.compose.ui.unit.Dp): androidx.compose.foundation.layout.PaddingValues"""
    ...

def size__Dp(receiver: int, /, size: float) -> int:
    """Kotlin: androidx.compose.foundation.layout.size(size: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def fillMaxWidth(receiver: int, /) -> int:
    """Kotlin: androidx.compose.foundation.layout.fillMaxWidth(): androidx.compose.ui.Modifier"""
    ...

def scan(receiver: int, first: float, __a1: float, /, last: float = ...) -> int:
    """A parameter named like a Python keyword: positional-only and anonymous, never renamed."""
    ...
