# GENERATED by python-multiplatform-gradle-plugin. Do not edit.

import typing as _t
import androidx.compose.ui

class _PaddingValues_callable_module(_t.Protocol):
    """Kotlin: the function PaddingValues, and the members of the module PaddingValues"""
    def __call__(self, all: float) -> _t.Any: ...
    Zero: _t.Any

def Column(verticalAlignment: androidx.compose.ui.Alignment.Vertical = ..., *, content: _t.Callable[[], None]) -> None:
    """Kotlin: androidx.compose.foundation.layout.Column(verticalAlignment: androidx.compose.ui.Alignment.Vertical, content: kotlin.Function0): kotlin.Unit"""
    ...

def fillMaxWidth(receiver: androidx.compose.ui.Modifier, /, fraction: float = ...) -> androidx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.fillMaxWidth(fraction: kotlin.Float): androidx.compose.ui.Modifier"""
    ...

def fillMaxHeight(receiver: androidx.compose.ui.Modifier, /, fraction: float = ...) -> androidx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.fillMaxHeight(fraction: kotlin.Float): androidx.compose.ui.Modifier"""
    ...

def scrollable(receiver: androidx.compose.ui.Modifier, /, state: _t.Any, enabled: bool = ..., on_click: _t.Callable[[], None] = ...) -> androidx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.scrollable(state: kotlin.Any, enabled: kotlin.Boolean, onClick: kotlin.Function0): androidx.compose.ui.Modifier"""
    ...

def PaddingValues__Dp(all: float) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.PaddingValues(all: androidx.compose.ui.unit.Dp): androidx.compose.foundation.layout.PaddingValues"""
    ...

PaddingValues: _PaddingValues_callable_module

fill_max_height = fillMaxHeight

fill_max_width = fillMaxWidth
