# GENERATED by scripts/gen_stubs.py from python-multiplatform's Kotlin-named stubs (artifact kotlin-stubs, workflow run 37131041879, commit 452cc807, Compose 1.11.1). Do not edit.
import typing as _t
import pythonx.compose.runtime
import pythonx.compose.ui.graphics

class _ImageVector_Builder_materialPath(_t.Protocol):
    def __call__(self, fill_alpha: float = ..., stroke_alpha: float = ..., path_fill_type: _t.Any = ..., *, path_builder: _t.Callable[[PathBuilder], None]) -> ImageVector.Builder: ...

class _ImageVector_Builder_path(_t.Protocol):
    def __call__(self, name: str, fill: pythonx.compose.ui.graphics.Brush | None, fill_alpha: float, stroke: pythonx.compose.ui.graphics.Brush | None, stroke_alpha: float, stroke_line_width: float, stroke_line_cap: _t.Any, stroke_line_join: _t.Any, stroke_line_miter: float, path_fill_type: _t.Any, path_builder: _t.Callable[[PathBuilder], None]) -> ImageVector.Builder: ...

class ImageVector:
    """Kotlin: androidx.compose.ui.graphics.vector.ImageVector"""
    @property
    def auto_mirror(self) -> bool:
        """Kotlin property: androidx.compose.ui.graphics.vector.ImageVector.autoMirror (androidx.compose.ui.graphics.vector.ImageVector.autoMirror: kotlin.Boolean)"""
        ...
    @property
    def default_height(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.ImageVector.defaultHeight (androidx.compose.ui.graphics.vector.ImageVector.defaultHeight: androidx.compose.ui.unit.Dp)"""
        ...
    @property
    def default_width(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.ImageVector.defaultWidth (androidx.compose.ui.graphics.vector.ImageVector.defaultWidth: androidx.compose.ui.unit.Dp)"""
        ...
    @property
    def name(self) -> str:
        """Kotlin property: androidx.compose.ui.graphics.vector.ImageVector.name (androidx.compose.ui.graphics.vector.ImageVector.name: kotlin.String)"""
        ...
    @property
    def root(self) -> VectorGroup:
        """Kotlin property: androidx.compose.ui.graphics.vector.ImageVector.root (androidx.compose.ui.graphics.vector.ImageVector.root: androidx.compose.ui.graphics.vector.VectorGroup)"""
        ...
    @property
    def tint_blend_mode(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.graphics.vector.ImageVector.tintBlendMode (androidx.compose.ui.graphics.vector.ImageVector.tintBlendMode: androidx.compose.ui.graphics.BlendMode)"""
        ...
    @property
    def tint_color(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.graphics.vector.ImageVector.tintColor (androidx.compose.ui.graphics.vector.ImageVector.tintColor: androidx.compose.ui.graphics.Color)"""
        ...
    @property
    def viewport_height(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.ImageVector.viewportHeight (androidx.compose.ui.graphics.vector.ImageVector.viewportHeight: kotlin.Float)"""
        ...
    @property
    def viewport_width(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.ImageVector.viewportWidth (androidx.compose.ui.graphics.vector.ImageVector.viewportWidth: kotlin.Float)"""
        ...
    class Builder:
        """Kotlin: androidx.compose.ui.graphics.vector.ImageVector.Builder"""
        material_path: _t.ClassVar[_ImageVector_Builder_materialPath]
        path: _t.ClassVar[_ImageVector_Builder_path]

class PathBuilder:
    """Kotlin: androidx.compose.ui.graphics.vector.PathBuilder"""
    def __init__(self) -> None:
        """Kotlin constructor: androidx.compose.ui.graphics.vector.PathBuilder (androidx.compose.ui.graphics.vector.PathBuilder(): androidx.compose.ui.graphics.vector.PathBuilder)"""
        ...

class PathNode:
    """Kotlin: androidx.compose.ui.graphics.vector.PathNode"""
    @property
    def is_curve(self) -> bool:
        """Kotlin property: androidx.compose.ui.graphics.vector.PathNode.isCurve (androidx.compose.ui.graphics.vector.PathNode.isCurve: kotlin.Boolean)"""
        ...
    @property
    def is_quad(self) -> bool:
        """Kotlin property: androidx.compose.ui.graphics.vector.PathNode.isQuad (androidx.compose.ui.graphics.vector.PathNode.isQuad: kotlin.Boolean)"""
        ...

class PathParser:
    """Kotlin: androidx.compose.ui.graphics.vector.PathParser"""
    def __init__(self) -> None:
        """Kotlin constructor: androidx.compose.ui.graphics.vector.PathParser (androidx.compose.ui.graphics.vector.PathParser(): androidx.compose.ui.graphics.vector.PathParser)"""
        ...

class VNode:
    """Kotlin: androidx.compose.ui.graphics.vector.VNode"""

class VectorApplier(pythonx.compose.runtime.AbstractApplier, pythonx.compose.runtime.Applier):
    """Kotlin: androidx.compose.ui.graphics.vector.VectorApplier"""
    def __init__(self, root: VNode) -> None:
        """Kotlin constructor: androidx.compose.ui.graphics.vector.VectorApplier (androidx.compose.ui.graphics.vector.VectorApplier(root: androidx.compose.ui.graphics.vector.VNode): androidx.compose.ui.graphics.vector.VectorApplier)"""
        ...

class VectorGroup:
    """Kotlin: androidx.compose.ui.graphics.vector.VectorGroup"""
    @property
    def name(self) -> str:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorGroup.name (androidx.compose.ui.graphics.vector.VectorGroup.name: kotlin.String)"""
        ...
    @property
    def pivot_x(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorGroup.pivotX (androidx.compose.ui.graphics.vector.VectorGroup.pivotX: kotlin.Float)"""
        ...
    @property
    def pivot_y(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorGroup.pivotY (androidx.compose.ui.graphics.vector.VectorGroup.pivotY: kotlin.Float)"""
        ...
    @property
    def rotation(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorGroup.rotation (androidx.compose.ui.graphics.vector.VectorGroup.rotation: kotlin.Float)"""
        ...
    @property
    def scale_x(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorGroup.scaleX (androidx.compose.ui.graphics.vector.VectorGroup.scaleX: kotlin.Float)"""
        ...
    @property
    def scale_y(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorGroup.scaleY (androidx.compose.ui.graphics.vector.VectorGroup.scaleY: kotlin.Float)"""
        ...
    @property
    def size(self) -> int:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorGroup.size (androidx.compose.ui.graphics.vector.VectorGroup.size: kotlin.Int)"""
        ...
    @property
    def translation_x(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorGroup.translationX (androidx.compose.ui.graphics.vector.VectorGroup.translationX: kotlin.Float)"""
        ...
    @property
    def translation_y(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorGroup.translationY (androidx.compose.ui.graphics.vector.VectorGroup.translationY: kotlin.Float)"""
        ...

class VectorPainter(_t.Any):
    """Kotlin: androidx.compose.ui.graphics.vector.VectorPainter"""
    @property
    def intrinsic_size(self) -> int:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPainter.intrinsicSize (androidx.compose.ui.graphics.vector.VectorPainter.intrinsicSize: androidx.compose.ui.geometry.Size)"""
        ...

class VectorPath:
    """Kotlin: androidx.compose.ui.graphics.vector.VectorPath"""
    @property
    def fill(self) -> pythonx.compose.ui.graphics.Brush | None:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPath.fill (androidx.compose.ui.graphics.vector.VectorPath.fill: androidx.compose.ui.graphics.Brush?)"""
        ...
    @property
    def fill_alpha(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPath.fillAlpha (androidx.compose.ui.graphics.vector.VectorPath.fillAlpha: kotlin.Float)"""
        ...
    @property
    def name(self) -> str:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPath.name (androidx.compose.ui.graphics.vector.VectorPath.name: kotlin.String)"""
        ...
    @property
    def path_fill_type(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPath.pathFillType (androidx.compose.ui.graphics.vector.VectorPath.pathFillType: androidx.compose.ui.graphics.PathFillType)"""
        ...
    @property
    def stroke(self) -> pythonx.compose.ui.graphics.Brush | None:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPath.stroke (androidx.compose.ui.graphics.vector.VectorPath.stroke: androidx.compose.ui.graphics.Brush?)"""
        ...
    @property
    def stroke_alpha(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPath.strokeAlpha (androidx.compose.ui.graphics.vector.VectorPath.strokeAlpha: kotlin.Float)"""
        ...
    @property
    def stroke_line_cap(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPath.strokeLineCap (androidx.compose.ui.graphics.vector.VectorPath.strokeLineCap: androidx.compose.ui.graphics.StrokeCap)"""
        ...
    @property
    def stroke_line_join(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPath.strokeLineJoin (androidx.compose.ui.graphics.vector.VectorPath.strokeLineJoin: androidx.compose.ui.graphics.StrokeJoin)"""
        ...
    @property
    def stroke_line_miter(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPath.strokeLineMiter (androidx.compose.ui.graphics.vector.VectorPath.strokeLineMiter: kotlin.Float)"""
        ...
    @property
    def stroke_line_width(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPath.strokeLineWidth (androidx.compose.ui.graphics.vector.VectorPath.strokeLineWidth: kotlin.Float)"""
        ...
    @property
    def trim_path_end(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPath.trimPathEnd (androidx.compose.ui.graphics.vector.VectorPath.trimPathEnd: kotlin.Float)"""
        ...
    @property
    def trim_path_offset(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPath.trimPathOffset (androidx.compose.ui.graphics.vector.VectorPath.trimPathOffset: kotlin.Float)"""
        ...
    @property
    def trim_path_start(self) -> float:
        """Kotlin property: androidx.compose.ui.graphics.vector.VectorPath.trimPathStart (androidx.compose.ui.graphics.vector.VectorPath.trimPathStart: kotlin.Float)"""
        ...

def Group(name: str = ..., rotation: float = ..., pivot_x: float = ..., pivot_y: float = ..., scale_x: float = ..., scale_y: float = ..., translation_x: float = ..., translation_y: float = ..., clip_path_data: _t.Any = ..., *, content: _t.Callable[[], None]) -> None:
    """Kotlin: androidx.compose.ui.graphics.vector.Group(name: kotlin.String, rotation: kotlin.Float, pivotX: kotlin.Float, pivotY: kotlin.Float, scaleX: kotlin.Float, scaleY: kotlin.Float, translationX: kotlin.Float, translationY: kotlin.Float, clipPathData: kotlin.collections.List, content: kotlin.Function0): kotlin.Unit"""
    ...

def Path(path_data: _t.Any, path_fill_type: _t.Any = ..., name: str = ..., fill: pythonx.compose.ui.graphics.Brush | None = ..., fill_alpha: float = ..., stroke: pythonx.compose.ui.graphics.Brush | None = ..., stroke_alpha: float = ..., stroke_line_width: float = ..., stroke_line_cap: _t.Any = ..., stroke_line_join: _t.Any = ..., stroke_line_miter: float = ..., trim_path_start: float = ..., trim_path_end: float = ..., trim_path_offset: float = ...) -> None:
    """Kotlin: androidx.compose.ui.graphics.vector.Path(pathData: kotlin.collections.List, pathFillType: androidx.compose.ui.graphics.PathFillType, name: kotlin.String, fill: androidx.compose.ui.graphics.Brush?, fillAlpha: kotlin.Float, stroke: androidx.compose.ui.graphics.Brush?, strokeAlpha: kotlin.Float, strokeLineWidth: kotlin.Float, strokeLineCap: androidx.compose.ui.graphics.StrokeCap, strokeLineJoin: androidx.compose.ui.graphics.StrokeJoin, strokeLineMiter: kotlin.Float, trimPathStart: kotlin.Float, trimPathEnd: kotlin.Float, trimPathOffset: kotlin.Float): kotlin.Unit"""
    ...

def RenderVectorGroup(group: VectorGroup, configs: _t.Any = ...) -> None:
    """Kotlin: androidx.compose.ui.graphics.vector.RenderVectorGroup(group: androidx.compose.ui.graphics.vector.VectorGroup, configs: kotlin.collections.Map): kotlin.Unit"""
    ...

def path(receiver: ImageVector.Builder, /, name: str, fill: pythonx.compose.ui.graphics.Brush | None, fill_alpha: float, stroke: pythonx.compose.ui.graphics.Brush | None, stroke_alpha: float, stroke_line_width: float, stroke_line_cap: _t.Any, stroke_line_join: _t.Any, stroke_line_miter: float, path_fill_type: _t.Any, path_builder: _t.Callable[[PathBuilder], None]) -> ImageVector.Builder:
    """Kotlin: androidx.compose.ui.graphics.vector.ImageVector.Builder.path(name: kotlin.String, fill: androidx.compose.ui.graphics.Brush?, fillAlpha: kotlin.Float, stroke: androidx.compose.ui.graphics.Brush?, strokeAlpha: kotlin.Float, strokeLineWidth: kotlin.Float, strokeLineCap: androidx.compose.ui.graphics.StrokeCap, strokeLineJoin: androidx.compose.ui.graphics.StrokeJoin, strokeLineMiter: kotlin.Float, pathFillType: androidx.compose.ui.graphics.PathFillType, pathBuilder: kotlin.Function1): androidx.compose.ui.graphics.vector.ImageVector.Builder"""
    ...

def remember_vector_painter__Dp_Dp_Float_Float_String_Color_BlendMode_Boolean_Unit(default_width: float, default_height: float, viewport_width: float = ..., viewport_height: float = ..., name: str = ..., tint_color: _t.Any = ..., tint_blend_mode: _t.Any = ..., auto_mirror: bool = ..., *, content: _t.Callable[[float, float], None]) -> VectorPainter:
    """Kotlin: androidx.compose.ui.graphics.vector.rememberVectorPainter(defaultWidth: androidx.compose.ui.unit.Dp, defaultHeight: androidx.compose.ui.unit.Dp, viewportWidth: kotlin.Float, viewportHeight: kotlin.Float, name: kotlin.String, tintColor: androidx.compose.ui.graphics.Color, tintBlendMode: androidx.compose.ui.graphics.BlendMode, autoMirror: kotlin.Boolean, content: kotlin.Function2): androidx.compose.ui.graphics.vector.VectorPainter"""
    ...

def remember_vector_painter__Dp_Dp_Float_Float_String_Color_BlendMode_Unit(default_width: float, default_height: float, viewport_width: float = ..., viewport_height: float = ..., name: str = ..., tint_color: _t.Any = ..., tint_blend_mode: _t.Any = ..., *, content: _t.Callable[[float, float], None]) -> VectorPainter:
    """Kotlin: androidx.compose.ui.graphics.vector.rememberVectorPainter(defaultWidth: androidx.compose.ui.unit.Dp, defaultHeight: androidx.compose.ui.unit.Dp, viewportWidth: kotlin.Float, viewportHeight: kotlin.Float, name: kotlin.String, tintColor: androidx.compose.ui.graphics.Color, tintBlendMode: androidx.compose.ui.graphics.BlendMode, content: kotlin.Function2): androidx.compose.ui.graphics.vector.VectorPainter"""
    ...

def remember_vector_painter__ImageVector(image: ImageVector) -> VectorPainter:
    """Kotlin: androidx.compose.ui.graphics.vector.rememberVectorPainter(image: androidx.compose.ui.graphics.vector.ImageVector): androidx.compose.ui.graphics.vector.VectorPainter"""
    ...

@_t.overload
def remember_vector_painter(default_width: float, default_height: float, viewport_width: float = ..., viewport_height: float = ..., name: str = ..., tint_color: _t.Any = ..., tint_blend_mode: _t.Any = ..., auto_mirror: bool = ..., *, content: _t.Callable[[float, float], None]) -> VectorPainter: ...
@_t.overload
def remember_vector_painter(default_width: float, default_height: float, viewport_width: float = ..., viewport_height: float = ..., name: str = ..., tint_color: _t.Any = ..., tint_blend_mode: _t.Any = ..., *, content: _t.Callable[[float, float], None]) -> VectorPainter: ...  # type: ignore[overload-cannot-match]
@_t.overload
def remember_vector_painter(image: ImageVector) -> VectorPainter: ...  # type: ignore[overload-cannot-match]
