# GENERATED by scripts/gen_stubs.py from python-multiplatform's Kotlin-named stubs (artifact kotlin-stubs, workflow run 37131041879, commit 452cc807, Compose 1.11.1). Do not edit.
import typing as _t

class _Constraints_callable_module(_t.Protocol):
    """Kotlin: the function Constraints, and the members of the module Constraints"""
    def __call__(self, min_width: int = ..., max_width: int = ..., min_height: int = ..., max_height: int = ...) -> _t.Any: ...
    Infinity: int

class _DpOffset_callable_module(_t.Protocol):
    """Kotlin: the function DpOffset, and the members of the module DpOffset"""
    def __call__(self, x: float, y: float) -> int: ...
    Unspecified: int
    Zero: int

class _DpSize_callable_module(_t.Protocol):
    """Kotlin: the function DpSize, and the members of the module DpSize"""
    def __call__(self, width: float, height: float) -> _t.Any: ...
    Unspecified: _t.Any
    Zero: _t.Any

class _IntOffset_callable_module(_t.Protocol):
    """Kotlin: the function IntOffset, and the members of the module IntOffset"""
    def __call__(self, x: int, y: int) -> int: ...
    Max: int
    Zero: int

class _IntRect_callable_module(_t.Protocol):
    """Kotlin: the function IntRect, and the members of the module IntRect"""
    @_t.overload
    def __call__(self, center: int, radius: int) -> _t.Any: ...
    @_t.overload
    def __call__(self, top_left: int, bottom_right: int) -> _t.Any: ...  # type: ignore[overload-cannot-match]
    @_t.overload
    def __call__(self, offset: int, size: _t.Any) -> _t.Any: ...  # type: ignore[overload-cannot-match]
    Zero: _t.Any

class _IntSize_callable_module(_t.Protocol):
    """Kotlin: the function IntSize, and the members of the module IntSize"""
    def __call__(self, width: int, height: int) -> int: ...
    Zero: int

class _TextUnit_callable_module(_t.Protocol):
    """Kotlin: the function TextUnit, and the members of the module TextUnit"""
    def __call__(self, value: float, type: int) -> _t.Any: ...
    Unspecified: _t.Any

class _Velocity_callable_module(_t.Protocol):
    """Kotlin: the function Velocity, and the members of the module Velocity"""
    def __call__(self, x: float, y: float) -> _t.Any: ...
    Zero: _t.Any

class DpRect:
    """Kotlin: androidx.compose.ui.unit.DpRect"""
    @_t.overload
    def __init__(self, origin: int, size: _t.Any) -> None: ...
    @_t.overload
    def __init__(self, left: float, top: float, right: float, bottom: float) -> None: ...  # type: ignore[overload-cannot-match]
    @property
    def bottom(self) -> float:
        """Kotlin property: androidx.compose.ui.unit.DpRect.bottom (androidx.compose.ui.unit.DpRect.bottom: androidx.compose.ui.unit.Dp)"""
        ...
    @property
    def height(self) -> float:
        """Kotlin property: androidx.compose.ui.unit.height (androidx.compose.ui.unit.DpRect.height: androidx.compose.ui.unit.Dp)"""
        ...
    @property
    def left(self) -> float:
        """Kotlin property: androidx.compose.ui.unit.DpRect.left (androidx.compose.ui.unit.DpRect.left: androidx.compose.ui.unit.Dp)"""
        ...
    @property
    def right(self) -> float:
        """Kotlin property: androidx.compose.ui.unit.DpRect.right (androidx.compose.ui.unit.DpRect.right: androidx.compose.ui.unit.Dp)"""
        ...
    @property
    def size(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.unit.size (androidx.compose.ui.unit.DpRect.size: androidx.compose.ui.unit.DpSize)"""
        ...
    @property
    def top(self) -> float:
        """Kotlin property: androidx.compose.ui.unit.DpRect.top (androidx.compose.ui.unit.DpRect.top: androidx.compose.ui.unit.Dp)"""
        ...
    @property
    def width(self) -> float:
        """Kotlin property: androidx.compose.ui.unit.width (androidx.compose.ui.unit.DpRect.width: androidx.compose.ui.unit.Dp)"""
        ...

class FontScalingLinear:
    """Kotlin: androidx.compose.ui.unit.FontScalingLinear"""
    @property
    def font_scale(self) -> float:
        """Kotlin property: androidx.compose.ui.unit.FontScalingLinear.fontScale (androidx.compose.ui.unit.FontScalingLinear.fontScale: kotlin.Float)"""
        ...

class LayoutDirection:
    """Kotlin: androidx.compose.ui.unit.LayoutDirection"""

def Density(density: float, font_scale: float = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.unit.Density(density: kotlin.Float, fontScale: kotlin.Float): androidx.compose.ui.unit.Density"""
    ...

def IntRect__IntOffset_Int(center: int, radius: int) -> _t.Any:
    """Kotlin: androidx.compose.ui.unit.IntRect(center: androidx.compose.ui.unit.IntOffset, radius: kotlin.Int): androidx.compose.ui.unit.IntRect"""
    ...

def IntRect__IntOffset_IntOffset(top_left: int, bottom_right: int) -> _t.Any:
    """Kotlin: androidx.compose.ui.unit.IntRect(topLeft: androidx.compose.ui.unit.IntOffset, bottomRight: androidx.compose.ui.unit.IntOffset): androidx.compose.ui.unit.IntRect"""
    ...

def IntRect__IntOffset_IntSize(offset: int, size: _t.Any) -> _t.Any:
    """Kotlin: androidx.compose.ui.unit.IntRect(offset: androidx.compose.ui.unit.IntOffset, size: androidx.compose.ui.unit.IntSize): androidx.compose.ui.unit.IntRect"""
    ...

def coerce_at_least(receiver: float, /, minimum_value: float) -> float:
    """Kotlin: androidx.compose.ui.unit.Dp.coerceAtLeast(minimumValue: androidx.compose.ui.unit.Dp): androidx.compose.ui.unit.Dp"""
    ...

def coerce_at_most(receiver: float, /, maximum_value: float) -> float:
    """Kotlin: androidx.compose.ui.unit.Dp.coerceAtMost(maximumValue: androidx.compose.ui.unit.Dp): androidx.compose.ui.unit.Dp"""
    ...

def coerce_in(receiver: float, /, minimum_value: float, maximum_value: float) -> float:
    """Kotlin: androidx.compose.ui.unit.Dp.coerceIn(minimumValue: androidx.compose.ui.unit.Dp, maximumValue: androidx.compose.ui.unit.Dp): androidx.compose.ui.unit.Dp"""
    ...

def constrain_height(receiver: int, /, height: int) -> int:
    """Kotlin: androidx.compose.ui.unit.Constraints.constrainHeight(height: kotlin.Int): kotlin.Int"""
    ...

def constrain_width(receiver: int, /, width: int) -> int:
    """Kotlin: androidx.compose.ui.unit.Constraints.constrainWidth(width: kotlin.Int): kotlin.Int"""
    ...

def constrain__Constraints(receiver: int, /, other_constraints: int) -> _t.Any:
    """Kotlin: androidx.compose.ui.unit.Constraints.constrain(otherConstraints: androidx.compose.ui.unit.Constraints): androidx.compose.ui.unit.Constraints"""
    ...

def constrain__IntSize(receiver: int, /, size: _t.Any) -> int:
    """Kotlin: androidx.compose.ui.unit.Constraints.constrain(size: androidx.compose.ui.unit.IntSize): androidx.compose.ui.unit.IntSize"""
    ...

def is_satisfied_by(receiver: int, /, size: _t.Any) -> bool:
    """Kotlin: androidx.compose.ui.unit.Constraints.isSatisfiedBy(size: androidx.compose.ui.unit.IntSize): kotlin.Boolean"""
    ...

def lerp__DpOffset_DpOffset_Float(start: int, stop: int, fraction: float) -> int:
    """Kotlin: androidx.compose.ui.unit.lerp(start: androidx.compose.ui.unit.DpOffset, stop: androidx.compose.ui.unit.DpOffset, fraction: kotlin.Float): androidx.compose.ui.unit.DpOffset"""
    ...

def lerp__DpSize_DpSize_Float(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any:
    """Kotlin: androidx.compose.ui.unit.lerp(start: androidx.compose.ui.unit.DpSize, stop: androidx.compose.ui.unit.DpSize, fraction: kotlin.Float): androidx.compose.ui.unit.DpSize"""
    ...

def lerp__Dp_Dp_Float(start: float, stop: float, fraction: float) -> float:
    """Kotlin: androidx.compose.ui.unit.lerp(start: androidx.compose.ui.unit.Dp, stop: androidx.compose.ui.unit.Dp, fraction: kotlin.Float): androidx.compose.ui.unit.Dp"""
    ...

def lerp__IntOffset_IntOffset_Float(start: int, stop: int, fraction: float) -> int:
    """Kotlin: androidx.compose.ui.unit.lerp(start: androidx.compose.ui.unit.IntOffset, stop: androidx.compose.ui.unit.IntOffset, fraction: kotlin.Float): androidx.compose.ui.unit.IntOffset"""
    ...

def lerp__IntRect_IntRect_Float(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any:
    """Kotlin: androidx.compose.ui.unit.lerp(start: androidx.compose.ui.unit.IntRect, stop: androidx.compose.ui.unit.IntRect, fraction: kotlin.Float): androidx.compose.ui.unit.IntRect"""
    ...

def lerp__TextUnit_TextUnit_Float(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any:
    """Kotlin: androidx.compose.ui.unit.lerp(start: androidx.compose.ui.unit.TextUnit, stop: androidx.compose.ui.unit.TextUnit, fraction: kotlin.Float): androidx.compose.ui.unit.TextUnit"""
    ...

def max(a: float, b: float) -> float:
    """Kotlin: androidx.compose.ui.unit.max(a: androidx.compose.ui.unit.Dp, b: androidx.compose.ui.unit.Dp): androidx.compose.ui.unit.Dp"""
    ...

def min(a: float, b: float) -> float:
    """Kotlin: androidx.compose.ui.unit.min(a: androidx.compose.ui.unit.Dp, b: androidx.compose.ui.unit.Dp): androidx.compose.ui.unit.Dp"""
    ...

def minus__IntOffset(receiver: int, /, offset: int) -> int:
    """Kotlin: androidx.compose.ui.geometry.Offset.minus(offset: androidx.compose.ui.unit.IntOffset): androidx.compose.ui.geometry.Offset"""
    ...

def minus__Offset(receiver: int, /, offset: int) -> int:
    """Kotlin: androidx.compose.ui.unit.IntOffset.minus(offset: androidx.compose.ui.geometry.Offset): androidx.compose.ui.geometry.Offset"""
    ...

def offset(receiver: int, /, horizontal: int = ..., vertical: int = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.unit.Constraints.offset(horizontal: kotlin.Int, vertical: kotlin.Int): androidx.compose.ui.unit.Constraints"""
    ...

def plus__IntOffset(receiver: int, /, offset: int) -> int:
    """Kotlin: androidx.compose.ui.geometry.Offset.plus(offset: androidx.compose.ui.unit.IntOffset): androidx.compose.ui.geometry.Offset"""
    ...

def plus__Offset(receiver: int, /, offset: int) -> int:
    """Kotlin: androidx.compose.ui.unit.IntOffset.plus(offset: androidx.compose.ui.geometry.Offset): androidx.compose.ui.geometry.Offset"""
    ...

def round(receiver: int, /) -> int:
    """Kotlin: androidx.compose.ui.geometry.Offset.round(): androidx.compose.ui.unit.IntOffset"""
    ...

def round_to_int_rect(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.geometry.Rect.roundToIntRect(): androidx.compose.ui.unit.IntRect"""
    ...

def round_to_int_size(receiver: int, /) -> int:
    """Kotlin: androidx.compose.ui.geometry.Size.roundToIntSize(): androidx.compose.ui.unit.IntSize"""
    ...

def take_or_else__Dp(receiver: float, /, block: _t.Callable[[], _t.Any]) -> float:
    """Kotlin: androidx.compose.ui.unit.Dp.takeOrElse(block: kotlin.Function0): androidx.compose.ui.unit.Dp"""
    ...

def take_or_else__DpOffset(receiver: int, /, block: _t.Callable[[], _t.Any]) -> int:
    """Kotlin: androidx.compose.ui.unit.DpOffset.takeOrElse(block: kotlin.Function0): androidx.compose.ui.unit.DpOffset"""
    ...

def take_or_else__DpSize(receiver: _t.Any, /, block: _t.Callable[[], _t.Any]) -> _t.Any:
    """Kotlin: androidx.compose.ui.unit.DpSize.takeOrElse(block: kotlin.Function0): androidx.compose.ui.unit.DpSize"""
    ...

def take_or_else__TextUnit(receiver: _t.Any, /, block: _t.Callable[[], _t.Any]) -> _t.Any:
    """Kotlin: androidx.compose.ui.unit.TextUnit.takeOrElse(block: kotlin.Function0): androidx.compose.ui.unit.TextUnit"""
    ...

def times__Double_Dp(receiver: float, /, other: float) -> float:
    """Kotlin: kotlin.Double.times(other: androidx.compose.ui.unit.Dp): androidx.compose.ui.unit.Dp"""
    ...

def times__Double_TextUnit(receiver: float, /, other: _t.Any) -> _t.Any:
    """Kotlin: kotlin.Double.times(other: androidx.compose.ui.unit.TextUnit): androidx.compose.ui.unit.TextUnit"""
    ...

def times__Float_Dp(receiver: float, /, other: float) -> float:
    """Kotlin: kotlin.Float.times(other: androidx.compose.ui.unit.Dp): androidx.compose.ui.unit.Dp"""
    ...

def times__Float_DpSize(receiver: float, /, size: _t.Any) -> _t.Any:
    """Kotlin: kotlin.Float.times(size: androidx.compose.ui.unit.DpSize): androidx.compose.ui.unit.DpSize"""
    ...

def times__Float_TextUnit(receiver: float, /, other: _t.Any) -> _t.Any:
    """Kotlin: kotlin.Float.times(other: androidx.compose.ui.unit.TextUnit): androidx.compose.ui.unit.TextUnit"""
    ...

def times__Int_Dp(receiver: int, /, other: float) -> float:
    """Kotlin: kotlin.Int.times(other: androidx.compose.ui.unit.Dp): androidx.compose.ui.unit.Dp"""
    ...

def times__Int_DpSize(receiver: int, /, size: _t.Any) -> _t.Any:
    """Kotlin: kotlin.Int.times(size: androidx.compose.ui.unit.DpSize): androidx.compose.ui.unit.DpSize"""
    ...

def times__Int_IntSize(receiver: int, /, size: _t.Any) -> int:
    """Kotlin: kotlin.Int.times(size: androidx.compose.ui.unit.IntSize): androidx.compose.ui.unit.IntSize"""
    ...

def times__Int_TextUnit(receiver: int, /, other: _t.Any) -> _t.Any:
    """Kotlin: kotlin.Int.times(other: androidx.compose.ui.unit.TextUnit): androidx.compose.ui.unit.TextUnit"""
    ...

def to_int_rect(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.unit.IntSize.toIntRect(): androidx.compose.ui.unit.IntRect"""
    ...

def to_int_size(receiver: int, /) -> int:
    """Kotlin: androidx.compose.ui.geometry.Size.toIntSize(): androidx.compose.ui.unit.IntSize"""
    ...

def to_offset(receiver: int, /) -> int:
    """Kotlin: androidx.compose.ui.unit.IntOffset.toOffset(): androidx.compose.ui.geometry.Offset"""
    ...

def to_rect(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.unit.IntRect.toRect(): androidx.compose.ui.geometry.Rect"""
    ...

def to_size(receiver: _t.Any, /) -> int:
    """Kotlin: androidx.compose.ui.unit.IntSize.toSize(): androidx.compose.ui.geometry.Size"""
    ...

Constraints: _Constraints_callable_module

DpOffset: _DpOffset_callable_module

DpSize: _DpSize_callable_module

IntOffset: _IntOffset_callable_module

IntRect: _IntRect_callable_module

IntSize: _IntSize_callable_module

TextUnit: _TextUnit_callable_module

Velocity: _Velocity_callable_module

def DpRect__DpOffset_DpSize(origin: int, size: _t.Any) -> DpRect:
    """Kotlin: androidx.compose.ui.unit.DpRect(origin: androidx.compose.ui.unit.DpOffset, size: androidx.compose.ui.unit.DpSize): androidx.compose.ui.unit.DpRect"""
    ...

def DpRect__Dp_Dp_Dp_Dp(left: float, top: float, right: float, bottom: float) -> DpRect:
    """Kotlin: androidx.compose.ui.unit.DpRect(left: androidx.compose.ui.unit.Dp, top: androidx.compose.ui.unit.Dp, right: androidx.compose.ui.unit.Dp, bottom: androidx.compose.ui.unit.Dp): androidx.compose.ui.unit.DpRect"""
    ...

@_t.overload
def constrain(receiver: int, /, other_constraints: int) -> _t.Any: ...
@_t.overload
def constrain(receiver: int, /, size: _t.Any) -> int: ...  # type: ignore[overload-cannot-match]

@_t.overload
def lerp(start: int, stop: int, fraction: float) -> int: ...
@_t.overload
def lerp(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any: ...  # type: ignore[overload-cannot-match]
@_t.overload
def lerp(start: float, stop: float, fraction: float) -> float: ...  # type: ignore[overload-cannot-match]
@_t.overload
def lerp(start: int, stop: int, fraction: float) -> int: ...  # type: ignore[overload-cannot-match]
@_t.overload
def lerp(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any: ...  # type: ignore[overload-cannot-match]
@_t.overload
def lerp(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any: ...  # type: ignore[overload-cannot-match]

@_t.overload
def minus(receiver: int, /, offset: int) -> int: ...
@_t.overload
def minus(receiver: int, /, offset: int) -> int: ...  # type: ignore[overload-cannot-match]

@_t.overload
def plus(receiver: int, /, offset: int) -> int: ...
@_t.overload
def plus(receiver: int, /, offset: int) -> int: ...  # type: ignore[overload-cannot-match]

@_t.overload
def take_or_else(receiver: float, /, block: _t.Callable[[], _t.Any]) -> float: ...
@_t.overload
def take_or_else(receiver: int, /, block: _t.Callable[[], _t.Any]) -> int: ...  # type: ignore[overload-cannot-match]
@_t.overload
def take_or_else(receiver: _t.Any, /, block: _t.Callable[[], _t.Any]) -> _t.Any: ...  # type: ignore[overload-cannot-match]
@_t.overload
def take_or_else(receiver: _t.Any, /, block: _t.Callable[[], _t.Any]) -> _t.Any: ...  # type: ignore[overload-cannot-match]

@_t.overload
def times(receiver: float, /, other: float) -> float: ...
@_t.overload
def times(receiver: float, /, other: _t.Any) -> _t.Any: ...  # type: ignore[overload-cannot-match]
@_t.overload
def times(receiver: float, /, other: float) -> float: ...  # type: ignore[overload-cannot-match]
@_t.overload
def times(receiver: float, /, size: _t.Any) -> _t.Any: ...  # type: ignore[overload-cannot-match]
@_t.overload
def times(receiver: float, /, other: _t.Any) -> _t.Any: ...  # type: ignore[overload-cannot-match]
@_t.overload
def times(receiver: int, /, other: float) -> float: ...  # type: ignore[overload-cannot-match]
@_t.overload
def times(receiver: int, /, size: _t.Any) -> _t.Any: ...  # type: ignore[overload-cannot-match]
@_t.overload
def times(receiver: int, /, size: _t.Any) -> int: ...  # type: ignore[overload-cannot-match]
@_t.overload
def times(receiver: int, /, other: _t.Any) -> _t.Any: ...  # type: ignore[overload-cannot-match]

class Dp:
    """Kotlin: androidx.compose.ui.unit.Dp"""
    Hairline: _t.ClassVar[float]
    """Kotlin: androidx.compose.ui.unit.Dp.Hairline(): androidx.compose.ui.unit.Dp"""
    Infinity: _t.ClassVar[float]
    """Kotlin: androidx.compose.ui.unit.Dp.Infinity(): androidx.compose.ui.unit.Dp"""
    Unspecified: _t.ClassVar[float]
    """Kotlin: androidx.compose.ui.unit.Dp.Unspecified(): androidx.compose.ui.unit.Dp"""

class TextUnitType:
    """Kotlin: androidx.compose.ui.unit.TextUnitType"""
    Em: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.unit.TextUnitType.Em(): androidx.compose.ui.unit.TextUnitType"""
    Sp: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.unit.TextUnitType.Sp(): androidx.compose.ui.unit.TextUnitType"""
    Unspecified: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.unit.TextUnitType.Unspecified(): androidx.compose.ui.unit.TextUnitType"""
