# GENERATED by python-multiplatform-gradle-plugin. Do not edit.

import typing as _t

End: _t.Any
"""Kotlin: androidx.compose.foundation.layout.Arrangement.End(): androidx.compose.foundation.layout.Arrangement.Horizontal"""

SpaceBetween: _t.Any
"""Kotlin: androidx.compose.foundation.layout.Arrangement.SpaceBetween(): androidx.compose.foundation.layout.Arrangement.HorizontalOrVertical"""

Start: _t.Any
"""Kotlin: androidx.compose.foundation.layout.Arrangement.Start(): androidx.compose.foundation.layout.Arrangement.Horizontal"""

Top: _t.Any
"""Kotlin: androidx.compose.foundation.layout.Arrangement.Top(): androidx.compose.foundation.layout.Arrangement.Vertical"""

def spacedBy(space: float) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.Arrangement.spacedBy(space: androidx.compose.ui.unit.Dp): androidx.compose.foundation.layout.Arrangement.HorizontalOrVertical"""
    ...
