# GENERATED by tools/gen_stubs.py from python-multiplatform's Kotlin-named stubs (artifact kotlin-stubs, workflow run 37098191598, commit fa2558e3, Compose 1.11.1). Do not edit.
import typing as _t
import pythonx.compose.ui.graphics
import pythonx.compose.ui.unit

class LinkAnnotation:
    """Kotlin: androidx.compose.ui.text.LinkAnnotation"""
    @property
    def link_interaction_listener(self) -> LinkInteractionListener | None:
        """Kotlin property: androidx.compose.ui.text.LinkAnnotation.linkInteractionListener (androidx.compose.ui.text.LinkAnnotation.linkInteractionListener: androidx.compose.ui.text.LinkInteractionListener?)"""
        ...
    @property
    def styles(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.LinkAnnotation.styles (androidx.compose.ui.text.LinkAnnotation.styles: androidx.compose.ui.text.TextLinkStyles?)"""
        ...

class LinkInteractionListener:
    """Kotlin: androidx.compose.ui.text.LinkInteractionListener"""

class MultiParagraphIntrinsics:
    """Kotlin: androidx.compose.ui.text.MultiParagraphIntrinsics"""
    @property
    def annotated_string(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.MultiParagraphIntrinsics.annotatedString (androidx.compose.ui.text.MultiParagraphIntrinsics.annotatedString: androidx.compose.ui.text.AnnotatedString)"""
        ...
    @property
    def has_stale_resolved_fonts(self) -> bool:
        """Kotlin property: androidx.compose.ui.text.MultiParagraphIntrinsics.hasStaleResolvedFonts (androidx.compose.ui.text.MultiParagraphIntrinsics.hasStaleResolvedFonts: kotlin.Boolean)"""
        ...
    @property
    def max_intrinsic_width(self) -> float:
        """Kotlin property: androidx.compose.ui.text.MultiParagraphIntrinsics.maxIntrinsicWidth (androidx.compose.ui.text.MultiParagraphIntrinsics.maxIntrinsicWidth: kotlin.Float)"""
        ...
    @property
    def min_intrinsic_width(self) -> float:
        """Kotlin property: androidx.compose.ui.text.MultiParagraphIntrinsics.minIntrinsicWidth (androidx.compose.ui.text.MultiParagraphIntrinsics.minIntrinsicWidth: kotlin.Float)"""
        ...

class ParagraphIntrinsics:
    """Kotlin: androidx.compose.ui.text.ParagraphIntrinsics"""
    @property
    def has_stale_resolved_fonts(self) -> bool:
        """Kotlin property: androidx.compose.ui.text.ParagraphIntrinsics.hasStaleResolvedFonts (androidx.compose.ui.text.ParagraphIntrinsics.hasStaleResolvedFonts: kotlin.Boolean)"""
        ...
    @property
    def max_intrinsic_width(self) -> float:
        """Kotlin property: androidx.compose.ui.text.ParagraphIntrinsics.maxIntrinsicWidth (androidx.compose.ui.text.ParagraphIntrinsics.maxIntrinsicWidth: kotlin.Float)"""
        ...
    @property
    def min_intrinsic_width(self) -> float:
        """Kotlin property: androidx.compose.ui.text.ParagraphIntrinsics.minIntrinsicWidth (androidx.compose.ui.text.ParagraphIntrinsics.minIntrinsicWidth: kotlin.Float)"""
        ...

class ParagraphStyle:
    """Kotlin: androidx.compose.ui.text.ParagraphStyle"""
    @property
    def deprecated_boxing_hyphens(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.ParagraphStyle.deprecated_boxing_hyphens (androidx.compose.ui.text.ParagraphStyle.deprecated_boxing_hyphens: androidx.compose.ui.text.style.Hyphens?)"""
        ...
    @property
    def deprecated_boxing_line_break(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.ParagraphStyle.deprecated_boxing_lineBreak (androidx.compose.ui.text.ParagraphStyle.deprecated_boxing_lineBreak: androidx.compose.ui.text.style.LineBreak?)"""
        ...
    @property
    def deprecated_boxing_text_align(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.ParagraphStyle.deprecated_boxing_textAlign (androidx.compose.ui.text.ParagraphStyle.deprecated_boxing_textAlign: androidx.compose.ui.text.style.TextAlign?)"""
        ...
    @property
    def deprecated_boxing_text_direction(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.ParagraphStyle.deprecated_boxing_textDirection (androidx.compose.ui.text.ParagraphStyle.deprecated_boxing_textDirection: androidx.compose.ui.text.style.TextDirection?)"""
        ...
    @property
    def hyphens(self) -> int:
        """Kotlin property: androidx.compose.ui.text.ParagraphStyle.hyphens (androidx.compose.ui.text.ParagraphStyle.hyphens: androidx.compose.ui.text.style.Hyphens)"""
        ...
    @property
    def line_break(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.ParagraphStyle.lineBreak (androidx.compose.ui.text.ParagraphStyle.lineBreak: androidx.compose.ui.text.style.LineBreak)"""
        ...
    @property
    def line_height(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.ParagraphStyle.lineHeight (androidx.compose.ui.text.ParagraphStyle.lineHeight: androidx.compose.ui.unit.TextUnit)"""
        ...
    @property
    def line_height_style(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.ParagraphStyle.lineHeightStyle (androidx.compose.ui.text.ParagraphStyle.lineHeightStyle: androidx.compose.ui.text.style.LineHeightStyle?)"""
        ...
    @property
    def platform_style(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.ParagraphStyle.platformStyle (androidx.compose.ui.text.ParagraphStyle.platformStyle: androidx.compose.ui.text.PlatformParagraphStyle?)"""
        ...
    @property
    def text_align(self) -> int:
        """Kotlin property: androidx.compose.ui.text.ParagraphStyle.textAlign (androidx.compose.ui.text.ParagraphStyle.textAlign: androidx.compose.ui.text.style.TextAlign)"""
        ...
    @property
    def text_direction(self) -> int:
        """Kotlin property: androidx.compose.ui.text.ParagraphStyle.textDirection (androidx.compose.ui.text.ParagraphStyle.textDirection: androidx.compose.ui.text.style.TextDirection)"""
        ...
    @property
    def text_indent(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.ParagraphStyle.textIndent (androidx.compose.ui.text.ParagraphStyle.textIndent: androidx.compose.ui.text.style.TextIndent?)"""
        ...
    @property
    def text_motion(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.ParagraphStyle.textMotion (androidx.compose.ui.text.ParagraphStyle.textMotion: androidx.compose.ui.text.style.TextMotion?)"""
        ...

class Placeholder:
    """Kotlin: androidx.compose.ui.text.Placeholder"""
    @property
    def height(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.Placeholder.height (androidx.compose.ui.text.Placeholder.height: androidx.compose.ui.unit.TextUnit)"""
        ...
    @property
    def placeholder_vertical_align(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.Placeholder.placeholderVerticalAlign (androidx.compose.ui.text.Placeholder.placeholderVerticalAlign: androidx.compose.ui.text.PlaceholderVerticalAlign)"""
        ...
    @property
    def width(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.Placeholder.width (androidx.compose.ui.text.Placeholder.width: androidx.compose.ui.unit.TextUnit)"""
        ...

class SpanStyle:
    """Kotlin: androidx.compose.ui.text.SpanStyle"""
    @property
    def alpha(self) -> float:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.alpha (androidx.compose.ui.text.SpanStyle.alpha: kotlin.Float)"""
        ...
    @property
    def background(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.background (androidx.compose.ui.text.SpanStyle.background: androidx.compose.ui.graphics.Color)"""
        ...
    @property
    def baseline_shift(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.baselineShift (androidx.compose.ui.text.SpanStyle.baselineShift: androidx.compose.ui.text.style.BaselineShift?)"""
        ...
    @property
    def brush(self) -> pythonx.compose.ui.graphics.Brush | None:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.brush (androidx.compose.ui.text.SpanStyle.brush: androidx.compose.ui.graphics.Brush?)"""
        ...
    @property
    def color(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.color (androidx.compose.ui.text.SpanStyle.color: androidx.compose.ui.graphics.Color)"""
        ...
    @property
    def draw_style(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.drawStyle (androidx.compose.ui.text.SpanStyle.drawStyle: androidx.compose.ui.graphics.drawscope.DrawStyle?)"""
        ...
    @property
    def font_family(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.fontFamily (androidx.compose.ui.text.SpanStyle.fontFamily: androidx.compose.ui.text.font.FontFamily?)"""
        ...
    @property
    def font_feature_settings(self) -> str | None:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.fontFeatureSettings (androidx.compose.ui.text.SpanStyle.fontFeatureSettings: kotlin.String?)"""
        ...
    @property
    def font_size(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.fontSize (androidx.compose.ui.text.SpanStyle.fontSize: androidx.compose.ui.unit.TextUnit)"""
        ...
    @property
    def font_style(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.fontStyle (androidx.compose.ui.text.SpanStyle.fontStyle: androidx.compose.ui.text.font.FontStyle?)"""
        ...
    @property
    def font_synthesis(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.fontSynthesis (androidx.compose.ui.text.SpanStyle.fontSynthesis: androidx.compose.ui.text.font.FontSynthesis?)"""
        ...
    @property
    def font_weight(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.fontWeight (androidx.compose.ui.text.SpanStyle.fontWeight: androidx.compose.ui.text.font.FontWeight?)"""
        ...
    @property
    def letter_spacing(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.letterSpacing (androidx.compose.ui.text.SpanStyle.letterSpacing: androidx.compose.ui.unit.TextUnit)"""
        ...
    @property
    def locale_list(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.localeList (androidx.compose.ui.text.SpanStyle.localeList: androidx.compose.ui.text.intl.LocaleList?)"""
        ...
    @property
    def platform_style(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.platformStyle (androidx.compose.ui.text.SpanStyle.platformStyle: androidx.compose.ui.text.PlatformSpanStyle?)"""
        ...
    @property
    def shadow(self) -> pythonx.compose.ui.graphics.Shadow | None:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.shadow (androidx.compose.ui.text.SpanStyle.shadow: androidx.compose.ui.graphics.Shadow?)"""
        ...
    @property
    def text_decoration(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.textDecoration (androidx.compose.ui.text.SpanStyle.textDecoration: androidx.compose.ui.text.style.TextDecoration?)"""
        ...
    @property
    def text_geometric_transform(self) -> _t.Any | None:
        """Kotlin property: androidx.compose.ui.text.SpanStyle.textGeometricTransform (androidx.compose.ui.text.SpanStyle.textGeometricTransform: androidx.compose.ui.text.style.TextGeometricTransform?)"""
        ...

class TextLayoutInput:
    """Kotlin: androidx.compose.ui.text.TextLayoutInput"""
    @property
    def constraints(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.TextLayoutInput.constraints (androidx.compose.ui.text.TextLayoutInput.constraints: androidx.compose.ui.unit.Constraints)"""
        ...
    @property
    def density(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.TextLayoutInput.density (androidx.compose.ui.text.TextLayoutInput.density: androidx.compose.ui.unit.Density)"""
        ...
    @property
    def font_family_resolver(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.TextLayoutInput.fontFamilyResolver (androidx.compose.ui.text.TextLayoutInput.fontFamilyResolver: androidx.compose.ui.text.font.FontFamily.Resolver)"""
        ...
    @property
    def layout_direction(self) -> pythonx.compose.ui.unit.LayoutDirection:
        """Kotlin property: androidx.compose.ui.text.TextLayoutInput.layoutDirection (androidx.compose.ui.text.TextLayoutInput.layoutDirection: androidx.compose.ui.unit.LayoutDirection)"""
        ...
    @property
    def max_lines(self) -> int:
        """Kotlin property: androidx.compose.ui.text.TextLayoutInput.maxLines (androidx.compose.ui.text.TextLayoutInput.maxLines: kotlin.Int)"""
        ...
    @property
    def overflow(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.TextLayoutInput.overflow (androidx.compose.ui.text.TextLayoutInput.overflow: androidx.compose.ui.text.style.TextOverflow)"""
        ...
    @property
    def resource_loader(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.TextLayoutInput.resourceLoader (androidx.compose.ui.text.TextLayoutInput.resourceLoader: androidx.compose.ui.text.font.Font.ResourceLoader)"""
        ...
    @property
    def soft_wrap(self) -> bool:
        """Kotlin property: androidx.compose.ui.text.TextLayoutInput.softWrap (androidx.compose.ui.text.TextLayoutInput.softWrap: kotlin.Boolean)"""
        ...
    @property
    def style(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.TextLayoutInput.style (androidx.compose.ui.text.TextLayoutInput.style: androidx.compose.ui.text.TextStyle)"""
        ...
    @property
    def text(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.TextLayoutInput.text (androidx.compose.ui.text.TextLayoutInput.text: androidx.compose.ui.text.AnnotatedString)"""
        ...

class TextLayoutResult:
    """Kotlin: androidx.compose.ui.text.TextLayoutResult"""
    @property
    def did_overflow_height(self) -> bool:
        """Kotlin property: androidx.compose.ui.text.TextLayoutResult.didOverflowHeight (androidx.compose.ui.text.TextLayoutResult.didOverflowHeight: kotlin.Boolean)"""
        ...
    @property
    def did_overflow_width(self) -> bool:
        """Kotlin property: androidx.compose.ui.text.TextLayoutResult.didOverflowWidth (androidx.compose.ui.text.TextLayoutResult.didOverflowWidth: kotlin.Boolean)"""
        ...
    @property
    def first_baseline(self) -> float:
        """Kotlin property: androidx.compose.ui.text.TextLayoutResult.firstBaseline (androidx.compose.ui.text.TextLayoutResult.firstBaseline: kotlin.Float)"""
        ...
    @property
    def has_visual_overflow(self) -> bool:
        """Kotlin property: androidx.compose.ui.text.TextLayoutResult.hasVisualOverflow (androidx.compose.ui.text.TextLayoutResult.hasVisualOverflow: kotlin.Boolean)"""
        ...
    @property
    def last_baseline(self) -> float:
        """Kotlin property: androidx.compose.ui.text.TextLayoutResult.lastBaseline (androidx.compose.ui.text.TextLayoutResult.lastBaseline: kotlin.Float)"""
        ...
    @property
    def layout_input(self) -> TextLayoutInput:
        """Kotlin property: androidx.compose.ui.text.TextLayoutResult.layoutInput (androidx.compose.ui.text.TextLayoutResult.layoutInput: androidx.compose.ui.text.TextLayoutInput)"""
        ...
    @property
    def line_count(self) -> int:
        """Kotlin property: androidx.compose.ui.text.TextLayoutResult.lineCount (androidx.compose.ui.text.TextLayoutResult.lineCount: kotlin.Int)"""
        ...
    @property
    def multi_paragraph(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.text.TextLayoutResult.multiParagraph (androidx.compose.ui.text.TextLayoutResult.multiParagraph: androidx.compose.ui.text.MultiParagraph)"""
        ...
    @property
    def size(self) -> int:
        """Kotlin property: androidx.compose.ui.text.TextLayoutResult.size (androidx.compose.ui.text.TextLayoutResult.size: androidx.compose.ui.unit.IntSize)"""
        ...

def AnnotatedString__String_ParagraphStyle(text: str, paragraph_style: ParagraphStyle) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.AnnotatedString(text: kotlin.String, paragraphStyle: androidx.compose.ui.text.ParagraphStyle): androidx.compose.ui.text.AnnotatedString"""
    ...

def AnnotatedString__String_SpanStyle_ParagraphStyle(text: str, span_style: SpanStyle, paragraph_style: ParagraphStyle | None = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.AnnotatedString(text: kotlin.String, spanStyle: androidx.compose.ui.text.SpanStyle, paragraphStyle: androidx.compose.ui.text.ParagraphStyle?): androidx.compose.ui.text.AnnotatedString"""
    ...

def MultiParagraph(intrinsics: MultiParagraphIntrinsics, max_lines: int = ..., ellipsis: bool = ..., *, width: float) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.MultiParagraph(intrinsics: androidx.compose.ui.text.MultiParagraphIntrinsics, maxLines: kotlin.Int, ellipsis: kotlin.Boolean, width: kotlin.Float): androidx.compose.ui.text.MultiParagraph"""
    ...

def Paragraph__ParagraphIntrinsics_Constraints_Int_TextOverflow(paragraph_intrinsics: ParagraphIntrinsics, constraints: int, max_lines: int = ..., overflow: _t.Any = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.Paragraph(paragraphIntrinsics: androidx.compose.ui.text.ParagraphIntrinsics, constraints: androidx.compose.ui.unit.Constraints, maxLines: kotlin.Int, overflow: androidx.compose.ui.text.style.TextOverflow): androidx.compose.ui.text.Paragraph"""
    ...

def Paragraph__ParagraphIntrinsics_Int_Boolean_Float(paragraph_intrinsics: ParagraphIntrinsics, max_lines: int = ..., ellipsis: bool = ..., *, width: float) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.Paragraph(paragraphIntrinsics: androidx.compose.ui.text.ParagraphIntrinsics, maxLines: kotlin.Int, ellipsis: kotlin.Boolean, width: kotlin.Float): androidx.compose.ui.text.Paragraph"""
    ...

def PlatformTextStyle(span_style: _t.Any | None, paragraph_style: _t.Any | None) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.PlatformTextStyle(spanStyle: androidx.compose.ui.text.PlatformSpanStyle?, paragraphStyle: androidx.compose.ui.text.PlatformParagraphStyle?): androidx.compose.ui.text.PlatformTextStyle"""
    ...

def StringAnnotation(value: str) -> str:
    """Kotlin: androidx.compose.ui.text.StringAnnotation(value: kotlin.String): androidx.compose.ui.text.StringAnnotation"""
    ...

def TextLinkStyles(style: SpanStyle | None = ..., focused_style: SpanStyle | None = ..., hovered_style: SpanStyle | None = ..., pressed_style: SpanStyle | None = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.TextLinkStyles(style: androidx.compose.ui.text.SpanStyle?, focusedStyle: androidx.compose.ui.text.SpanStyle?, hoveredStyle: androidx.compose.ui.text.SpanStyle?, pressedStyle: androidx.compose.ui.text.SpanStyle?): androidx.compose.ui.text.TextLinkStyles"""
    ...

def TextMeasurer(default_font_family_resolver: _t.Any, default_density: _t.Any, default_layout_direction: pythonx.compose.ui.unit.LayoutDirection, cache_size: int = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.TextMeasurer(defaultFontFamilyResolver: androidx.compose.ui.text.font.FontFamily.Resolver, defaultDensity: androidx.compose.ui.unit.Density, defaultLayoutDirection: androidx.compose.ui.unit.LayoutDirection, cacheSize: kotlin.Int): androidx.compose.ui.text.TextMeasurer"""
    ...

def TextRange__Int(index: int) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.TextRange(index: kotlin.Int): androidx.compose.ui.text.TextRange"""
    ...

def TextRange__Int_Int(start: int, end: int) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.TextRange(start: kotlin.Int, end: kotlin.Int): androidx.compose.ui.text.TextRange"""
    ...

def UrlAnnotation(url: str) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.UrlAnnotation(url: kotlin.String): androidx.compose.ui.text.UrlAnnotation"""
    ...

def VerbatimTtsAnnotation(verbatim: str) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.VerbatimTtsAnnotation(verbatim: kotlin.String): androidx.compose.ui.text.VerbatimTtsAnnotation"""
    ...

def build_annotated_string(builder: _t.Callable[[_t.Any], None]) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.buildAnnotatedString(builder: kotlin.Function1): androidx.compose.ui.text.AnnotatedString"""
    ...

def capitalize__AnnotatedString_LocaleList(receiver: _t.Any, /, locale_list: _t.Any = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.AnnotatedString.capitalize(localeList: androidx.compose.ui.text.intl.LocaleList): androidx.compose.ui.text.AnnotatedString"""
    ...

def capitalize__String_Locale(receiver: str, /, locale: _t.Any) -> str:
    """Kotlin: kotlin.String.capitalize(locale: androidx.compose.ui.text.intl.Locale): kotlin.String"""
    ...

def capitalize__String_LocaleList(receiver: str, /, locale_list: _t.Any) -> str:
    """Kotlin: kotlin.String.capitalize(localeList: androidx.compose.ui.text.intl.LocaleList): kotlin.String"""
    ...

def coerce_in(receiver: _t.Any, /, minimum_value: int, maximum_value: int) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.TextRange.coerceIn(minimumValue: kotlin.Int, maximumValue: kotlin.Int): androidx.compose.ui.text.TextRange"""
    ...

def decapitalize__AnnotatedString_LocaleList(receiver: _t.Any, /, locale_list: _t.Any = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.AnnotatedString.decapitalize(localeList: androidx.compose.ui.text.intl.LocaleList): androidx.compose.ui.text.AnnotatedString"""
    ...

def decapitalize__String_Locale(receiver: str, /, locale: _t.Any) -> str:
    """Kotlin: kotlin.String.decapitalize(locale: androidx.compose.ui.text.intl.Locale): kotlin.String"""
    ...

def decapitalize__String_LocaleList(receiver: str, /, locale_list: _t.Any) -> str:
    """Kotlin: kotlin.String.decapitalize(localeList: androidx.compose.ui.text.intl.LocaleList): kotlin.String"""
    ...

def draw_text__TextLayoutResult_Brush_Offset_Float_Shadow_TextDecoration_DrawStyle_BlendMode(receiver: _t.Any, /, text_layout_result: TextLayoutResult, brush: pythonx.compose.ui.graphics.Brush, top_left: int = ..., alpha: float = ..., shadow: pythonx.compose.ui.graphics.Shadow | None = ..., text_decoration: _t.Any | None = ..., draw_style: _t.Any | None = ..., blend_mode: _t.Any = ...) -> None:
    """Kotlin: androidx.compose.ui.graphics.drawscope.DrawScope.drawText(textLayoutResult: androidx.compose.ui.text.TextLayoutResult, brush: androidx.compose.ui.graphics.Brush, topLeft: androidx.compose.ui.geometry.Offset, alpha: kotlin.Float, shadow: androidx.compose.ui.graphics.Shadow?, textDecoration: androidx.compose.ui.text.style.TextDecoration?, drawStyle: androidx.compose.ui.graphics.drawscope.DrawStyle?, blendMode: androidx.compose.ui.graphics.BlendMode): kotlin.Unit"""
    ...

def draw_text__TextLayoutResult_Color_Offset_Float_Shadow_TextDecoration_DrawStyle_BlendMode(receiver: _t.Any, /, text_layout_result: TextLayoutResult, color: _t.Any, top_left: int, alpha: float, shadow: pythonx.compose.ui.graphics.Shadow | None, text_decoration: _t.Any | None, draw_style: _t.Any | None, blend_mode: _t.Any) -> None:
    """Kotlin: androidx.compose.ui.graphics.drawscope.DrawScope.drawText(textLayoutResult: androidx.compose.ui.text.TextLayoutResult, color: androidx.compose.ui.graphics.Color, topLeft: androidx.compose.ui.geometry.Offset, alpha: kotlin.Float, shadow: androidx.compose.ui.graphics.Shadow?, textDecoration: androidx.compose.ui.text.style.TextDecoration?, drawStyle: androidx.compose.ui.graphics.drawscope.DrawStyle?, blendMode: androidx.compose.ui.graphics.BlendMode): kotlin.Unit"""
    ...

def draw_text__TextMeasurer_String_Offset_TextStyle_TextOverflow_Boolean_Int_Size_BlendMode(receiver: _t.Any, /, text_measurer: _t.Any, text: str, top_left: int, style: _t.Any, overflow: _t.Any, soft_wrap: bool, max_lines: int, size: int, blend_mode: _t.Any) -> None:
    """Kotlin: androidx.compose.ui.graphics.drawscope.DrawScope.drawText(textMeasurer: androidx.compose.ui.text.TextMeasurer, text: kotlin.String, topLeft: androidx.compose.ui.geometry.Offset, style: androidx.compose.ui.text.TextStyle, overflow: androidx.compose.ui.text.style.TextOverflow, softWrap: kotlin.Boolean, maxLines: kotlin.Int, size: androidx.compose.ui.geometry.Size, blendMode: androidx.compose.ui.graphics.BlendMode): kotlin.Unit"""
    ...

def lerp__ParagraphStyle_ParagraphStyle_Float(start: ParagraphStyle, stop: ParagraphStyle, fraction: float) -> ParagraphStyle:
    """Kotlin: androidx.compose.ui.text.lerp(start: androidx.compose.ui.text.ParagraphStyle, stop: androidx.compose.ui.text.ParagraphStyle, fraction: kotlin.Float): androidx.compose.ui.text.ParagraphStyle"""
    ...

def lerp__PlatformParagraphStyle_PlatformParagraphStyle_Float(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.lerp(start: androidx.compose.ui.text.PlatformParagraphStyle, stop: androidx.compose.ui.text.PlatformParagraphStyle, fraction: kotlin.Float): androidx.compose.ui.text.PlatformParagraphStyle"""
    ...

def lerp__PlatformSpanStyle_PlatformSpanStyle_Float(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.lerp(start: androidx.compose.ui.text.PlatformSpanStyle, stop: androidx.compose.ui.text.PlatformSpanStyle, fraction: kotlin.Float): androidx.compose.ui.text.PlatformSpanStyle"""
    ...

def lerp__SpanStyle_SpanStyle_Float(start: SpanStyle, stop: SpanStyle, fraction: float) -> SpanStyle:
    """Kotlin: androidx.compose.ui.text.lerp(start: androidx.compose.ui.text.SpanStyle, stop: androidx.compose.ui.text.SpanStyle, fraction: kotlin.Float): androidx.compose.ui.text.SpanStyle"""
    ...

def lerp__TextStyle_TextStyle_Float(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.lerp(start: androidx.compose.ui.text.TextStyle, stop: androidx.compose.ui.text.TextStyle, fraction: kotlin.Float): androidx.compose.ui.text.TextStyle"""
    ...

def remember_text_measurer(cache_size: int = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.rememberTextMeasurer(cacheSize: kotlin.Int): androidx.compose.ui.text.TextMeasurer"""
    ...

def resolve_defaults(style: _t.Any, direction: pythonx.compose.ui.unit.LayoutDirection) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.resolveDefaults(style: androidx.compose.ui.text.TextStyle, direction: androidx.compose.ui.unit.LayoutDirection): androidx.compose.ui.text.TextStyle"""
    ...

def to_lower_case__AnnotatedString_LocaleList(receiver: _t.Any, /, locale_list: _t.Any = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.AnnotatedString.toLowerCase(localeList: androidx.compose.ui.text.intl.LocaleList): androidx.compose.ui.text.AnnotatedString"""
    ...

def to_lower_case__String_Locale(receiver: str, /, locale: _t.Any) -> str:
    """Kotlin: kotlin.String.toLowerCase(locale: androidx.compose.ui.text.intl.Locale): kotlin.String"""
    ...

def to_lower_case__String_LocaleList(receiver: str, /, locale_list: _t.Any) -> str:
    """Kotlin: kotlin.String.toLowerCase(localeList: androidx.compose.ui.text.intl.LocaleList): kotlin.String"""
    ...

def to_upper_case__AnnotatedString_LocaleList(receiver: _t.Any, /, locale_list: _t.Any = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.text.AnnotatedString.toUpperCase(localeList: androidx.compose.ui.text.intl.LocaleList): androidx.compose.ui.text.AnnotatedString"""
    ...

def to_upper_case__String_Locale(receiver: str, /, locale: _t.Any) -> str:
    """Kotlin: kotlin.String.toUpperCase(locale: androidx.compose.ui.text.intl.Locale): kotlin.String"""
    ...

def to_upper_case__String_LocaleList(receiver: str, /, locale_list: _t.Any) -> str:
    """Kotlin: kotlin.String.toUpperCase(localeList: androidx.compose.ui.text.intl.LocaleList): kotlin.String"""
    ...

@_t.overload
def AnnotatedString(text: str, paragraph_style: ParagraphStyle) -> _t.Any: ...
@_t.overload
def AnnotatedString(text: str, span_style: SpanStyle, paragraph_style: ParagraphStyle | None = ...) -> _t.Any: ...  # type: ignore[overload-cannot-match]

@_t.overload
def Paragraph(paragraph_intrinsics: ParagraphIntrinsics, constraints: int, max_lines: int = ..., overflow: _t.Any = ...) -> _t.Any: ...
@_t.overload
def Paragraph(paragraph_intrinsics: ParagraphIntrinsics, max_lines: int = ..., ellipsis: bool = ..., *, width: float) -> _t.Any: ...  # type: ignore[overload-cannot-match]

@_t.overload
def TextRange(index: int) -> _t.Any: ...
@_t.overload
def TextRange(start: int, end: int) -> _t.Any: ...  # type: ignore[overload-cannot-match]

@_t.overload
def capitalize(receiver: _t.Any, /, locale_list: _t.Any = ...) -> _t.Any: ...
@_t.overload
def capitalize(receiver: str, /, locale: _t.Any) -> str: ...  # type: ignore[overload-cannot-match]
@_t.overload
def capitalize(receiver: str, /, locale_list: _t.Any) -> str: ...  # type: ignore[overload-cannot-match]

@_t.overload
def decapitalize(receiver: _t.Any, /, locale_list: _t.Any = ...) -> _t.Any: ...
@_t.overload
def decapitalize(receiver: str, /, locale: _t.Any) -> str: ...  # type: ignore[overload-cannot-match]
@_t.overload
def decapitalize(receiver: str, /, locale_list: _t.Any) -> str: ...  # type: ignore[overload-cannot-match]

@_t.overload
def draw_text(receiver: _t.Any, /, text_layout_result: TextLayoutResult, brush: pythonx.compose.ui.graphics.Brush, top_left: int = ..., alpha: float = ..., shadow: pythonx.compose.ui.graphics.Shadow | None = ..., text_decoration: _t.Any | None = ..., draw_style: _t.Any | None = ..., blend_mode: _t.Any = ...) -> None: ...
@_t.overload
def draw_text(receiver: _t.Any, /, text_layout_result: TextLayoutResult, color: _t.Any, top_left: int, alpha: float, shadow: pythonx.compose.ui.graphics.Shadow | None, text_decoration: _t.Any | None, draw_style: _t.Any | None, blend_mode: _t.Any) -> None: ...  # type: ignore[overload-cannot-match]
@_t.overload
def draw_text(receiver: _t.Any, /, text_measurer: _t.Any, text: str, top_left: int, style: _t.Any, overflow: _t.Any, soft_wrap: bool, max_lines: int, size: int, blend_mode: _t.Any) -> None: ...  # type: ignore[overload-cannot-match]

@_t.overload
def lerp(start: ParagraphStyle, stop: ParagraphStyle, fraction: float) -> ParagraphStyle: ...
@_t.overload
def lerp(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any: ...  # type: ignore[overload-cannot-match]
@_t.overload
def lerp(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any: ...  # type: ignore[overload-cannot-match]
@_t.overload
def lerp(start: SpanStyle, stop: SpanStyle, fraction: float) -> SpanStyle: ...  # type: ignore[overload-cannot-match]
@_t.overload
def lerp(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any: ...  # type: ignore[overload-cannot-match]

@_t.overload
def to_lower_case(receiver: _t.Any, /, locale_list: _t.Any = ...) -> _t.Any: ...
@_t.overload
def to_lower_case(receiver: str, /, locale: _t.Any) -> str: ...  # type: ignore[overload-cannot-match]
@_t.overload
def to_lower_case(receiver: str, /, locale_list: _t.Any) -> str: ...  # type: ignore[overload-cannot-match]

@_t.overload
def to_upper_case(receiver: _t.Any, /, locale_list: _t.Any = ...) -> _t.Any: ...
@_t.overload
def to_upper_case(receiver: str, /, locale: _t.Any) -> str: ...  # type: ignore[overload-cannot-match]
@_t.overload
def to_upper_case(receiver: str, /, locale_list: _t.Any) -> str: ...  # type: ignore[overload-cannot-match]

class Bullet:
    """Kotlin: androidx.compose.ui.text.Bullet"""
    Default: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.Bullet.Default(): androidx.compose.ui.text.Bullet"""
    DefaultIndentation: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.Bullet.DefaultIndentation(): androidx.compose.ui.unit.TextUnit"""
    DefaultPadding: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.Bullet.DefaultPadding(): androidx.compose.ui.unit.TextUnit"""
    DefaultSize: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.Bullet.DefaultSize(): androidx.compose.ui.unit.TextUnit"""

class ComposeUiTextFlags:
    """Kotlin: androidx.compose.ui.text.ComposeUiTextFlags"""
    is_correct_shadow_lerp_with_nulls_enabled: _t.ClassVar[bool]
    """Kotlin: androidx.compose.ui.text.ComposeUiTextFlags.isCorrectShadowLerpWithNullsEnabled(): kotlin.Boolean"""

class FontRasterizationSettings:
    """Kotlin: androidx.compose.ui.text.FontRasterizationSettings"""
    PlatformDefault: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.FontRasterizationSettings.PlatformDefault(): androidx.compose.ui.text.FontRasterizationSettings"""

class PlaceholderVerticalAlign:
    """Kotlin: androidx.compose.ui.text.PlaceholderVerticalAlign"""
    AboveBaseline: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.PlaceholderVerticalAlign.AboveBaseline(): androidx.compose.ui.text.PlaceholderVerticalAlign"""
    Bottom: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.PlaceholderVerticalAlign.Bottom(): androidx.compose.ui.text.PlaceholderVerticalAlign"""
    Center: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.PlaceholderVerticalAlign.Center(): androidx.compose.ui.text.PlaceholderVerticalAlign"""
    TextBottom: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.PlaceholderVerticalAlign.TextBottom(): androidx.compose.ui.text.PlaceholderVerticalAlign"""
    TextCenter: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.PlaceholderVerticalAlign.TextCenter(): androidx.compose.ui.text.PlaceholderVerticalAlign"""
    TextTop: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.PlaceholderVerticalAlign.TextTop(): androidx.compose.ui.text.PlaceholderVerticalAlign"""
    Top: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.PlaceholderVerticalAlign.Top(): androidx.compose.ui.text.PlaceholderVerticalAlign"""

class PlatformParagraphStyle:
    """Kotlin: androidx.compose.ui.text.PlatformParagraphStyle"""
    Default: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.PlatformParagraphStyle.Default(): androidx.compose.ui.text.PlatformParagraphStyle"""

class PlatformSpanStyle:
    """Kotlin: androidx.compose.ui.text.PlatformSpanStyle"""
    Default: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.PlatformSpanStyle.Default(): androidx.compose.ui.text.PlatformSpanStyle"""

class TextDecorationLineStyle:
    """Kotlin: androidx.compose.ui.text.TextDecorationLineStyle"""
    Dashed: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.text.TextDecorationLineStyle.Dashed(): androidx.compose.ui.text.TextDecorationLineStyle"""
    Dotted: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.text.TextDecorationLineStyle.Dotted(): androidx.compose.ui.text.TextDecorationLineStyle"""
    Double: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.text.TextDecorationLineStyle.Double(): androidx.compose.ui.text.TextDecorationLineStyle"""
    Solid: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.text.TextDecorationLineStyle.Solid(): androidx.compose.ui.text.TextDecorationLineStyle"""
    Wavy: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.text.TextDecorationLineStyle.Wavy(): androidx.compose.ui.text.TextDecorationLineStyle"""

class TextGranularity:
    """Kotlin: androidx.compose.ui.text.TextGranularity"""
    Character: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.TextGranularity.Character(): androidx.compose.ui.text.TextGranularity"""
    Word: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.TextGranularity.Word(): androidx.compose.ui.text.TextGranularity"""

class TextInclusionStrategy:
    """Kotlin: androidx.compose.ui.text.TextInclusionStrategy"""
    AnyOverlap: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.TextInclusionStrategy.AnyOverlap(): androidx.compose.ui.text.TextInclusionStrategy"""
    ContainsAll: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.TextInclusionStrategy.ContainsAll(): androidx.compose.ui.text.TextInclusionStrategy"""
    ContainsCenter: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.TextInclusionStrategy.ContainsCenter(): androidx.compose.ui.text.TextInclusionStrategy"""

class TextPainter:
    """Kotlin: androidx.compose.ui.text.TextPainter"""
    @staticmethod
    def paint(canvas: _t.Any, text_layout_result: TextLayoutResult) -> None:
        """Kotlin: androidx.compose.ui.text.TextPainter.paint(canvas: androidx.compose.ui.graphics.Canvas, textLayoutResult: androidx.compose.ui.text.TextLayoutResult): kotlin.Unit"""
        ...

class TextStyle:
    """Kotlin: androidx.compose.ui.text.TextStyle"""
    Default: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.text.TextStyle.Default(): androidx.compose.ui.text.TextStyle"""
