# GENERATED by tools/gen_stubs.py from python-multiplatform's Kotlin-named stubs (artifact kotlin-stubs, workflow run 37077627980, commit 86012ca0, Compose 1.11.1). Do not edit.
# Methods are reached by snake_case names, but their keyword arguments keep Kotlin's names: the runtime does not translate a method's keywords yet.
import typing as _t
import pythonx.compose.ui

class _Composer_materialize(_t.Protocol):
    def __call__(self, modifier: pythonx.compose.ui.Modifier) -> pythonx.compose.ui.Modifier: ...

class _CompositionLocalAccessorScope_mediaQuery(_t.Protocol):
    def __call__(self, query: _t.Callable[[pythonx.compose.ui.UiMediaScope], bool]) -> bool: ...

class _CompositionLocalAccessorScope_mediaQuery__CompositionLocalAccessorScope_Boolean(_t.Protocol):
    def __call__(self, query: _t.Callable[[pythonx.compose.ui.UiMediaScope], bool]) -> bool: ...

class Composer:
    """Kotlin: androidx.compose.runtime.Composer"""
    materialize: _t.ClassVar[_Composer_materialize]

class CompositionLocalAccessorScope:
    """Kotlin: androidx.compose.runtime.CompositionLocalAccessorScope"""
    media_query: _t.ClassVar[_CompositionLocalAccessorScope_mediaQuery]
    media_query__CompositionLocalAccessorScope_Boolean: _t.ClassVar[_CompositionLocalAccessorScope_mediaQuery__CompositionLocalAccessorScope_Boolean]

class State:
    """Kotlin: androidx.compose.runtime.State"""

def Composable(target):
    ...
