# GENERATED by tools/gen_stubs.py from python-multiplatform's Kotlin-named stubs (artifact kotlin-stubs, workflow run 37103737430, commit a5028618, Compose 1.11.1). Do not edit.
import typing as _t
import pythonx.compose.layout
import pythonx.compose.runtime
import pythonx.compose.ui.graphics
import pythonx.compose.ui.unit

class _ImageComposeScene_use(_t.Protocol):
    def __call__(self, block: _t.Callable[[ImageComposeScene], _t.Any | None]) -> _t.Any | None: ...

class _Modifier_absoluteOffset(_t.Protocol):
    @_t.overload
    def __call__(self, x: float = ..., y: float = ...) -> Modifier: ...
    @_t.overload
    def __call__(self, offset: _t.Callable[[_t.Any], _t.Any]) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_absoluteOffset__Dp_Dp(_t.Protocol):
    def __call__(self, x: float = ..., y: float = ...) -> Modifier: ...

class _Modifier_absoluteOffset__IntOffset(_t.Protocol):
    def __call__(self, offset: _t.Callable[[_t.Any], _t.Any]) -> Modifier: ...

class _Modifier_absolutePadding(_t.Protocol):
    def __call__(self, left: float = ..., top: float = ..., right: float = ..., bottom: float = ...) -> Modifier: ...

class _Modifier_alpha(_t.Protocol):
    def __call__(self, alpha: float) -> Modifier: ...

class _Modifier_approachLayout(_t.Protocol):
    def __call__(self, is_measurement_approach_in_progress: _t.Callable[[_t.Any], bool], is_placement_approach_in_progress: _t.Callable[[_t.Any, _t.Any], bool] = ..., *, approach_measure: _t.Callable[[_t.Any, _t.Any, _t.Any], _t.Any]) -> Modifier: ...

class _Modifier_aspectRatio(_t.Protocol):
    def __call__(self, ratio: float, match_height_constraints_first: bool = ...) -> Modifier: ...

class _Modifier_blur(_t.Protocol):
    @_t.overload
    def __call__(self, radius: float, edge_treatment: _t.Any = ...) -> Modifier: ...
    @_t.overload
    def __call__(self, radius_x: float, radius_y: float, edge_treatment: _t.Any = ...) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_blur__Dp_BlurredEdgeTreatment(_t.Protocol):
    def __call__(self, radius: float, edge_treatment: _t.Any = ...) -> Modifier: ...

class _Modifier_blur__Dp_Dp_BlurredEdgeTreatment(_t.Protocol):
    def __call__(self, radius_x: float, radius_y: float, edge_treatment: _t.Any = ...) -> Modifier: ...

class _Modifier_captionBarPadding(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_clearAndSetSemantics(_t.Protocol):
    def __call__(self, properties: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_clip(_t.Protocol):
    def __call__(self, shape: pythonx.compose.ui.graphics.Shape) -> Modifier: ...

class _Modifier_clipToBounds(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_consumeWindowInsets(_t.Protocol):
    @_t.overload
    def __call__(self, padding_values: _t.Any) -> Modifier: ...
    @_t.overload
    def __call__(self, insets: _t.Any) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_consumeWindowInsets__PaddingValues(_t.Protocol):
    def __call__(self, padding_values: _t.Any) -> Modifier: ...

class _Modifier_consumeWindowInsets__WindowInsets(_t.Protocol):
    def __call__(self, insets: _t.Any) -> Modifier: ...

class _Modifier_contentType(_t.Protocol):
    def __call__(self, content_type: _t.Any) -> Modifier: ...

class _Modifier_defaultMinSize(_t.Protocol):
    def __call__(self, min_width: float = ..., min_height: float = ...) -> Modifier: ...

class _Modifier_displayCutoutPadding(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_drawBehind(_t.Protocol):
    def __call__(self, on_draw: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_drawWithCache(_t.Protocol):
    def __call__(self, on_build_draw_cache: _t.Callable[[_t.Any], _t.Any]) -> Modifier: ...

class _Modifier_drawWithContent(_t.Protocol):
    def __call__(self, on_draw: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_dropShadow(_t.Protocol):
    @_t.overload
    def __call__(self, shape: pythonx.compose.ui.graphics.Shape, shadow: _t.Any) -> Modifier: ...
    @_t.overload
    def __call__(self, shape: pythonx.compose.ui.graphics.Shape, block: _t.Callable[[_t.Any], None]) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_dropShadow__Shape_Shadow(_t.Protocol):
    def __call__(self, shape: pythonx.compose.ui.graphics.Shape, shadow: _t.Any) -> Modifier: ...

class _Modifier_dropShadow__Shape_Unit(_t.Protocol):
    def __call__(self, shape: pythonx.compose.ui.graphics.Shape, block: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_fillMaxHeight(_t.Protocol):
    def __call__(self, fraction: float = ...) -> Modifier: ...

class _Modifier_fillMaxSize(_t.Protocol):
    def __call__(self, fraction: float = ...) -> Modifier: ...

class _Modifier_fillMaxWidth(_t.Protocol):
    def __call__(self, fraction: float = ...) -> Modifier: ...

class _Modifier_fitInside(_t.Protocol):
    def __call__(self, rulers: _t.Any) -> Modifier: ...

class _Modifier_fitOutside(_t.Protocol):
    def __call__(self, rulers: _t.Any) -> Modifier: ...

class _Modifier_focusModifier(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_focusOrder(_t.Protocol):
    @_t.overload
    def __call__(self, focus_requester: _t.Any) -> Modifier: ...
    @_t.overload
    def __call__(self, focus_requester: _t.Any, focus_order_receiver: _t.Callable[[_t.Any], None]) -> Modifier: ...  # type: ignore[overload-cannot-match]
    @_t.overload
    def __call__(self, focus_order_receiver: _t.Callable[[_t.Any], None]) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_focusOrder__FocusRequester(_t.Protocol):
    def __call__(self, focus_requester: _t.Any) -> Modifier: ...

class _Modifier_focusOrder__FocusRequester_Unit(_t.Protocol):
    def __call__(self, focus_requester: _t.Any, focus_order_receiver: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_focusOrder__Unit(_t.Protocol):
    def __call__(self, focus_order_receiver: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_focusProperties(_t.Protocol):
    def __call__(self, scope: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_focusRequester(_t.Protocol):
    def __call__(self, focus_requester: _t.Any) -> Modifier: ...

class _Modifier_focusRestorer(_t.Protocol):
    @_t.overload
    def __call__(self, fallback: _t.Any = ...) -> Modifier: ...
    @_t.overload
    def __call__(self, on_restore_failed: _t.Callable[[], _t.Any] | None) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_focusRestorer__androidx_compose_ui_Modifier_androidx_compose_ui_focus_FocusRequester(_t.Protocol):
    def __call__(self, fallback: _t.Any = ...) -> Modifier: ...

class _Modifier_focusRestorer__androidx_compose_ui_Modifier_kotlin_Function0____androidx_compose_ui_focus_FocusRequester(_t.Protocol):
    def __call__(self, on_restore_failed: _t.Callable[[], _t.Any] | None) -> Modifier: ...

class _Modifier_focusTarget(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_graphicsLayer(_t.Protocol):
    @_t.overload
    def __call__(self, scale_x: float, scale_y: float, alpha: float, translation_x: float, translation_y: float, shadow_elevation: float, rotation_x: float, rotation_y: float, rotation_z: float, camera_distance: float, transform_origin: _t.Any, shape: pythonx.compose.ui.graphics.Shape, clip: bool, render_effect: pythonx.compose.ui.graphics.RenderEffect | None, ambient_shadow_color: _t.Any, spot_shadow_color: _t.Any, compositing_strategy: _t.Any, blend_mode: _t.Any, color_filter: pythonx.compose.ui.graphics.ColorFilter | None) -> Modifier: ...
    @_t.overload
    def __call__(self, block: _t.Callable[[_t.Any], None]) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_graphicsLayer__Float_Float_Float_Float_Float_Float_Float_Float_Float_Float_TransformOrigin_Shape_Boolean_RenderEffect_Color_Color_CompositingStrategy_BlendMode_ColorFilter(_t.Protocol):
    def __call__(self, scale_x: float, scale_y: float, alpha: float, translation_x: float, translation_y: float, shadow_elevation: float, rotation_x: float, rotation_y: float, rotation_z: float, camera_distance: float, transform_origin: _t.Any, shape: pythonx.compose.ui.graphics.Shape, clip: bool, render_effect: pythonx.compose.ui.graphics.RenderEffect | None, ambient_shadow_color: _t.Any, spot_shadow_color: _t.Any, compositing_strategy: _t.Any, blend_mode: _t.Any, color_filter: pythonx.compose.ui.graphics.ColorFilter | None) -> Modifier: ...

class _Modifier_graphicsLayer__Unit(_t.Protocol):
    def __call__(self, block: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_height(_t.Protocol):
    @_t.overload
    def __call__(self, height: float) -> Modifier: ...
    @_t.overload
    def __call__(self, intrinsic_size: pythonx.compose.layout.IntrinsicSize) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_heightIn(_t.Protocol):
    def __call__(self, min: float = ..., max: float = ...) -> Modifier: ...

class _Modifier_height__Dp(_t.Protocol):
    def __call__(self, height: float) -> Modifier: ...

class _Modifier_height__IntrinsicSize(_t.Protocol):
    def __call__(self, intrinsic_size: pythonx.compose.layout.IntrinsicSize) -> Modifier: ...

class _Modifier_imePadding(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_innerShadow(_t.Protocol):
    @_t.overload
    def __call__(self, shape: pythonx.compose.ui.graphics.Shape, shadow: _t.Any) -> Modifier: ...
    @_t.overload
    def __call__(self, shape: pythonx.compose.ui.graphics.Shape, block: _t.Callable[[_t.Any], None]) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_innerShadow__Shape_Shadow(_t.Protocol):
    def __call__(self, shape: pythonx.compose.ui.graphics.Shape, shadow: _t.Any) -> Modifier: ...

class _Modifier_innerShadow__Shape_Unit(_t.Protocol):
    def __call__(self, shape: pythonx.compose.ui.graphics.Shape, block: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_inspectable(_t.Protocol):
    def __call__(self, inspector_info: _t.Callable[[_t.Any], None], factory: _t.Callable[[Modifier], Modifier]) -> Modifier: ...

class _Modifier_keepScreenOn(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_layout(_t.Protocol):
    def __call__(self, measure: _t.Callable[[_t.Any, _t.Any, _t.Any], _t.Any]) -> Modifier: ...

class _Modifier_layoutBounds(_t.Protocol):
    def __call__(self, holder: _t.Any) -> Modifier: ...

class _Modifier_mandatorySystemGesturesPadding(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_minimumInteractiveComponentSize(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_modifierLocalConsumer(_t.Protocol):
    def __call__(self, consumer: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_modifierLocalProvider(_t.Protocol):
    def __call__(self, key: _t.Any, value: _t.Callable[[], _t.Any | None]) -> Modifier: ...

class _Modifier_mouseScrollFilter(_t.Protocol):
    def __call__(self, on_mouse_scroll: _t.Callable[[_t.Any, _t.Any], bool]) -> Modifier: ...

class _Modifier_navigationBarsPadding(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_nestedScroll(_t.Protocol):
    def __call__(self, connection: _t.Any, dispatcher: _t.Any | None = ...) -> Modifier: ...

class _Modifier_offset(_t.Protocol):
    @_t.overload
    def __call__(self, x: float = ..., y: float = ...) -> Modifier: ...
    @_t.overload
    def __call__(self, offset: _t.Callable[[_t.Any], _t.Any]) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_offset__Dp_Dp(_t.Protocol):
    def __call__(self, x: float = ..., y: float = ...) -> Modifier: ...

class _Modifier_offset__IntOffset(_t.Protocol):
    def __call__(self, offset: _t.Callable[[_t.Any], _t.Any]) -> Modifier: ...

class _Modifier_onConsumedWindowInsetsChanged(_t.Protocol):
    def __call__(self, block: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_onFirstVisible(_t.Protocol):
    def __call__(self, min_duration_ms: int = ..., min_fraction_visible: float = ..., viewport_bounds: _t.Any | None = ..., *, callback: _t.Callable[[], None]) -> Modifier: ...

class _Modifier_onFocusChanged(_t.Protocol):
    def __call__(self, on_focus_changed: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_onFocusEvent(_t.Protocol):
    def __call__(self, on_focus_event: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_onGloballyPositioned(_t.Protocol):
    def __call__(self, on_globally_positioned: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_onInterceptKeyBeforeSoftKeyboard(_t.Protocol):
    def __call__(self, on_intercept_key_before_soft_keyboard: _t.Callable[[_t.Any], bool]) -> Modifier: ...

class _Modifier_onKeyEvent(_t.Protocol):
    def __call__(self, on_key_event: _t.Callable[[_t.Any], bool]) -> Modifier: ...

class _Modifier_onLayoutRectChanged(_t.Protocol):
    def __call__(self, throttle_millis: int = ..., debounce_millis: int = ..., *, callback: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_onPlaced(_t.Protocol):
    def __call__(self, on_placed: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_onPointerEvent(_t.Protocol):
    def __call__(self, event_type: _t.Any, __a1: _t.Any, /, on_event: _t.Callable[[_t.Any, _t.Any], None]) -> Modifier: ...

class _Modifier_onPreInterceptKeyBeforeSoftKeyboard(_t.Protocol):
    def __call__(self, on_pre_intercept_key_before_soft_keyboard: _t.Callable[[_t.Any], bool]) -> Modifier: ...

class _Modifier_onPreRotaryScrollEvent(_t.Protocol):
    def __call__(self, on_pre_rotary_scroll_event: _t.Callable[[_t.Any], bool]) -> Modifier: ...

class _Modifier_onPreviewKeyEvent(_t.Protocol):
    def __call__(self, on_preview_key_event: _t.Callable[[_t.Any], bool]) -> Modifier: ...

class _Modifier_onRotaryScrollEvent(_t.Protocol):
    def __call__(self, on_rotary_scroll_event: _t.Callable[[_t.Any], bool]) -> Modifier: ...

class _Modifier_onSizeChanged(_t.Protocol):
    def __call__(self, on_size_changed: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_onVisibilityChanged(_t.Protocol):
    def __call__(self, min_duration_ms: int = ..., min_fraction_visible: float = ..., viewport_bounds: _t.Any | None = ..., *, callback: _t.Callable[[bool], None]) -> Modifier: ...

class _Modifier_padding(_t.Protocol):
    @_t.overload
    def __call__(self, all: float) -> Modifier: ...
    @_t.overload
    def __call__(self, horizontal: float = ..., vertical: float = ...) -> Modifier: ...  # type: ignore[overload-cannot-match]
    @_t.overload
    def __call__(self, start: float = ..., top: float = ..., end: float = ..., bottom: float = ...) -> Modifier: ...  # type: ignore[overload-cannot-match]
    @_t.overload
    def __call__(self, padding_values: _t.Any) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_paddingFrom(_t.Protocol):
    @_t.overload
    def __call__(self, alignment_line: _t.Any, before: float = ..., after: float = ...) -> Modifier: ...
    @_t.overload
    def __call__(self, alignment_line: _t.Any, before: _t.Any = ..., after: _t.Any = ...) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_paddingFromBaseline(_t.Protocol):
    @_t.overload
    def __call__(self, top: float = ..., bottom: float = ...) -> Modifier: ...
    @_t.overload
    def __call__(self, top: _t.Any = ..., bottom: _t.Any = ...) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_paddingFromBaseline__Dp_Dp(_t.Protocol):
    def __call__(self, top: float = ..., bottom: float = ...) -> Modifier: ...

class _Modifier_paddingFromBaseline__TextUnit_TextUnit(_t.Protocol):
    def __call__(self, top: _t.Any = ..., bottom: _t.Any = ...) -> Modifier: ...

class _Modifier_paddingFrom__AlignmentLine_Dp_Dp(_t.Protocol):
    def __call__(self, alignment_line: _t.Any, before: float = ..., after: float = ...) -> Modifier: ...

class _Modifier_paddingFrom__AlignmentLine_TextUnit_TextUnit(_t.Protocol):
    def __call__(self, alignment_line: _t.Any, before: _t.Any = ..., after: _t.Any = ...) -> Modifier: ...

class _Modifier_padding__Dp(_t.Protocol):
    def __call__(self, all: float) -> Modifier: ...

class _Modifier_padding__Dp_Dp(_t.Protocol):
    def __call__(self, horizontal: float = ..., vertical: float = ...) -> Modifier: ...

class _Modifier_padding__Dp_Dp_Dp_Dp(_t.Protocol):
    def __call__(self, start: float = ..., top: float = ..., end: float = ..., bottom: float = ...) -> Modifier: ...

class _Modifier_padding__PaddingValues(_t.Protocol):
    def __call__(self, padding_values: _t.Any) -> Modifier: ...

class _Modifier_paint(_t.Protocol):
    def __call__(self, painter: _t.Any, size_to_intrinsics: bool = ..., alignment: _t.Any = ..., content_scale: _t.Any = ..., alpha: float = ..., color_filter: pythonx.compose.ui.graphics.ColorFilter | None = ...) -> Modifier: ...

class _Modifier_pointerHoverIcon(_t.Protocol):
    def __call__(self, icon: _t.Any, override_descendants: bool = ...) -> Modifier: ...

class _Modifier_pointerInput(_t.Protocol):
    @_t.overload
    def __call__(self, key1: _t.Any | None, key2: _t.Any | None, block: _t.Any) -> Modifier: ...
    @_t.overload
    def __call__(self, key1: _t.Any | None, block: _t.Any) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_pointerInput__Any_Any_PointerInputEventHandler(_t.Protocol):
    def __call__(self, key1: _t.Any | None, key2: _t.Any | None, block: _t.Any) -> Modifier: ...

class _Modifier_pointerInput__Any_PointerInputEventHandler(_t.Protocol):
    def __call__(self, key1: _t.Any | None, block: _t.Any) -> Modifier: ...

class _Modifier_pointerMoveFilter(_t.Protocol):
    def __call__(self, on_move: _t.Callable[[_t.Any], bool] = ..., on_exit: _t.Callable[[], bool] = ..., on_enter: _t.Callable[[], bool] = ...) -> Modifier: ...

class _Modifier_preferredFrameRate(_t.Protocol):
    @_t.overload
    def __call__(self, frame_rate: float) -> Modifier: ...
    @_t.overload
    def __call__(self, frame_rate_category: _t.Any) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_preferredFrameRate__Float(_t.Protocol):
    def __call__(self, frame_rate: float) -> Modifier: ...

class _Modifier_preferredFrameRate__FrameRateCategory(_t.Protocol):
    def __call__(self, frame_rate_category: _t.Any) -> Modifier: ...

class _Modifier_pullToRefresh(_t.Protocol):
    def __call__(self, is_refreshing: bool, state: _t.Any, enabled: bool = ..., threshold: float = ..., *, on_refresh: _t.Callable[[], None]) -> Modifier: ...

class _Modifier_recalculateWindowInsets(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_requiredHeight(_t.Protocol):
    @_t.overload
    def __call__(self, height: float) -> Modifier: ...
    @_t.overload
    def __call__(self, intrinsic_size: pythonx.compose.layout.IntrinsicSize) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_requiredHeightIn(_t.Protocol):
    def __call__(self, min: float = ..., max: float = ...) -> Modifier: ...

class _Modifier_requiredHeight__Dp(_t.Protocol):
    def __call__(self, height: float) -> Modifier: ...

class _Modifier_requiredHeight__IntrinsicSize(_t.Protocol):
    def __call__(self, intrinsic_size: pythonx.compose.layout.IntrinsicSize) -> Modifier: ...

class _Modifier_requiredSize(_t.Protocol):
    @_t.overload
    def __call__(self, size: float) -> Modifier: ...
    @_t.overload
    def __call__(self, size: _t.Any) -> Modifier: ...  # type: ignore[overload-cannot-match]
    @_t.overload
    def __call__(self, width: float, height: float) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_requiredSizeIn(_t.Protocol):
    def __call__(self, min_width: float = ..., min_height: float = ..., max_width: float = ..., max_height: float = ...) -> Modifier: ...

class _Modifier_requiredSize__Dp(_t.Protocol):
    def __call__(self, size: float) -> Modifier: ...

class _Modifier_requiredSize__DpSize(_t.Protocol):
    def __call__(self, size: _t.Any) -> Modifier: ...

class _Modifier_requiredSize__Dp_Dp(_t.Protocol):
    def __call__(self, width: float, height: float) -> Modifier: ...

class _Modifier_requiredWidth(_t.Protocol):
    @_t.overload
    def __call__(self, width: float) -> Modifier: ...
    @_t.overload
    def __call__(self, intrinsic_size: pythonx.compose.layout.IntrinsicSize) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_requiredWidthIn(_t.Protocol):
    def __call__(self, min: float = ..., max: float = ...) -> Modifier: ...

class _Modifier_requiredWidth__Dp(_t.Protocol):
    def __call__(self, width: float) -> Modifier: ...

class _Modifier_requiredWidth__IntrinsicSize(_t.Protocol):
    def __call__(self, intrinsic_size: pythonx.compose.layout.IntrinsicSize) -> Modifier: ...

class _Modifier_rotate(_t.Protocol):
    def __call__(self, degrees: float) -> Modifier: ...

class _Modifier_safeContentPadding(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_safeDrawingPadding(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_safeGesturesPadding(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_scale(_t.Protocol):
    @_t.overload
    def __call__(self, scale: float) -> Modifier: ...
    @_t.overload
    def __call__(self, scale_x: float, scale_y: float) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_scale__Float(_t.Protocol):
    def __call__(self, scale: float) -> Modifier: ...

class _Modifier_scale__Float_Float(_t.Protocol):
    def __call__(self, scale_x: float, scale_y: float) -> Modifier: ...

class _Modifier_semantics(_t.Protocol):
    def __call__(self, merge_descendants: bool = ..., *, properties: _t.Callable[[_t.Any], None]) -> Modifier: ...

class _Modifier_sensitiveContent(_t.Protocol):
    def __call__(self, is_content_sensitive: bool = ...) -> Modifier: ...

class _Modifier_shadow(_t.Protocol):
    def __call__(self, elevation: float, shape: pythonx.compose.ui.graphics.Shape = ..., clip: bool = ..., ambient_color: _t.Any = ..., spot_color: _t.Any = ...) -> Modifier: ...

class _Modifier_size(_t.Protocol):
    @_t.overload
    def __call__(self, size: float) -> Modifier: ...
    @_t.overload
    def __call__(self, size: _t.Any) -> Modifier: ...  # type: ignore[overload-cannot-match]
    @_t.overload
    def __call__(self, width: float, height: float) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_sizeIn(_t.Protocol):
    def __call__(self, min_width: float = ..., min_height: float = ..., max_width: float = ..., max_height: float = ...) -> Modifier: ...

class _Modifier_size__Dp(_t.Protocol):
    def __call__(self, size: float) -> Modifier: ...

class _Modifier_size__DpSize(_t.Protocol):
    def __call__(self, size: _t.Any) -> Modifier: ...

class _Modifier_size__Dp_Dp(_t.Protocol):
    def __call__(self, width: float, height: float) -> Modifier: ...

class _Modifier_statusBarsPadding(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_stylusHoverIcon(_t.Protocol):
    def __call__(self, icon: _t.Any, override_descendants: bool = ..., touch_bounds_expansion: _t.Any | None = ...) -> Modifier: ...

class _Modifier_systemBarsPadding(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_systemGesturesPadding(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_testTag(_t.Protocol):
    def __call__(self, tag: str) -> Modifier: ...

class _Modifier_toolingGraphicsLayer(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_visible(_t.Protocol):
    def __call__(self, visible: bool) -> Modifier: ...

class _Modifier_waterfallPadding(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_width(_t.Protocol):
    @_t.overload
    def __call__(self, width: float) -> Modifier: ...
    @_t.overload
    def __call__(self, intrinsic_size: pythonx.compose.layout.IntrinsicSize) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_widthIn(_t.Protocol):
    def __call__(self, min: float = ..., max: float = ...) -> Modifier: ...

class _Modifier_width__Dp(_t.Protocol):
    def __call__(self, width: float) -> Modifier: ...

class _Modifier_width__IntrinsicSize(_t.Protocol):
    def __call__(self, intrinsic_size: pythonx.compose.layout.IntrinsicSize) -> Modifier: ...

class _Modifier_windowInsetsBottomHeight(_t.Protocol):
    def __call__(self, insets: _t.Any) -> Modifier: ...

class _Modifier_windowInsetsEndWidth(_t.Protocol):
    def __call__(self, insets: _t.Any) -> Modifier: ...

class _Modifier_windowInsetsPadding(_t.Protocol):
    def __call__(self, insets: _t.Any) -> Modifier: ...

class _Modifier_windowInsetsStartWidth(_t.Protocol):
    def __call__(self, insets: _t.Any) -> Modifier: ...

class _Modifier_windowInsetsTopHeight(_t.Protocol):
    def __call__(self, insets: _t.Any) -> Modifier: ...

class _Modifier_wrapContentHeight(_t.Protocol):
    def __call__(self, align: Alignment.Vertical = ..., unbounded: bool = ...) -> Modifier: ...

class _Modifier_wrapContentSize(_t.Protocol):
    def __call__(self, align: _t.Any = ..., unbounded: bool = ...) -> Modifier: ...

class _Modifier_wrapContentWidth(_t.Protocol):
    def __call__(self, align: Alignment.Horizontal = ..., unbounded: bool = ...) -> Modifier: ...

class _Modifier_zIndex(_t.Protocol):
    def __call__(self, z_index: float) -> Modifier: ...

class BiasAbsoluteAlignment:
    """Kotlin: androidx.compose.ui.BiasAbsoluteAlignment"""
    def __init__(self, horizontalBias: float, verticalBias: float) -> None:
        """Kotlin constructor: androidx.compose.ui.BiasAbsoluteAlignment (androidx.compose.ui.BiasAbsoluteAlignment(horizontalBias: kotlin.Float, verticalBias: kotlin.Float): androidx.compose.ui.BiasAbsoluteAlignment)"""
        ...
    @property
    def horizontal_bias(self) -> float:
        """Kotlin property: androidx.compose.ui.BiasAbsoluteAlignment.horizontalBias (androidx.compose.ui.BiasAbsoluteAlignment.horizontalBias: kotlin.Float)"""
        ...
    @property
    def vertical_bias(self) -> float:
        """Kotlin property: androidx.compose.ui.BiasAbsoluteAlignment.verticalBias (androidx.compose.ui.BiasAbsoluteAlignment.verticalBias: kotlin.Float)"""
        ...

class BiasAlignment:
    """Kotlin: androidx.compose.ui.BiasAlignment"""
    def __init__(self, horizontalBias: float, verticalBias: float) -> None:
        """Kotlin constructor: androidx.compose.ui.BiasAlignment (androidx.compose.ui.BiasAlignment(horizontalBias: kotlin.Float, verticalBias: kotlin.Float): androidx.compose.ui.BiasAlignment)"""
        ...
    @property
    def horizontal_bias(self) -> float:
        """Kotlin property: androidx.compose.ui.BiasAlignment.horizontalBias (androidx.compose.ui.BiasAlignment.horizontalBias: kotlin.Float)"""
        ...
    @property
    def vertical_bias(self) -> float:
        """Kotlin property: androidx.compose.ui.BiasAlignment.verticalBias (androidx.compose.ui.BiasAlignment.verticalBias: kotlin.Float)"""
        ...

class CombinedModifier(Modifier):
    """Kotlin: androidx.compose.ui.CombinedModifier"""
    def __init__(self, outer: Modifier, inner: Modifier) -> None:
        """Kotlin constructor: androidx.compose.ui.CombinedModifier (androidx.compose.ui.CombinedModifier(outer: androidx.compose.ui.Modifier, inner: androidx.compose.ui.Modifier): androidx.compose.ui.CombinedModifier)"""
        ...

class ImageComposeScene:
    """Kotlin: androidx.compose.ui.ImageComposeScene"""
    use: _t.ClassVar[_ImageComposeScene_use]
    @property
    def constraints(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.ImageComposeScene.constraints (androidx.compose.ui.ImageComposeScene.constraints: androidx.compose.ui.unit.Constraints)"""
        ...
    @constraints.setter
    def constraints(self, value: int) -> None:
        """Kotlin property: androidx.compose.ui.ImageComposeScene.constraints="""
        ...
    @property
    def content_size(self) -> int:
        """Kotlin property: androidx.compose.ui.ImageComposeScene.contentSize (androidx.compose.ui.ImageComposeScene.contentSize: androidx.compose.ui.unit.IntSize)"""
        ...
    @property
    def layout_direction(self) -> pythonx.compose.ui.unit.LayoutDirection:
        """Kotlin property: androidx.compose.ui.ImageComposeScene.layoutDirection (androidx.compose.ui.ImageComposeScene.layoutDirection: androidx.compose.ui.unit.LayoutDirection)"""
        ...
    @layout_direction.setter
    def layout_direction(self, value: pythonx.compose.ui.unit.LayoutDirection) -> None:
        """Kotlin property: androidx.compose.ui.ImageComposeScene.layoutDirection="""
        ...

class Modifier:
    """Kotlin: androidx.compose.ui.Modifier"""
    absolute_offset: _t.ClassVar[_Modifier_absoluteOffset]
    absolute_offset__Dp_Dp: _t.ClassVar[_Modifier_absoluteOffset__Dp_Dp]
    absolute_offset__IntOffset: _t.ClassVar[_Modifier_absoluteOffset__IntOffset]
    absolute_padding: _t.ClassVar[_Modifier_absolutePadding]
    alpha: _t.ClassVar[_Modifier_alpha]
    approach_layout: _t.ClassVar[_Modifier_approachLayout]
    aspect_ratio: _t.ClassVar[_Modifier_aspectRatio]
    blur: _t.ClassVar[_Modifier_blur]
    blur__Dp_BlurredEdgeTreatment: _t.ClassVar[_Modifier_blur__Dp_BlurredEdgeTreatment]
    blur__Dp_Dp_BlurredEdgeTreatment: _t.ClassVar[_Modifier_blur__Dp_Dp_BlurredEdgeTreatment]
    caption_bar_padding: _t.ClassVar[_Modifier_captionBarPadding]
    clear_and_set_semantics: _t.ClassVar[_Modifier_clearAndSetSemantics]
    clip: _t.ClassVar[_Modifier_clip]
    clip_to_bounds: _t.ClassVar[_Modifier_clipToBounds]
    consume_window_insets: _t.ClassVar[_Modifier_consumeWindowInsets]
    consume_window_insets__PaddingValues: _t.ClassVar[_Modifier_consumeWindowInsets__PaddingValues]
    consume_window_insets__WindowInsets: _t.ClassVar[_Modifier_consumeWindowInsets__WindowInsets]
    content_type: _t.ClassVar[_Modifier_contentType]
    default_min_size: _t.ClassVar[_Modifier_defaultMinSize]
    display_cutout_padding: _t.ClassVar[_Modifier_displayCutoutPadding]
    draw_behind: _t.ClassVar[_Modifier_drawBehind]
    draw_with_cache: _t.ClassVar[_Modifier_drawWithCache]
    draw_with_content: _t.ClassVar[_Modifier_drawWithContent]
    drop_shadow: _t.ClassVar[_Modifier_dropShadow]
    drop_shadow__Shape_Shadow: _t.ClassVar[_Modifier_dropShadow__Shape_Shadow]
    drop_shadow__Shape_Unit: _t.ClassVar[_Modifier_dropShadow__Shape_Unit]
    fill_max_height: _t.ClassVar[_Modifier_fillMaxHeight]
    fill_max_size: _t.ClassVar[_Modifier_fillMaxSize]
    fill_max_width: _t.ClassVar[_Modifier_fillMaxWidth]
    fit_inside: _t.ClassVar[_Modifier_fitInside]
    fit_outside: _t.ClassVar[_Modifier_fitOutside]
    focus_modifier: _t.ClassVar[_Modifier_focusModifier]
    focus_order: _t.ClassVar[_Modifier_focusOrder]
    focus_order__FocusRequester: _t.ClassVar[_Modifier_focusOrder__FocusRequester]
    focus_order__FocusRequester_Unit: _t.ClassVar[_Modifier_focusOrder__FocusRequester_Unit]
    focus_order__Unit: _t.ClassVar[_Modifier_focusOrder__Unit]
    focus_properties: _t.ClassVar[_Modifier_focusProperties]
    focus_requester: _t.ClassVar[_Modifier_focusRequester]
    focus_restorer: _t.ClassVar[_Modifier_focusRestorer]
    focus_restorer__androidx_compose_ui_Modifier_androidx_compose_ui_focus_FocusRequester: _t.ClassVar[_Modifier_focusRestorer__androidx_compose_ui_Modifier_androidx_compose_ui_focus_FocusRequester]
    focus_restorer__androidx_compose_ui_Modifier_kotlin_Function0____androidx_compose_ui_focus_FocusRequester: _t.ClassVar[_Modifier_focusRestorer__androidx_compose_ui_Modifier_kotlin_Function0____androidx_compose_ui_focus_FocusRequester]
    focus_target: _t.ClassVar[_Modifier_focusTarget]
    graphics_layer: _t.ClassVar[_Modifier_graphicsLayer]
    graphics_layer__Float_Float_Float_Float_Float_Float_Float_Float_Float_Float_TransformOrigin_Shape_Boolean_RenderEffect_Color_Color_CompositingStrategy_BlendMode_ColorFilter: _t.ClassVar[_Modifier_graphicsLayer__Float_Float_Float_Float_Float_Float_Float_Float_Float_Float_TransformOrigin_Shape_Boolean_RenderEffect_Color_Color_CompositingStrategy_BlendMode_ColorFilter]
    graphics_layer__Unit: _t.ClassVar[_Modifier_graphicsLayer__Unit]
    height: _t.ClassVar[_Modifier_height]
    height_in: _t.ClassVar[_Modifier_heightIn]
    height__Dp: _t.ClassVar[_Modifier_height__Dp]
    height__IntrinsicSize: _t.ClassVar[_Modifier_height__IntrinsicSize]
    ime_padding: _t.ClassVar[_Modifier_imePadding]
    inner_shadow: _t.ClassVar[_Modifier_innerShadow]
    inner_shadow__Shape_Shadow: _t.ClassVar[_Modifier_innerShadow__Shape_Shadow]
    inner_shadow__Shape_Unit: _t.ClassVar[_Modifier_innerShadow__Shape_Unit]
    inspectable: _t.ClassVar[_Modifier_inspectable]
    keep_screen_on: _t.ClassVar[_Modifier_keepScreenOn]
    layout: _t.ClassVar[_Modifier_layout]
    layout_bounds: _t.ClassVar[_Modifier_layoutBounds]
    mandatory_system_gestures_padding: _t.ClassVar[_Modifier_mandatorySystemGesturesPadding]
    minimum_interactive_component_size: _t.ClassVar[_Modifier_minimumInteractiveComponentSize]
    modifier_local_consumer: _t.ClassVar[_Modifier_modifierLocalConsumer]
    modifier_local_provider: _t.ClassVar[_Modifier_modifierLocalProvider]
    mouse_scroll_filter: _t.ClassVar[_Modifier_mouseScrollFilter]
    navigation_bars_padding: _t.ClassVar[_Modifier_navigationBarsPadding]
    nested_scroll: _t.ClassVar[_Modifier_nestedScroll]
    offset: _t.ClassVar[_Modifier_offset]
    offset__Dp_Dp: _t.ClassVar[_Modifier_offset__Dp_Dp]
    offset__IntOffset: _t.ClassVar[_Modifier_offset__IntOffset]
    on_consumed_window_insets_changed: _t.ClassVar[_Modifier_onConsumedWindowInsetsChanged]
    on_first_visible: _t.ClassVar[_Modifier_onFirstVisible]
    on_focus_changed: _t.ClassVar[_Modifier_onFocusChanged]
    on_focus_event: _t.ClassVar[_Modifier_onFocusEvent]
    on_globally_positioned: _t.ClassVar[_Modifier_onGloballyPositioned]
    on_intercept_key_before_soft_keyboard: _t.ClassVar[_Modifier_onInterceptKeyBeforeSoftKeyboard]
    on_key_event: _t.ClassVar[_Modifier_onKeyEvent]
    on_layout_rect_changed: _t.ClassVar[_Modifier_onLayoutRectChanged]
    on_placed: _t.ClassVar[_Modifier_onPlaced]
    on_pointer_event: _t.ClassVar[_Modifier_onPointerEvent]
    on_pre_intercept_key_before_soft_keyboard: _t.ClassVar[_Modifier_onPreInterceptKeyBeforeSoftKeyboard]
    on_pre_rotary_scroll_event: _t.ClassVar[_Modifier_onPreRotaryScrollEvent]
    on_preview_key_event: _t.ClassVar[_Modifier_onPreviewKeyEvent]
    on_rotary_scroll_event: _t.ClassVar[_Modifier_onRotaryScrollEvent]
    on_size_changed: _t.ClassVar[_Modifier_onSizeChanged]
    on_visibility_changed: _t.ClassVar[_Modifier_onVisibilityChanged]
    padding: _t.ClassVar[_Modifier_padding]
    padding_from: _t.ClassVar[_Modifier_paddingFrom]
    padding_from_baseline: _t.ClassVar[_Modifier_paddingFromBaseline]
    padding_from_baseline__Dp_Dp: _t.ClassVar[_Modifier_paddingFromBaseline__Dp_Dp]
    padding_from_baseline__TextUnit_TextUnit: _t.ClassVar[_Modifier_paddingFromBaseline__TextUnit_TextUnit]
    padding_from__AlignmentLine_Dp_Dp: _t.ClassVar[_Modifier_paddingFrom__AlignmentLine_Dp_Dp]
    padding_from__AlignmentLine_TextUnit_TextUnit: _t.ClassVar[_Modifier_paddingFrom__AlignmentLine_TextUnit_TextUnit]
    padding__Dp: _t.ClassVar[_Modifier_padding__Dp]
    padding__Dp_Dp: _t.ClassVar[_Modifier_padding__Dp_Dp]
    padding__Dp_Dp_Dp_Dp: _t.ClassVar[_Modifier_padding__Dp_Dp_Dp_Dp]
    padding__PaddingValues: _t.ClassVar[_Modifier_padding__PaddingValues]
    paint: _t.ClassVar[_Modifier_paint]
    pointer_hover_icon: _t.ClassVar[_Modifier_pointerHoverIcon]
    pointer_input: _t.ClassVar[_Modifier_pointerInput]
    pointer_input__Any_Any_PointerInputEventHandler: _t.ClassVar[_Modifier_pointerInput__Any_Any_PointerInputEventHandler]
    pointer_input__Any_PointerInputEventHandler: _t.ClassVar[_Modifier_pointerInput__Any_PointerInputEventHandler]
    pointer_move_filter: _t.ClassVar[_Modifier_pointerMoveFilter]
    preferred_frame_rate: _t.ClassVar[_Modifier_preferredFrameRate]
    preferred_frame_rate__Float: _t.ClassVar[_Modifier_preferredFrameRate__Float]
    preferred_frame_rate__FrameRateCategory: _t.ClassVar[_Modifier_preferredFrameRate__FrameRateCategory]
    pull_to_refresh: _t.ClassVar[_Modifier_pullToRefresh]
    recalculate_window_insets: _t.ClassVar[_Modifier_recalculateWindowInsets]
    required_height: _t.ClassVar[_Modifier_requiredHeight]
    required_height_in: _t.ClassVar[_Modifier_requiredHeightIn]
    required_height__Dp: _t.ClassVar[_Modifier_requiredHeight__Dp]
    required_height__IntrinsicSize: _t.ClassVar[_Modifier_requiredHeight__IntrinsicSize]
    required_size: _t.ClassVar[_Modifier_requiredSize]
    required_size_in: _t.ClassVar[_Modifier_requiredSizeIn]
    required_size__Dp: _t.ClassVar[_Modifier_requiredSize__Dp]
    required_size__DpSize: _t.ClassVar[_Modifier_requiredSize__DpSize]
    required_size__Dp_Dp: _t.ClassVar[_Modifier_requiredSize__Dp_Dp]
    required_width: _t.ClassVar[_Modifier_requiredWidth]
    required_width_in: _t.ClassVar[_Modifier_requiredWidthIn]
    required_width__Dp: _t.ClassVar[_Modifier_requiredWidth__Dp]
    required_width__IntrinsicSize: _t.ClassVar[_Modifier_requiredWidth__IntrinsicSize]
    rotate: _t.ClassVar[_Modifier_rotate]
    safe_content_padding: _t.ClassVar[_Modifier_safeContentPadding]
    safe_drawing_padding: _t.ClassVar[_Modifier_safeDrawingPadding]
    safe_gestures_padding: _t.ClassVar[_Modifier_safeGesturesPadding]
    scale: _t.ClassVar[_Modifier_scale]
    scale__Float: _t.ClassVar[_Modifier_scale__Float]
    scale__Float_Float: _t.ClassVar[_Modifier_scale__Float_Float]
    semantics: _t.ClassVar[_Modifier_semantics]
    sensitive_content: _t.ClassVar[_Modifier_sensitiveContent]
    shadow: _t.ClassVar[_Modifier_shadow]
    size: _t.ClassVar[_Modifier_size]
    size_in: _t.ClassVar[_Modifier_sizeIn]
    size__Dp: _t.ClassVar[_Modifier_size__Dp]
    size__DpSize: _t.ClassVar[_Modifier_size__DpSize]
    size__Dp_Dp: _t.ClassVar[_Modifier_size__Dp_Dp]
    status_bars_padding: _t.ClassVar[_Modifier_statusBarsPadding]
    stylus_hover_icon: _t.ClassVar[_Modifier_stylusHoverIcon]
    system_bars_padding: _t.ClassVar[_Modifier_systemBarsPadding]
    system_gestures_padding: _t.ClassVar[_Modifier_systemGesturesPadding]
    test_tag: _t.ClassVar[_Modifier_testTag]
    tooling_graphics_layer: _t.ClassVar[_Modifier_toolingGraphicsLayer]
    visible: _t.ClassVar[_Modifier_visible]
    waterfall_padding: _t.ClassVar[_Modifier_waterfallPadding]
    width: _t.ClassVar[_Modifier_width]
    width_in: _t.ClassVar[_Modifier_widthIn]
    width__Dp: _t.ClassVar[_Modifier_width__Dp]
    width__IntrinsicSize: _t.ClassVar[_Modifier_width__IntrinsicSize]
    window_insets_bottom_height: _t.ClassVar[_Modifier_windowInsetsBottomHeight]
    window_insets_end_width: _t.ClassVar[_Modifier_windowInsetsEndWidth]
    window_insets_padding: _t.ClassVar[_Modifier_windowInsetsPadding]
    window_insets_start_width: _t.ClassVar[_Modifier_windowInsetsStartWidth]
    window_insets_top_height: _t.ClassVar[_Modifier_windowInsetsTopHeight]
    wrap_content_height: _t.ClassVar[_Modifier_wrapContentHeight]
    wrap_content_size: _t.ClassVar[_Modifier_wrapContentSize]
    wrap_content_width: _t.ClassVar[_Modifier_wrapContentWidth]
    z_index: _t.ClassVar[_Modifier_zIndex]
    class Element:
        """Kotlin: androidx.compose.ui.Modifier.Element"""
    class Node:
        """Kotlin: androidx.compose.ui.Modifier.Node"""

class MotionDurationScale:
    """Kotlin: androidx.compose.ui.MotionDurationScale"""
    @property
    def key(self) -> _t.Any:
        """Kotlin property: androidx.compose.ui.MotionDurationScale.key (androidx.compose.ui.MotionDurationScale.key: kotlin.coroutines.CoroutineContext.Key)"""
        ...
    @property
    def scale_factor(self) -> float:
        """Kotlin property: androidx.compose.ui.MotionDurationScale.scaleFactor (androidx.compose.ui.MotionDurationScale.scaleFactor: kotlin.Float)"""
        ...

class UiMediaScope:
    """Kotlin: androidx.compose.ui.UiMediaScope"""
    @property
    def has_camera(self) -> bool:
        """Kotlin property: androidx.compose.ui.UiMediaScope.hasCamera (androidx.compose.ui.UiMediaScope.hasCamera: kotlin.Boolean)"""
        ...
    @property
    def has_microphone(self) -> bool:
        """Kotlin property: androidx.compose.ui.UiMediaScope.hasMicrophone (androidx.compose.ui.UiMediaScope.hasMicrophone: kotlin.Boolean)"""
        ...
    @property
    def keyboard_kind(self) -> UiMediaScope.KeyboardKind:
        """Kotlin property: androidx.compose.ui.UiMediaScope.keyboardKind (androidx.compose.ui.UiMediaScope.keyboardKind: androidx.compose.ui.UiMediaScope.KeyboardKind)"""
        ...
    @property
    def pointer_precision(self) -> UiMediaScope.PointerPrecision:
        """Kotlin property: androidx.compose.ui.UiMediaScope.pointerPrecision (androidx.compose.ui.UiMediaScope.pointerPrecision: androidx.compose.ui.UiMediaScope.PointerPrecision)"""
        ...
    @property
    def viewing_distance(self) -> UiMediaScope.ViewingDistance:
        """Kotlin property: androidx.compose.ui.UiMediaScope.viewingDistance (androidx.compose.ui.UiMediaScope.viewingDistance: androidx.compose.ui.UiMediaScope.ViewingDistance)"""
        ...
    @property
    def window_height(self) -> float:
        """Kotlin property: androidx.compose.ui.UiMediaScope.windowHeight (androidx.compose.ui.UiMediaScope.windowHeight: androidx.compose.ui.unit.Dp)"""
        ...
    @property
    def window_posture(self) -> UiMediaScope.Posture:
        """Kotlin property: androidx.compose.ui.UiMediaScope.windowPosture (androidx.compose.ui.UiMediaScope.windowPosture: androidx.compose.ui.UiMediaScope.Posture)"""
        ...
    @property
    def window_width(self) -> float:
        """Kotlin property: androidx.compose.ui.UiMediaScope.windowWidth (androidx.compose.ui.UiMediaScope.windowWidth: androidx.compose.ui.unit.Dp)"""
        ...
    class KeyboardKind:
        """Kotlin: androidx.compose.ui.UiMediaScope.KeyboardKind"""
    class PointerPrecision:
        """Kotlin: androidx.compose.ui.UiMediaScope.PointerPrecision"""
    class Posture:
        """Kotlin: androidx.compose.ui.UiMediaScope.Posture"""
    class ViewingDistance:
        """Kotlin: androidx.compose.ui.UiMediaScope.ViewingDistance"""

def configure_swing_globals_for_compose(override_look_and_feel: bool = ..., use_screen_menu_bar_on_mac_os: bool = ..., use_auto_dpi_on_linux: bool = ...) -> None:
    """Kotlin: androidx.compose.ui.configureSwingGlobalsForCompose(overrideLookAndFeel: kotlin.Boolean, useScreenMenuBarOnMacOs: kotlin.Boolean, useAutoDpiOnLinux: kotlin.Boolean): kotlin.Unit"""
    ...

def derived_media_query(query: _t.Callable[[UiMediaScope], bool]) -> pythonx.compose.runtime.State:
    """Kotlin: androidx.compose.ui.derivedMediaQuery(query: kotlin.Function1): androidx.compose.runtime.State"""
    ...

def keep_screen_on(receiver: Modifier, /) -> Modifier:
    """Kotlin: androidx.compose.ui.Modifier.keepScreenOn(): androidx.compose.ui.Modifier"""
    ...

def materialize(receiver: pythonx.compose.runtime.Composer, /, modifier: Modifier) -> Modifier:
    """Kotlin: androidx.compose.runtime.Composer.materialize(modifier: androidx.compose.ui.Modifier): androidx.compose.ui.Modifier"""
    ...

def media_query__Boolean(query: _t.Callable[[UiMediaScope], bool]) -> bool:
    """Kotlin: androidx.compose.ui.mediaQuery(query: kotlin.Function1): kotlin.Boolean"""
    ...

def media_query__CompositionLocalAccessorScope_Boolean(receiver: pythonx.compose.runtime.CompositionLocalAccessorScope, /, query: _t.Callable[[UiMediaScope], bool]) -> bool:
    """Kotlin: androidx.compose.runtime.CompositionLocalAccessorScope.mediaQuery(query: kotlin.Function1): kotlin.Boolean"""
    ...

def media_query__CompositionLocalConsumerModifierNode_Boolean(receiver: _t.Any, /, query: _t.Callable[[UiMediaScope], bool]) -> bool:
    """Kotlin: androidx.compose.ui.node.CompositionLocalConsumerModifierNode.mediaQuery(query: kotlin.Function1): kotlin.Boolean"""
    ...

def preferred_frame_rate__Float(receiver: Modifier, /, frame_rate: float) -> Modifier:
    """Kotlin: androidx.compose.ui.Modifier.preferredFrameRate(frameRate: kotlin.Float): androidx.compose.ui.Modifier"""
    ...

def preferred_frame_rate__FrameRateCategory(receiver: Modifier, /, frame_rate_category: _t.Any) -> Modifier:
    """Kotlin: androidx.compose.ui.Modifier.preferredFrameRate(frameRateCategory: androidx.compose.ui.FrameRateCategory): androidx.compose.ui.Modifier"""
    ...

def sensitive_content(receiver: Modifier, /, is_content_sensitive: bool = ...) -> Modifier:
    """Kotlin: androidx.compose.ui.Modifier.sensitiveContent(isContentSensitive: kotlin.Boolean): androidx.compose.ui.Modifier"""
    ...

def use(receiver: ImageComposeScene, /, block: _t.Callable[[ImageComposeScene], _t.Any | None]) -> _t.Any | None:
    """Kotlin: androidx.compose.ui.ImageComposeScene.use(block: kotlin.Function1): kotlin.Any"""
    ...

def z_index(receiver: Modifier, /, z_index: float) -> Modifier:
    """Kotlin: androidx.compose.ui.Modifier.zIndex(zIndex: kotlin.Float): androidx.compose.ui.Modifier"""
    ...

@_t.overload
def media_query(query: _t.Callable[[UiMediaScope], bool]) -> bool: ...
@_t.overload
def media_query(receiver: pythonx.compose.runtime.CompositionLocalAccessorScope, /, query: _t.Callable[[UiMediaScope], bool]) -> bool: ...  # type: ignore[overload-cannot-match]
@_t.overload
def media_query(receiver: _t.Any, /, query: _t.Callable[[UiMediaScope], bool]) -> bool: ...  # type: ignore[overload-cannot-match]

@_t.overload
def preferred_frame_rate(receiver: Modifier, /, frame_rate: float) -> Modifier: ...
@_t.overload
def preferred_frame_rate(receiver: Modifier, /, frame_rate_category: _t.Any) -> Modifier: ...  # type: ignore[overload-cannot-match]

class AbsoluteAlignment:
    """Kotlin: androidx.compose.ui.AbsoluteAlignment"""
    BottomLeft: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.AbsoluteAlignment.BottomLeft(): androidx.compose.ui.Alignment"""
    BottomRight: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.AbsoluteAlignment.BottomRight(): androidx.compose.ui.Alignment"""
    CenterLeft: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.AbsoluteAlignment.CenterLeft(): androidx.compose.ui.Alignment"""
    CenterRight: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.AbsoluteAlignment.CenterRight(): androidx.compose.ui.Alignment"""
    Left: _t.ClassVar[Alignment.Horizontal]
    """Kotlin: androidx.compose.ui.AbsoluteAlignment.Left(): androidx.compose.ui.Alignment.Horizontal"""
    Right: _t.ClassVar[Alignment.Horizontal]
    """Kotlin: androidx.compose.ui.AbsoluteAlignment.Right(): androidx.compose.ui.Alignment.Horizontal"""
    TopLeft: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.AbsoluteAlignment.TopLeft(): androidx.compose.ui.Alignment"""
    TopRight: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.AbsoluteAlignment.TopRight(): androidx.compose.ui.Alignment"""

class Alignment:
    """Kotlin: androidx.compose.ui.Alignment"""
    class Horizontal:
        """Kotlin: androidx.compose.ui.Alignment.Horizontal"""
        CenterHorizontally: _t.ClassVar[Alignment.Horizontal]
        End: _t.ClassVar[Alignment.Horizontal]
        Start: _t.ClassVar[Alignment.Horizontal]
    class Vertical:
        """Kotlin: androidx.compose.ui.Alignment.Vertical"""
        Bottom: _t.ClassVar[Alignment.Vertical]
        CenterVertically: _t.ClassVar[Alignment.Vertical]
        Top: _t.ClassVar[Alignment.Vertical]
    Bottom: _t.ClassVar[Alignment.Vertical]
    """Kotlin: androidx.compose.ui.Alignment.Bottom(): androidx.compose.ui.Alignment.Vertical"""
    BottomCenter: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.Alignment.BottomCenter(): androidx.compose.ui.Alignment"""
    BottomEnd: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.Alignment.BottomEnd(): androidx.compose.ui.Alignment"""
    BottomStart: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.Alignment.BottomStart(): androidx.compose.ui.Alignment"""
    Center: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.Alignment.Center(): androidx.compose.ui.Alignment"""
    CenterEnd: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.Alignment.CenterEnd(): androidx.compose.ui.Alignment"""
    CenterHorizontally: _t.ClassVar[Alignment.Horizontal]
    """Kotlin: androidx.compose.ui.Alignment.CenterHorizontally(): androidx.compose.ui.Alignment.Horizontal"""
    CenterStart: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.Alignment.CenterStart(): androidx.compose.ui.Alignment"""
    CenterVertically: _t.ClassVar[Alignment.Vertical]
    """Kotlin: androidx.compose.ui.Alignment.CenterVertically(): androidx.compose.ui.Alignment.Vertical"""
    End: _t.ClassVar[Alignment.Horizontal]
    """Kotlin: androidx.compose.ui.Alignment.End(): androidx.compose.ui.Alignment.Horizontal"""
    Start: _t.ClassVar[Alignment.Horizontal]
    """Kotlin: androidx.compose.ui.Alignment.Start(): androidx.compose.ui.Alignment.Horizontal"""
    Top: _t.ClassVar[Alignment.Vertical]
    """Kotlin: androidx.compose.ui.Alignment.Top(): androidx.compose.ui.Alignment.Vertical"""
    TopCenter: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.Alignment.TopCenter(): androidx.compose.ui.Alignment"""
    TopEnd: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.Alignment.TopEnd(): androidx.compose.ui.Alignment"""
    TopStart: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.Alignment.TopStart(): androidx.compose.ui.Alignment"""

class ComposeUiFlags:
    """Kotlin: androidx.compose.ui.ComposeUiFlags"""
    is_accessibility_should_include_offscreen_children_enabled: _t.ClassVar[bool]
    """Kotlin: androidx.compose.ui.ComposeUiFlags.isAccessibilityShouldIncludeOffscreenChildrenEnabled(): kotlin.Boolean"""
    is_bypass_unfocusable_compose_view_enabled: _t.ClassVar[bool]
    """Kotlin: androidx.compose.ui.ComposeUiFlags.isBypassUnfocusableComposeViewEnabled(): kotlin.Boolean"""
    is_focus_restoration_enabled: _t.ClassVar[bool]
    """Kotlin: androidx.compose.ui.ComposeUiFlags.isFocusRestorationEnabled(): kotlin.Boolean"""
    is_graphics_layer_shape_semantics_enabled: _t.ClassVar[bool]
    """Kotlin: androidx.compose.ui.ComposeUiFlags.isGraphicsLayerShapeSemanticsEnabled(): kotlin.Boolean"""
    is_indirect_pointer_navigation_gesture_detector_enabled: _t.ClassVar[bool]
    """Kotlin: androidx.compose.ui.ComposeUiFlags.isIndirectPointerNavigationGestureDetectorEnabled(): kotlin.Boolean"""
    is_initial_focus_on_focusable_available: _t.ClassVar[bool]
    """Kotlin: androidx.compose.ui.ComposeUiFlags.isInitialFocusOnFocusableAvailable(): kotlin.Boolean"""
    is_media_query_integration_enabled: _t.ClassVar[bool]
    """Kotlin: androidx.compose.ui.ComposeUiFlags.isMediaQueryIntegrationEnabled(): kotlin.Boolean"""
    is_optimized_focus_event_dispatch_enabled: _t.ClassVar[bool]
    """Kotlin: androidx.compose.ui.ComposeUiFlags.isOptimizedFocusEventDispatchEnabled(): kotlin.Boolean"""
    is_skip_non_important_semantics_nodes_hit_test_enabled: _t.ClassVar[bool]
    """Kotlin: androidx.compose.ui.ComposeUiFlags.isSkipNonImportantSemanticsNodesHitTestEnabled(): kotlin.Boolean"""
    is_trackpad_gesture_handling_enabled: _t.ClassVar[bool]
    """Kotlin: androidx.compose.ui.ComposeUiFlags.isTrackpadGestureHandlingEnabled(): kotlin.Boolean"""
    is_traversable_delegates_fix_enabled: _t.ClassVar[bool]
    """Kotlin: androidx.compose.ui.ComposeUiFlags.isTraversableDelegatesFixEnabled(): kotlin.Boolean"""
    is_view_focus_fix_enabled: _t.ClassVar[bool]
    """Kotlin: androidx.compose.ui.ComposeUiFlags.isViewFocusFixEnabled(): kotlin.Boolean"""

class FrameRateCategory:
    """Kotlin: androidx.compose.ui.FrameRateCategory"""
    Default: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.FrameRateCategory.Default(): androidx.compose.ui.FrameRateCategory"""
    High: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.FrameRateCategory.High(): androidx.compose.ui.FrameRateCategory"""
    Normal: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.FrameRateCategory.Normal(): androidx.compose.ui.FrameRateCategory"""
