# GENERATED by pythonx/_build/gen_stubs.py from python-multiplatform's Kotlin-named stubs (artifact kotlin-stubs, workflow run 37103737430, commit a5028618, Compose 1.11.1). Do not edit.
import typing as _t
import pythonx.compose.material3
import pythonx.compose.ui
import pythonx.compose.ui.unit

class _RowScope_NavigationBarItem(_t.Protocol):
    def __call__(self, selected: bool, on_click: _t.Callable[[], None], icon: _t.Callable[[], None], modifier: pythonx.compose.ui.Modifier = ..., enabled: bool = ..., label: _t.Callable[[], None] | None = ..., always_show_label: bool = ..., colors: pythonx.compose.material3.NavigationBarItemColors = ..., interaction_source: _t.Any | None = ...) -> None: ...

class BoxScope:
    """Kotlin: androidx.compose.foundation.layout.BoxScope"""

class BoxWithConstraintsScope:
    """Kotlin: androidx.compose.foundation.layout.BoxWithConstraintsScope"""
    @property
    def constraints(self) -> _t.Any:
        """Kotlin property: androidx.compose.foundation.layout.BoxWithConstraintsScope.constraints (androidx.compose.foundation.layout.BoxWithConstraintsScope.constraints: androidx.compose.ui.unit.Constraints)"""
        ...
    @property
    def max_height(self) -> float:
        """Kotlin property: androidx.compose.foundation.layout.BoxWithConstraintsScope.maxHeight (androidx.compose.foundation.layout.BoxWithConstraintsScope.maxHeight: androidx.compose.ui.unit.Dp)"""
        ...
    @property
    def max_width(self) -> float:
        """Kotlin property: androidx.compose.foundation.layout.BoxWithConstraintsScope.maxWidth (androidx.compose.foundation.layout.BoxWithConstraintsScope.maxWidth: androidx.compose.ui.unit.Dp)"""
        ...
    @property
    def min_height(self) -> float:
        """Kotlin property: androidx.compose.foundation.layout.BoxWithConstraintsScope.minHeight (androidx.compose.foundation.layout.BoxWithConstraintsScope.minHeight: androidx.compose.ui.unit.Dp)"""
        ...
    @property
    def min_width(self) -> float:
        """Kotlin property: androidx.compose.foundation.layout.BoxWithConstraintsScope.minWidth (androidx.compose.foundation.layout.BoxWithConstraintsScope.minWidth: androidx.compose.ui.unit.Dp)"""
        ...

class ColumnScope:
    """Kotlin: androidx.compose.foundation.layout.ColumnScope"""

class ContextualFlowColumnScope:
    """Kotlin: androidx.compose.foundation.layout.ContextualFlowColumnScope"""
    @property
    def index_in_line(self) -> int:
        """Kotlin property: androidx.compose.foundation.layout.ContextualFlowColumnScope.indexInLine (androidx.compose.foundation.layout.ContextualFlowColumnScope.indexInLine: kotlin.Int)"""
        ...
    @property
    def line_index(self) -> int:
        """Kotlin property: androidx.compose.foundation.layout.ContextualFlowColumnScope.lineIndex (androidx.compose.foundation.layout.ContextualFlowColumnScope.lineIndex: kotlin.Int)"""
        ...
    @property
    def max_height_in_line(self) -> float:
        """Kotlin property: androidx.compose.foundation.layout.ContextualFlowColumnScope.maxHeightInLine (androidx.compose.foundation.layout.ContextualFlowColumnScope.maxHeightInLine: androidx.compose.ui.unit.Dp)"""
        ...
    @property
    def max_width(self) -> float:
        """Kotlin property: androidx.compose.foundation.layout.ContextualFlowColumnScope.maxWidth (androidx.compose.foundation.layout.ContextualFlowColumnScope.maxWidth: androidx.compose.ui.unit.Dp)"""
        ...

class ContextualFlowRowScope:
    """Kotlin: androidx.compose.foundation.layout.ContextualFlowRowScope"""
    @property
    def index_in_line(self) -> int:
        """Kotlin property: androidx.compose.foundation.layout.ContextualFlowRowScope.indexInLine (androidx.compose.foundation.layout.ContextualFlowRowScope.indexInLine: kotlin.Int)"""
        ...
    @property
    def line_index(self) -> int:
        """Kotlin property: androidx.compose.foundation.layout.ContextualFlowRowScope.lineIndex (androidx.compose.foundation.layout.ContextualFlowRowScope.lineIndex: kotlin.Int)"""
        ...
    @property
    def max_height(self) -> float:
        """Kotlin property: androidx.compose.foundation.layout.ContextualFlowRowScope.maxHeight (androidx.compose.foundation.layout.ContextualFlowRowScope.maxHeight: androidx.compose.ui.unit.Dp)"""
        ...
    @property
    def max_width_in_line(self) -> float:
        """Kotlin property: androidx.compose.foundation.layout.ContextualFlowRowScope.maxWidthInLine (androidx.compose.foundation.layout.ContextualFlowRowScope.maxWidthInLine: androidx.compose.ui.unit.Dp)"""
        ...

class FlexBoxConfig:
    """Kotlin: androidx.compose.foundation.layout.FlexBoxConfig"""

class FlexBoxConfigScope:
    """Kotlin: androidx.compose.foundation.layout.FlexBoxConfigScope"""
    @property
    def constraints(self) -> _t.Any:
        """Kotlin property: androidx.compose.foundation.layout.FlexBoxConfigScope.constraints (androidx.compose.foundation.layout.FlexBoxConfigScope.constraints: androidx.compose.ui.unit.Constraints)"""
        ...

class FlexBoxScope:
    """Kotlin: androidx.compose.foundation.layout.FlexBoxScope"""

class FlexConfigScope:
    """Kotlin: androidx.compose.foundation.layout.FlexConfigScope"""
    @property
    def flex_box_cross_axis_max(self) -> int:
        """Kotlin property: androidx.compose.foundation.layout.FlexConfigScope.flexBoxCrossAxisMax (androidx.compose.foundation.layout.FlexConfigScope.flexBoxCrossAxisMax: kotlin.Int)"""
        ...
    @property
    def flex_box_cross_axis_min(self) -> int:
        """Kotlin property: androidx.compose.foundation.layout.FlexConfigScope.flexBoxCrossAxisMin (androidx.compose.foundation.layout.FlexConfigScope.flexBoxCrossAxisMin: kotlin.Int)"""
        ...
    @property
    def flex_box_main_axis_max(self) -> int:
        """Kotlin property: androidx.compose.foundation.layout.FlexConfigScope.flexBoxMainAxisMax (androidx.compose.foundation.layout.FlexConfigScope.flexBoxMainAxisMax: kotlin.Int)"""
        ...
    @property
    def flex_box_main_axis_min(self) -> int:
        """Kotlin property: androidx.compose.foundation.layout.FlexConfigScope.flexBoxMainAxisMin (androidx.compose.foundation.layout.FlexConfigScope.flexBoxMainAxisMin: kotlin.Int)"""
        ...

class FlowColumnOverflowScope:
    """Kotlin: androidx.compose.foundation.layout.FlowColumnOverflowScope"""
    @property
    def shown_item_count(self) -> int:
        """Kotlin property: androidx.compose.foundation.layout.FlowColumnOverflowScope.shownItemCount (androidx.compose.foundation.layout.FlowColumnOverflowScope.shownItemCount: kotlin.Int)"""
        ...
    @property
    def total_item_count(self) -> int:
        """Kotlin property: androidx.compose.foundation.layout.FlowColumnOverflowScope.totalItemCount (androidx.compose.foundation.layout.FlowColumnOverflowScope.totalItemCount: kotlin.Int)"""
        ...

class FlowColumnScope:
    """Kotlin: androidx.compose.foundation.layout.FlowColumnScope"""

class FlowRowOverflowScope:
    """Kotlin: androidx.compose.foundation.layout.FlowRowOverflowScope"""
    @property
    def shown_item_count(self) -> int:
        """Kotlin property: androidx.compose.foundation.layout.FlowRowOverflowScope.shownItemCount (androidx.compose.foundation.layout.FlowRowOverflowScope.shownItemCount: kotlin.Int)"""
        ...
    @property
    def total_item_count(self) -> int:
        """Kotlin property: androidx.compose.foundation.layout.FlowRowOverflowScope.totalItemCount (androidx.compose.foundation.layout.FlowRowOverflowScope.totalItemCount: kotlin.Int)"""
        ...

class FlowRowScope:
    """Kotlin: androidx.compose.foundation.layout.FlowRowScope"""

class GridConfigurationScope:
    """Kotlin: androidx.compose.foundation.layout.GridConfigurationScope"""
    @property
    def constraints(self) -> _t.Any:
        """Kotlin property: androidx.compose.foundation.layout.GridConfigurationScope.constraints (androidx.compose.foundation.layout.GridConfigurationScope.constraints: androidx.compose.ui.unit.Constraints)"""
        ...
    @property
    def flow(self) -> _t.Any:
        """Kotlin property: androidx.compose.foundation.layout.GridConfigurationScope.flow (androidx.compose.foundation.layout.GridConfigurationScope.flow: androidx.compose.foundation.layout.GridFlow)"""
        ...
    @flow.setter
    def flow(self, value: _t.Any) -> None:
        """Kotlin property: androidx.compose.foundation.layout.GridConfigurationScope.flow="""
        ...

class IntrinsicSize:
    """Kotlin: androidx.compose.foundation.layout.IntrinsicSize"""

class MutableWindowInsets:
    """Kotlin: androidx.compose.foundation.layout.MutableWindowInsets"""
    def __init__(self, initialInsets: _t.Any = ...) -> None:
        """Kotlin constructor: androidx.compose.foundation.layout.MutableWindowInsets (androidx.compose.foundation.layout.MutableWindowInsets(initialInsets: androidx.compose.foundation.layout.WindowInsets): androidx.compose.foundation.layout.MutableWindowInsets)"""
        ...
    @property
    def insets(self) -> _t.Any:
        """Kotlin property: androidx.compose.foundation.layout.MutableWindowInsets.insets (androidx.compose.foundation.layout.MutableWindowInsets.insets: androidx.compose.foundation.layout.WindowInsets)"""
        ...
    @insets.setter
    def insets(self, value: _t.Any) -> None:
        """Kotlin property: androidx.compose.foundation.layout.MutableWindowInsets.insets="""
        ...

class RowScope:
    """Kotlin: androidx.compose.foundation.layout.RowScope"""
    NavigationBarItem: _t.ClassVar[_RowScope_NavigationBarItem]

def BoxWithConstraints(modifier: pythonx.compose.ui.Modifier = ..., content_alignment: _t.Any = ..., propagate_min_constraints: bool = ..., *, content: _t.Callable[[BoxWithConstraintsScope], None]) -> None:
    """Kotlin: androidx.compose.foundation.layout.BoxWithConstraints(modifier: androidx.compose.ui.Modifier, contentAlignment: androidx.compose.ui.Alignment, propagateMinConstraints: kotlin.Boolean, content: kotlin.Function1): kotlin.Unit"""
    ...

def Box__Modifier(modifier: pythonx.compose.ui.Modifier) -> None:
    """Kotlin: androidx.compose.foundation.layout.Box(modifier: androidx.compose.ui.Modifier): kotlin.Unit"""
    ...

def Box__Modifier_Alignment_Boolean_Unit(modifier: pythonx.compose.ui.Modifier = ..., content_alignment: _t.Any = ..., propagate_min_constraints: bool = ..., *, content: _t.Callable[[BoxScope], None]) -> None:
    """Kotlin: androidx.compose.foundation.layout.Box(modifier: androidx.compose.ui.Modifier, contentAlignment: androidx.compose.ui.Alignment, propagateMinConstraints: kotlin.Boolean, content: kotlin.Function1): kotlin.Unit"""
    ...

def Column(modifier: pythonx.compose.ui.Modifier = ..., vertical_arrangement: Arrangement.Vertical = ..., horizontal_alignment: pythonx.compose.ui.Alignment.Horizontal = ..., *, content: _t.Callable[[ColumnScope], None]) -> None:
    """Kotlin: androidx.compose.foundation.layout.Column(modifier: androidx.compose.ui.Modifier, verticalArrangement: androidx.compose.foundation.layout.Arrangement.Vertical, horizontalAlignment: androidx.compose.ui.Alignment.Horizontal, content: kotlin.Function1): kotlin.Unit"""
    ...

def ContextualFlowColumn(item_count: int, modifier: pythonx.compose.ui.Modifier = ..., vertical_arrangement: Arrangement.Vertical = ..., horizontal_arrangement: Arrangement.Horizontal = ..., item_horizontal_alignment: pythonx.compose.ui.Alignment.Horizontal = ..., max_items_in_each_column: int = ..., max_lines: int = ..., overflow: _t.Any = ..., *, content: _t.Callable[[ContextualFlowColumnScope, int], None]) -> None:
    """Kotlin: androidx.compose.foundation.layout.ContextualFlowColumn(itemCount: kotlin.Int, modifier: androidx.compose.ui.Modifier, verticalArrangement: androidx.compose.foundation.layout.Arrangement.Vertical, horizontalArrangement: androidx.compose.foundation.layout.Arrangement.Horizontal, itemHorizontalAlignment: androidx.compose.ui.Alignment.Horizontal, maxItemsInEachColumn: kotlin.Int, maxLines: kotlin.Int, overflow: androidx.compose.foundation.layout.ContextualFlowColumnOverflow, content: kotlin.Function2): kotlin.Unit"""
    ...

def ContextualFlowRow(item_count: int, modifier: pythonx.compose.ui.Modifier = ..., horizontal_arrangement: Arrangement.Horizontal = ..., vertical_arrangement: Arrangement.Vertical = ..., item_vertical_alignment: pythonx.compose.ui.Alignment.Vertical = ..., max_items_in_each_row: int = ..., max_lines: int = ..., overflow: _t.Any = ..., *, content: _t.Callable[[ContextualFlowRowScope, int], None]) -> None:
    """Kotlin: androidx.compose.foundation.layout.ContextualFlowRow(itemCount: kotlin.Int, modifier: androidx.compose.ui.Modifier, horizontalArrangement: androidx.compose.foundation.layout.Arrangement.Horizontal, verticalArrangement: androidx.compose.foundation.layout.Arrangement.Vertical, itemVerticalAlignment: androidx.compose.ui.Alignment.Vertical, maxItemsInEachRow: kotlin.Int, maxLines: kotlin.Int, overflow: androidx.compose.foundation.layout.ContextualFlowRowOverflow, content: kotlin.Function2): kotlin.Unit"""
    ...

def FlexBox(modifier: pythonx.compose.ui.Modifier = ..., config: FlexBoxConfig = ..., *, content: _t.Callable[[FlexBoxScope], None]) -> None:
    """Kotlin: androidx.compose.foundation.layout.FlexBox(modifier: androidx.compose.ui.Modifier, config: androidx.compose.foundation.layout.FlexBoxConfig, content: kotlin.Function1): kotlin.Unit"""
    ...

def FlowColumn__Modifier_Vertical_Horizontal_Horizontal_Int_Int_FlowColumnOverflow_Unit(modifier: pythonx.compose.ui.Modifier = ..., vertical_arrangement: Arrangement.Vertical = ..., horizontal_arrangement: Arrangement.Horizontal = ..., item_horizontal_alignment: pythonx.compose.ui.Alignment.Horizontal = ..., max_items_in_each_column: int = ..., max_lines: int = ..., overflow: _t.Any = ..., *, content: _t.Callable[[FlowColumnScope], None]) -> None:
    """Kotlin: androidx.compose.foundation.layout.FlowColumn(modifier: androidx.compose.ui.Modifier, verticalArrangement: androidx.compose.foundation.layout.Arrangement.Vertical, horizontalArrangement: androidx.compose.foundation.layout.Arrangement.Horizontal, itemHorizontalAlignment: androidx.compose.ui.Alignment.Horizontal, maxItemsInEachColumn: kotlin.Int, maxLines: kotlin.Int, overflow: androidx.compose.foundation.layout.FlowColumnOverflow, content: kotlin.Function1): kotlin.Unit"""
    ...

def FlowColumn__Modifier_Vertical_Horizontal_Horizontal_Int_Int_Unit(modifier: pythonx.compose.ui.Modifier = ..., vertical_arrangement: Arrangement.Vertical = ..., horizontal_arrangement: Arrangement.Horizontal = ..., item_horizontal_alignment: pythonx.compose.ui.Alignment.Horizontal = ..., max_items_in_each_column: int = ..., max_lines: int = ..., *, content: _t.Callable[[FlowColumnScope], None]) -> None:
    """Kotlin: androidx.compose.foundation.layout.FlowColumn(modifier: androidx.compose.ui.Modifier, verticalArrangement: androidx.compose.foundation.layout.Arrangement.Vertical, horizontalArrangement: androidx.compose.foundation.layout.Arrangement.Horizontal, itemHorizontalAlignment: androidx.compose.ui.Alignment.Horizontal, maxItemsInEachColumn: kotlin.Int, maxLines: kotlin.Int, content: kotlin.Function1): kotlin.Unit"""
    ...

def FlowRow__Modifier_Horizontal_Vertical_Vertical_Int_Int_FlowRowOverflow_Unit(modifier: pythonx.compose.ui.Modifier = ..., horizontal_arrangement: Arrangement.Horizontal = ..., vertical_arrangement: Arrangement.Vertical = ..., item_vertical_alignment: pythonx.compose.ui.Alignment.Vertical = ..., max_items_in_each_row: int = ..., max_lines: int = ..., overflow: _t.Any = ..., *, content: _t.Callable[[FlowRowScope], None]) -> None:
    """Kotlin: androidx.compose.foundation.layout.FlowRow(modifier: androidx.compose.ui.Modifier, horizontalArrangement: androidx.compose.foundation.layout.Arrangement.Horizontal, verticalArrangement: androidx.compose.foundation.layout.Arrangement.Vertical, itemVerticalAlignment: androidx.compose.ui.Alignment.Vertical, maxItemsInEachRow: kotlin.Int, maxLines: kotlin.Int, overflow: androidx.compose.foundation.layout.FlowRowOverflow, content: kotlin.Function1): kotlin.Unit"""
    ...

def FlowRow__Modifier_Horizontal_Vertical_Vertical_Int_Int_Unit(modifier: pythonx.compose.ui.Modifier = ..., horizontal_arrangement: Arrangement.Horizontal = ..., vertical_arrangement: Arrangement.Vertical = ..., item_vertical_alignment: pythonx.compose.ui.Alignment.Vertical = ..., max_items_in_each_row: int = ..., max_lines: int = ..., *, content: _t.Callable[[FlowRowScope], None]) -> None:
    """Kotlin: androidx.compose.foundation.layout.FlowRow(modifier: androidx.compose.ui.Modifier, horizontalArrangement: androidx.compose.foundation.layout.Arrangement.Horizontal, verticalArrangement: androidx.compose.foundation.layout.Arrangement.Vertical, itemVerticalAlignment: androidx.compose.ui.Alignment.Vertical, maxItemsInEachRow: kotlin.Int, maxLines: kotlin.Int, content: kotlin.Function1): kotlin.Unit"""
    ...

def Fr(value: float) -> float:
    """Kotlin: androidx.compose.foundation.layout.Fr(value: kotlin.Float): androidx.compose.foundation.layout.Fr"""
    ...

def Grid(config: _t.Callable[[GridConfigurationScope], None], modifier: pythonx.compose.ui.Modifier = ..., *, content: _t.Callable[[_t.Any], None]) -> None:
    """Kotlin: androidx.compose.foundation.layout.Grid(config: kotlin.Function1, modifier: androidx.compose.ui.Modifier, content: kotlin.Function1): kotlin.Unit"""
    ...

def PaddingValues__Dp(all: float) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.PaddingValues(all: androidx.compose.ui.unit.Dp): androidx.compose.foundation.layout.PaddingValues"""
    ...

def PaddingValues__Dp_Dp(horizontal: float = ..., vertical: float = ...) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.PaddingValues(horizontal: androidx.compose.ui.unit.Dp, vertical: androidx.compose.ui.unit.Dp): androidx.compose.foundation.layout.PaddingValues"""
    ...

def PaddingValues__Dp_Dp_Dp_Dp(start: float = ..., top: float = ..., end: float = ..., bottom: float = ...) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.PaddingValues(start: androidx.compose.ui.unit.Dp, top: androidx.compose.ui.unit.Dp, end: androidx.compose.ui.unit.Dp, bottom: androidx.compose.ui.unit.Dp): androidx.compose.foundation.layout.PaddingValues"""
    ...

def Row(modifier: pythonx.compose.ui.Modifier = ..., horizontal_arrangement: Arrangement.Horizontal = ..., vertical_alignment: pythonx.compose.ui.Alignment.Vertical = ..., *, content: _t.Callable[[RowScope], None]) -> None:
    """Kotlin: androidx.compose.foundation.layout.Row(modifier: androidx.compose.ui.Modifier, horizontalArrangement: androidx.compose.foundation.layout.Arrangement.Horizontal, verticalAlignment: androidx.compose.ui.Alignment.Vertical, content: kotlin.Function1): kotlin.Unit"""
    ...

def Spacer(modifier: pythonx.compose.ui.Modifier) -> None:
    """Kotlin: androidx.compose.foundation.layout.Spacer(modifier: androidx.compose.ui.Modifier): kotlin.Unit"""
    ...

def WindowInsets__0() -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.WindowInsets(): androidx.compose.foundation.layout.WindowInsets"""
    ...

def WindowInsets__Dp_Dp_Dp_Dp(left: float = ..., top: float = ..., right: float = ..., bottom: float = ...) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.WindowInsets(left: androidx.compose.ui.unit.Dp, top: androidx.compose.ui.unit.Dp, right: androidx.compose.ui.unit.Dp, bottom: androidx.compose.ui.unit.Dp): androidx.compose.foundation.layout.WindowInsets"""
    ...

def WindowInsets__Int_Int_Int_Int(left: int = ..., top: int = ..., right: int = ..., bottom: int = ...) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.WindowInsets(left: kotlin.Int, top: kotlin.Int, right: kotlin.Int, bottom: kotlin.Int): androidx.compose.foundation.layout.WindowInsets"""
    ...

def absolute_offset__Dp_Dp(receiver: pythonx.compose.ui.Modifier, /, x: float = ..., y: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.absoluteOffset(x: androidx.compose.ui.unit.Dp, y: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def absolute_offset__IntOffset(receiver: pythonx.compose.ui.Modifier, /, offset: _t.Callable[[_t.Any], _t.Any]) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.absoluteOffset(offset: kotlin.Function1): androidx.compose.ui.Modifier"""
    ...

def absolute_padding(receiver: pythonx.compose.ui.Modifier, /, left: float = ..., top: float = ..., right: float = ..., bottom: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.absolutePadding(left: androidx.compose.ui.unit.Dp, top: androidx.compose.ui.unit.Dp, right: androidx.compose.ui.unit.Dp, bottom: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def add(receiver: _t.Any, /, insets: _t.Any) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.WindowInsets.add(insets: androidx.compose.foundation.layout.WindowInsets): androidx.compose.foundation.layout.WindowInsets"""
    ...

def as_padding_values__0(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.WindowInsets.asPaddingValues(): androidx.compose.foundation.layout.PaddingValues"""
    ...

def as_padding_values__Density(receiver: _t.Any, /, density: _t.Any) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.WindowInsets.asPaddingValues(density: androidx.compose.ui.unit.Density): androidx.compose.foundation.layout.PaddingValues"""
    ...

def aspect_ratio(receiver: pythonx.compose.ui.Modifier, /, ratio: float, match_height_constraints_first: bool = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.aspectRatio(ratio: kotlin.Float, matchHeightConstraintsFirst: kotlin.Boolean): androidx.compose.ui.Modifier"""
    ...

def calculate_end_padding(receiver: _t.Any, /, layout_direction: pythonx.compose.ui.unit.LayoutDirection) -> float:
    """Kotlin: androidx.compose.foundation.layout.PaddingValues.calculateEndPadding(layoutDirection: androidx.compose.ui.unit.LayoutDirection): androidx.compose.ui.unit.Dp"""
    ...

def calculate_start_padding(receiver: _t.Any, /, layout_direction: pythonx.compose.ui.unit.LayoutDirection) -> float:
    """Kotlin: androidx.compose.foundation.layout.PaddingValues.calculateStartPadding(layoutDirection: androidx.compose.ui.unit.LayoutDirection): androidx.compose.ui.unit.Dp"""
    ...

def caption_bar_padding(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.captionBarPadding(): androidx.compose.ui.Modifier"""
    ...

def consume_window_insets__PaddingValues(receiver: pythonx.compose.ui.Modifier, /, padding_values: _t.Any) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.consumeWindowInsets(paddingValues: androidx.compose.foundation.layout.PaddingValues): androidx.compose.ui.Modifier"""
    ...

def consume_window_insets__WindowInsets(receiver: pythonx.compose.ui.Modifier, /, insets: _t.Any) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.consumeWindowInsets(insets: androidx.compose.foundation.layout.WindowInsets): androidx.compose.ui.Modifier"""
    ...

def default_min_size(receiver: pythonx.compose.ui.Modifier, /, min_width: float = ..., min_height: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.defaultMinSize(minWidth: androidx.compose.ui.unit.Dp, minHeight: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def display_cutout_padding(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.displayCutoutPadding(): androidx.compose.ui.Modifier"""
    ...

def exclude(receiver: _t.Any, /, insets: _t.Any) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.WindowInsets.exclude(insets: androidx.compose.foundation.layout.WindowInsets): androidx.compose.foundation.layout.WindowInsets"""
    ...

def fill_max_height(receiver: pythonx.compose.ui.Modifier, /, fraction: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.fillMaxHeight(fraction: kotlin.Float): androidx.compose.ui.Modifier"""
    ...

def fill_max_size(receiver: pythonx.compose.ui.Modifier, /, fraction: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.fillMaxSize(fraction: kotlin.Float): androidx.compose.ui.Modifier"""
    ...

def fill_max_width(receiver: pythonx.compose.ui.Modifier, /, fraction: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.fillMaxWidth(fraction: kotlin.Float): androidx.compose.ui.Modifier"""
    ...

def fit_inside(receiver: pythonx.compose.ui.Modifier, /, rulers: _t.Any) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.fitInside(rulers: androidx.compose.ui.layout.RectRulers): androidx.compose.ui.Modifier"""
    ...

def fit_outside(receiver: pythonx.compose.ui.Modifier, /, rulers: _t.Any) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.fitOutside(rulers: androidx.compose.ui.layout.RectRulers): androidx.compose.ui.Modifier"""
    ...

def height_in(receiver: pythonx.compose.ui.Modifier, /, min: float = ..., max: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.heightIn(min: androidx.compose.ui.unit.Dp, max: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def height__Dp(receiver: pythonx.compose.ui.Modifier, /, height: float) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.height(height: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def height__IntrinsicSize(receiver: pythonx.compose.ui.Modifier, /, intrinsic_size: IntrinsicSize) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.height(intrinsicSize: androidx.compose.foundation.layout.IntrinsicSize): androidx.compose.ui.Modifier"""
    ...

def ime_padding(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.imePadding(): androidx.compose.ui.Modifier"""
    ...

def mandatory_system_gestures_padding(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.mandatorySystemGesturesPadding(): androidx.compose.ui.Modifier"""
    ...

def minus(receiver: _t.Any, /, other: _t.Any) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.PaddingValues.minus(other: androidx.compose.foundation.layout.PaddingValues): androidx.compose.foundation.layout.PaddingValues"""
    ...

def navigation_bars_padding(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.navigationBarsPadding(): androidx.compose.ui.Modifier"""
    ...

def offset__Dp_Dp(receiver: pythonx.compose.ui.Modifier, /, x: float = ..., y: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.offset(x: androidx.compose.ui.unit.Dp, y: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def offset__IntOffset(receiver: pythonx.compose.ui.Modifier, /, offset: _t.Callable[[_t.Any], _t.Any]) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.offset(offset: kotlin.Function1): androidx.compose.ui.Modifier"""
    ...

def on_consumed_window_insets_changed(receiver: pythonx.compose.ui.Modifier, /, block: _t.Callable[[_t.Any], None]) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.onConsumedWindowInsetsChanged(block: kotlin.Function1): androidx.compose.ui.Modifier"""
    ...

def only(receiver: _t.Any, /, sides: _t.Any) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.WindowInsets.only(sides: androidx.compose.foundation.layout.WindowInsetsSides): androidx.compose.foundation.layout.WindowInsets"""
    ...

def padding_from_baseline__Dp_Dp(receiver: pythonx.compose.ui.Modifier, /, top: float = ..., bottom: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.paddingFromBaseline(top: androidx.compose.ui.unit.Dp, bottom: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def padding_from_baseline__TextUnit_TextUnit(receiver: pythonx.compose.ui.Modifier, /, top: _t.Any = ..., bottom: _t.Any = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.paddingFromBaseline(top: androidx.compose.ui.unit.TextUnit, bottom: androidx.compose.ui.unit.TextUnit): androidx.compose.ui.Modifier"""
    ...

def padding_from__AlignmentLine_Dp_Dp(receiver: pythonx.compose.ui.Modifier, /, alignment_line: _t.Any, before: float = ..., after: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.paddingFrom(alignmentLine: androidx.compose.ui.layout.AlignmentLine, before: androidx.compose.ui.unit.Dp, after: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def padding_from__AlignmentLine_TextUnit_TextUnit(receiver: pythonx.compose.ui.Modifier, /, alignment_line: _t.Any, before: _t.Any = ..., after: _t.Any = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.paddingFrom(alignmentLine: androidx.compose.ui.layout.AlignmentLine, before: androidx.compose.ui.unit.TextUnit, after: androidx.compose.ui.unit.TextUnit): androidx.compose.ui.Modifier"""
    ...

def padding__Dp(receiver: pythonx.compose.ui.Modifier, /, all: float) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.padding(all: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def padding__Dp_Dp(receiver: pythonx.compose.ui.Modifier, /, horizontal: float = ..., vertical: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.padding(horizontal: androidx.compose.ui.unit.Dp, vertical: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def padding__Dp_Dp_Dp_Dp(receiver: pythonx.compose.ui.Modifier, /, start: float = ..., top: float = ..., end: float = ..., bottom: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.padding(start: androidx.compose.ui.unit.Dp, top: androidx.compose.ui.unit.Dp, end: androidx.compose.ui.unit.Dp, bottom: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def padding__PaddingValues(receiver: pythonx.compose.ui.Modifier, /, padding_values: _t.Any) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.padding(paddingValues: androidx.compose.foundation.layout.PaddingValues): androidx.compose.ui.Modifier"""
    ...

def plus(receiver: _t.Any, /, other: _t.Any) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.PaddingValues.plus(other: androidx.compose.foundation.layout.PaddingValues): androidx.compose.foundation.layout.PaddingValues"""
    ...

def recalculate_window_insets(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.recalculateWindowInsets(): androidx.compose.ui.Modifier"""
    ...

def required_height_in(receiver: pythonx.compose.ui.Modifier, /, min: float = ..., max: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.requiredHeightIn(min: androidx.compose.ui.unit.Dp, max: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def required_height__Dp(receiver: pythonx.compose.ui.Modifier, /, height: float) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.requiredHeight(height: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def required_height__IntrinsicSize(receiver: pythonx.compose.ui.Modifier, /, intrinsic_size: IntrinsicSize) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.requiredHeight(intrinsicSize: androidx.compose.foundation.layout.IntrinsicSize): androidx.compose.ui.Modifier"""
    ...

def required_size_in(receiver: pythonx.compose.ui.Modifier, /, min_width: float = ..., min_height: float = ..., max_width: float = ..., max_height: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.requiredSizeIn(minWidth: androidx.compose.ui.unit.Dp, minHeight: androidx.compose.ui.unit.Dp, maxWidth: androidx.compose.ui.unit.Dp, maxHeight: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def required_size__Dp(receiver: pythonx.compose.ui.Modifier, /, size: float) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.requiredSize(size: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def required_size__DpSize(receiver: pythonx.compose.ui.Modifier, /, size: _t.Any) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.requiredSize(size: androidx.compose.ui.unit.DpSize): androidx.compose.ui.Modifier"""
    ...

def required_size__Dp_Dp(receiver: pythonx.compose.ui.Modifier, /, width: float, height: float) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.requiredSize(width: androidx.compose.ui.unit.Dp, height: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def required_width_in(receiver: pythonx.compose.ui.Modifier, /, min: float = ..., max: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.requiredWidthIn(min: androidx.compose.ui.unit.Dp, max: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def required_width__Dp(receiver: pythonx.compose.ui.Modifier, /, width: float) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.requiredWidth(width: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def required_width__IntrinsicSize(receiver: pythonx.compose.ui.Modifier, /, intrinsic_size: IntrinsicSize) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.requiredWidth(intrinsicSize: androidx.compose.foundation.layout.IntrinsicSize): androidx.compose.ui.Modifier"""
    ...

def safe_content_padding(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.safeContentPadding(): androidx.compose.ui.Modifier"""
    ...

def safe_drawing_padding(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.safeDrawingPadding(): androidx.compose.ui.Modifier"""
    ...

def safe_gestures_padding(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.safeGesturesPadding(): androidx.compose.ui.Modifier"""
    ...

def size_in(receiver: pythonx.compose.ui.Modifier, /, min_width: float = ..., min_height: float = ..., max_width: float = ..., max_height: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.sizeIn(minWidth: androidx.compose.ui.unit.Dp, minHeight: androidx.compose.ui.unit.Dp, maxWidth: androidx.compose.ui.unit.Dp, maxHeight: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def size__Dp(receiver: pythonx.compose.ui.Modifier, /, size: float) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.size(size: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def size__DpSize(receiver: pythonx.compose.ui.Modifier, /, size: _t.Any) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.size(size: androidx.compose.ui.unit.DpSize): androidx.compose.ui.Modifier"""
    ...

def size__Dp_Dp(receiver: pythonx.compose.ui.Modifier, /, width: float, height: float) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.size(width: androidx.compose.ui.unit.Dp, height: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def status_bars_padding(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.statusBarsPadding(): androidx.compose.ui.Modifier"""
    ...

def system_bars_padding(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.systemBarsPadding(): androidx.compose.ui.Modifier"""
    ...

def system_gestures_padding(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.systemGesturesPadding(): androidx.compose.ui.Modifier"""
    ...

def union(receiver: _t.Any, /, insets: _t.Any) -> _t.Any:
    """Kotlin: androidx.compose.foundation.layout.WindowInsets.union(insets: androidx.compose.foundation.layout.WindowInsets): androidx.compose.foundation.layout.WindowInsets"""
    ...

def visible(receiver: pythonx.compose.ui.Modifier, /, visible: bool) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.visible(visible: kotlin.Boolean): androidx.compose.ui.Modifier"""
    ...

def waterfall_padding(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.waterfallPadding(): androidx.compose.ui.Modifier"""
    ...

def width_in(receiver: pythonx.compose.ui.Modifier, /, min: float = ..., max: float = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.widthIn(min: androidx.compose.ui.unit.Dp, max: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def width__Dp(receiver: pythonx.compose.ui.Modifier, /, width: float) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.width(width: androidx.compose.ui.unit.Dp): androidx.compose.ui.Modifier"""
    ...

def width__IntrinsicSize(receiver: pythonx.compose.ui.Modifier, /, intrinsic_size: IntrinsicSize) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.width(intrinsicSize: androidx.compose.foundation.layout.IntrinsicSize): androidx.compose.ui.Modifier"""
    ...

def window_insets_bottom_height(receiver: pythonx.compose.ui.Modifier, /, insets: _t.Any) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.windowInsetsBottomHeight(insets: androidx.compose.foundation.layout.WindowInsets): androidx.compose.ui.Modifier"""
    ...

def window_insets_end_width(receiver: pythonx.compose.ui.Modifier, /, insets: _t.Any) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.windowInsetsEndWidth(insets: androidx.compose.foundation.layout.WindowInsets): androidx.compose.ui.Modifier"""
    ...

def window_insets_padding(receiver: pythonx.compose.ui.Modifier, /, insets: _t.Any) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.windowInsetsPadding(insets: androidx.compose.foundation.layout.WindowInsets): androidx.compose.ui.Modifier"""
    ...

def window_insets_start_width(receiver: pythonx.compose.ui.Modifier, /, insets: _t.Any) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.windowInsetsStartWidth(insets: androidx.compose.foundation.layout.WindowInsets): androidx.compose.ui.Modifier"""
    ...

def window_insets_top_height(receiver: pythonx.compose.ui.Modifier, /, insets: _t.Any) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.windowInsetsTopHeight(insets: androidx.compose.foundation.layout.WindowInsets): androidx.compose.ui.Modifier"""
    ...

def wrap_content_height(receiver: pythonx.compose.ui.Modifier, /, align: pythonx.compose.ui.Alignment.Vertical = ..., unbounded: bool = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.wrapContentHeight(align: androidx.compose.ui.Alignment.Vertical, unbounded: kotlin.Boolean): androidx.compose.ui.Modifier"""
    ...

def wrap_content_size(receiver: pythonx.compose.ui.Modifier, /, align: _t.Any = ..., unbounded: bool = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.wrapContentSize(align: androidx.compose.ui.Alignment, unbounded: kotlin.Boolean): androidx.compose.ui.Modifier"""
    ...

def wrap_content_width(receiver: pythonx.compose.ui.Modifier, /, align: pythonx.compose.ui.Alignment.Horizontal = ..., unbounded: bool = ...) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.wrapContentWidth(align: androidx.compose.ui.Alignment.Horizontal, unbounded: kotlin.Boolean): androidx.compose.ui.Modifier"""
    ...

@_t.overload
def Box(modifier: pythonx.compose.ui.Modifier) -> None: ...
@_t.overload
def Box(modifier: pythonx.compose.ui.Modifier = ..., content_alignment: _t.Any = ..., propagate_min_constraints: bool = ..., *, content: _t.Callable[[BoxScope], None]) -> None: ...  # type: ignore[overload-cannot-match]

@_t.overload
def FlowColumn(modifier: pythonx.compose.ui.Modifier = ..., vertical_arrangement: Arrangement.Vertical = ..., horizontal_arrangement: Arrangement.Horizontal = ..., item_horizontal_alignment: pythonx.compose.ui.Alignment.Horizontal = ..., max_items_in_each_column: int = ..., max_lines: int = ..., overflow: _t.Any = ..., *, content: _t.Callable[[FlowColumnScope], None]) -> None: ...
@_t.overload
def FlowColumn(modifier: pythonx.compose.ui.Modifier = ..., vertical_arrangement: Arrangement.Vertical = ..., horizontal_arrangement: Arrangement.Horizontal = ..., item_horizontal_alignment: pythonx.compose.ui.Alignment.Horizontal = ..., max_items_in_each_column: int = ..., max_lines: int = ..., *, content: _t.Callable[[FlowColumnScope], None]) -> None: ...  # type: ignore[overload-cannot-match]

@_t.overload
def FlowRow(modifier: pythonx.compose.ui.Modifier = ..., horizontal_arrangement: Arrangement.Horizontal = ..., vertical_arrangement: Arrangement.Vertical = ..., item_vertical_alignment: pythonx.compose.ui.Alignment.Vertical = ..., max_items_in_each_row: int = ..., max_lines: int = ..., overflow: _t.Any = ..., *, content: _t.Callable[[FlowRowScope], None]) -> None: ...
@_t.overload
def FlowRow(modifier: pythonx.compose.ui.Modifier = ..., horizontal_arrangement: Arrangement.Horizontal = ..., vertical_arrangement: Arrangement.Vertical = ..., item_vertical_alignment: pythonx.compose.ui.Alignment.Vertical = ..., max_items_in_each_row: int = ..., max_lines: int = ..., *, content: _t.Callable[[FlowRowScope], None]) -> None: ...  # type: ignore[overload-cannot-match]

@_t.overload
def PaddingValues(all: float) -> _t.Any: ...
@_t.overload
def PaddingValues(horizontal: float = ..., vertical: float = ...) -> _t.Any: ...  # type: ignore[overload-cannot-match]
@_t.overload
def PaddingValues(start: float = ..., top: float = ..., end: float = ..., bottom: float = ...) -> _t.Any: ...  # type: ignore[overload-cannot-match]

@_t.overload
def WindowInsets() -> _t.Any: ...
@_t.overload
def WindowInsets(left: float = ..., top: float = ..., right: float = ..., bottom: float = ...) -> _t.Any: ...  # type: ignore[overload-cannot-match]
@_t.overload
def WindowInsets(left: int = ..., top: int = ..., right: int = ..., bottom: int = ...) -> _t.Any: ...  # type: ignore[overload-cannot-match]

@_t.overload
def absolute_offset(receiver: pythonx.compose.ui.Modifier, /, x: float = ..., y: float = ...) -> pythonx.compose.ui.Modifier: ...
@_t.overload
def absolute_offset(receiver: pythonx.compose.ui.Modifier, /, offset: _t.Callable[[_t.Any], _t.Any]) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]

@_t.overload
def as_padding_values(receiver: _t.Any, /) -> _t.Any: ...
@_t.overload
def as_padding_values(receiver: _t.Any, /, density: _t.Any) -> _t.Any: ...  # type: ignore[overload-cannot-match]

@_t.overload
def consume_window_insets(receiver: pythonx.compose.ui.Modifier, /, padding_values: _t.Any) -> pythonx.compose.ui.Modifier: ...
@_t.overload
def consume_window_insets(receiver: pythonx.compose.ui.Modifier, /, insets: _t.Any) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]

@_t.overload
def height(receiver: pythonx.compose.ui.Modifier, /, height: float) -> pythonx.compose.ui.Modifier: ...
@_t.overload
def height(receiver: pythonx.compose.ui.Modifier, /, intrinsic_size: IntrinsicSize) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]

@_t.overload
def offset(receiver: pythonx.compose.ui.Modifier, /, x: float = ..., y: float = ...) -> pythonx.compose.ui.Modifier: ...
@_t.overload
def offset(receiver: pythonx.compose.ui.Modifier, /, offset: _t.Callable[[_t.Any], _t.Any]) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]

@_t.overload
def padding(receiver: pythonx.compose.ui.Modifier, /, all: float) -> pythonx.compose.ui.Modifier: ...
@_t.overload
def padding(receiver: pythonx.compose.ui.Modifier, /, horizontal: float = ..., vertical: float = ...) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]
@_t.overload
def padding(receiver: pythonx.compose.ui.Modifier, /, start: float = ..., top: float = ..., end: float = ..., bottom: float = ...) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]
@_t.overload
def padding(receiver: pythonx.compose.ui.Modifier, /, padding_values: _t.Any) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]

@_t.overload
def padding_from(receiver: pythonx.compose.ui.Modifier, /, alignment_line: _t.Any, before: float = ..., after: float = ...) -> pythonx.compose.ui.Modifier: ...
@_t.overload
def padding_from(receiver: pythonx.compose.ui.Modifier, /, alignment_line: _t.Any, before: _t.Any = ..., after: _t.Any = ...) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]

@_t.overload
def padding_from_baseline(receiver: pythonx.compose.ui.Modifier, /, top: float = ..., bottom: float = ...) -> pythonx.compose.ui.Modifier: ...
@_t.overload
def padding_from_baseline(receiver: pythonx.compose.ui.Modifier, /, top: _t.Any = ..., bottom: _t.Any = ...) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]

@_t.overload
def required_height(receiver: pythonx.compose.ui.Modifier, /, height: float) -> pythonx.compose.ui.Modifier: ...
@_t.overload
def required_height(receiver: pythonx.compose.ui.Modifier, /, intrinsic_size: IntrinsicSize) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]

@_t.overload
def required_size(receiver: pythonx.compose.ui.Modifier, /, size: float) -> pythonx.compose.ui.Modifier: ...
@_t.overload
def required_size(receiver: pythonx.compose.ui.Modifier, /, size: _t.Any) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]
@_t.overload
def required_size(receiver: pythonx.compose.ui.Modifier, /, width: float, height: float) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]

@_t.overload
def required_width(receiver: pythonx.compose.ui.Modifier, /, width: float) -> pythonx.compose.ui.Modifier: ...
@_t.overload
def required_width(receiver: pythonx.compose.ui.Modifier, /, intrinsic_size: IntrinsicSize) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]

@_t.overload
def size(receiver: pythonx.compose.ui.Modifier, /, size: float) -> pythonx.compose.ui.Modifier: ...
@_t.overload
def size(receiver: pythonx.compose.ui.Modifier, /, size: _t.Any) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]
@_t.overload
def size(receiver: pythonx.compose.ui.Modifier, /, width: float, height: float) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]

@_t.overload
def width(receiver: pythonx.compose.ui.Modifier, /, width: float) -> pythonx.compose.ui.Modifier: ...
@_t.overload
def width(receiver: pythonx.compose.ui.Modifier, /, intrinsic_size: IntrinsicSize) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]

class Arrangement:
    """Kotlin: androidx.compose.foundation.layout.Arrangement"""
    class Horizontal:
        """Kotlin: androidx.compose.foundation.layout.Arrangement.Horizontal"""
        End: _t.ClassVar[Arrangement.Horizontal]
        Start: _t.ClassVar[Arrangement.Horizontal]
    class HorizontalOrVertical(Arrangement.Horizontal, Arrangement.Vertical):
        """Kotlin: androidx.compose.foundation.layout.Arrangement.HorizontalOrVertical"""
        Center: _t.ClassVar[Arrangement.HorizontalOrVertical]
        SpaceAround: _t.ClassVar[Arrangement.HorizontalOrVertical]
        SpaceBetween: _t.ClassVar[Arrangement.HorizontalOrVertical]
        SpaceEvenly: _t.ClassVar[Arrangement.HorizontalOrVertical]
    class Vertical:
        """Kotlin: androidx.compose.foundation.layout.Arrangement.Vertical"""
        Bottom: _t.ClassVar[Arrangement.Vertical]
        Top: _t.ClassVar[Arrangement.Vertical]
    Bottom: _t.ClassVar[Arrangement.Vertical]
    """Kotlin: androidx.compose.foundation.layout.Arrangement.Bottom(): androidx.compose.foundation.layout.Arrangement.Vertical"""
    Center: _t.ClassVar[Arrangement.HorizontalOrVertical]
    """Kotlin: androidx.compose.foundation.layout.Arrangement.Center(): androidx.compose.foundation.layout.Arrangement.HorizontalOrVertical"""
    End: _t.ClassVar[Arrangement.Horizontal]
    """Kotlin: androidx.compose.foundation.layout.Arrangement.End(): androidx.compose.foundation.layout.Arrangement.Horizontal"""
    SpaceAround: _t.ClassVar[Arrangement.HorizontalOrVertical]
    """Kotlin: androidx.compose.foundation.layout.Arrangement.SpaceAround(): androidx.compose.foundation.layout.Arrangement.HorizontalOrVertical"""
    SpaceBetween: _t.ClassVar[Arrangement.HorizontalOrVertical]
    """Kotlin: androidx.compose.foundation.layout.Arrangement.SpaceBetween(): androidx.compose.foundation.layout.Arrangement.HorizontalOrVertical"""
    SpaceEvenly: _t.ClassVar[Arrangement.HorizontalOrVertical]
    """Kotlin: androidx.compose.foundation.layout.Arrangement.SpaceEvenly(): androidx.compose.foundation.layout.Arrangement.HorizontalOrVertical"""
    Start: _t.ClassVar[Arrangement.Horizontal]
    """Kotlin: androidx.compose.foundation.layout.Arrangement.Start(): androidx.compose.foundation.layout.Arrangement.Horizontal"""
    Top: _t.ClassVar[Arrangement.Vertical]
    """Kotlin: androidx.compose.foundation.layout.Arrangement.Top(): androidx.compose.foundation.layout.Arrangement.Vertical"""
    @staticmethod
    def aligned__Horizontal(alignment: pythonx.compose.ui.Alignment.Horizontal) -> Arrangement.Horizontal:
        """Kotlin: androidx.compose.foundation.layout.Arrangement.aligned(alignment: androidx.compose.ui.Alignment.Horizontal): androidx.compose.foundation.layout.Arrangement.Horizontal"""
        ...
    @staticmethod
    def aligned__Vertical(alignment: pythonx.compose.ui.Alignment.Vertical) -> Arrangement.Vertical:
        """Kotlin: androidx.compose.foundation.layout.Arrangement.aligned(alignment: androidx.compose.ui.Alignment.Vertical): androidx.compose.foundation.layout.Arrangement.Vertical"""
        ...
    @staticmethod
    def spaced_by__Dp(space: float) -> Arrangement.HorizontalOrVertical:
        """Kotlin: androidx.compose.foundation.layout.Arrangement.spacedBy(space: androidx.compose.ui.unit.Dp): androidx.compose.foundation.layout.Arrangement.HorizontalOrVertical"""
        ...
    @staticmethod
    def spaced_by__Dp_Horizontal(space: float, alignment: pythonx.compose.ui.Alignment.Horizontal) -> Arrangement.Horizontal:
        """Kotlin: androidx.compose.foundation.layout.Arrangement.spacedBy(space: androidx.compose.ui.unit.Dp, alignment: androidx.compose.ui.Alignment.Horizontal): androidx.compose.foundation.layout.Arrangement.Horizontal"""
        ...
    @staticmethod
    def spaced_by__Dp_Vertical(space: float, alignment: pythonx.compose.ui.Alignment.Vertical) -> Arrangement.Vertical:
        """Kotlin: androidx.compose.foundation.layout.Arrangement.spacedBy(space: androidx.compose.ui.unit.Dp, alignment: androidx.compose.ui.Alignment.Vertical): androidx.compose.foundation.layout.Arrangement.Vertical"""
        ...
    @staticmethod
    @_t.overload
    def aligned(alignment: pythonx.compose.ui.Alignment.Horizontal) -> Arrangement.Horizontal: ...
    @staticmethod
    @_t.overload
    def aligned(alignment: pythonx.compose.ui.Alignment.Vertical) -> Arrangement.Vertical: ...  # type: ignore[overload-cannot-match]
    @staticmethod
    @_t.overload
    def spaced_by(space: float) -> Arrangement.HorizontalOrVertical: ...
    @staticmethod
    @_t.overload
    def spaced_by(space: float, alignment: pythonx.compose.ui.Alignment.Horizontal) -> Arrangement.Horizontal: ...  # type: ignore[overload-cannot-match]
    @staticmethod
    @_t.overload
    def spaced_by(space: float, alignment: pythonx.compose.ui.Alignment.Vertical) -> Arrangement.Vertical: ...  # type: ignore[overload-cannot-match]

class ContextualFlowColumnOverflow:
    """Kotlin: androidx.compose.foundation.layout.ContextualFlowColumnOverflow"""
    Clip: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.ContextualFlowColumnOverflow.Clip(): androidx.compose.foundation.layout.ContextualFlowColumnOverflow"""
    Visible: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.ContextualFlowColumnOverflow.Visible(): androidx.compose.foundation.layout.ContextualFlowColumnOverflow"""

class ContextualFlowRowOverflow:
    """Kotlin: androidx.compose.foundation.layout.ContextualFlowRowOverflow"""
    Clip: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.ContextualFlowRowOverflow.Clip(): androidx.compose.foundation.layout.ContextualFlowRowOverflow"""
    Visible: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.ContextualFlowRowOverflow.Visible(): androidx.compose.foundation.layout.ContextualFlowRowOverflow"""

class FlexAlignContent:
    """Kotlin: androidx.compose.foundation.layout.FlexAlignContent"""
    Center: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignContent.Center(): androidx.compose.foundation.layout.FlexAlignContent"""
    End: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignContent.End(): androidx.compose.foundation.layout.FlexAlignContent"""
    SpaceAround: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignContent.SpaceAround(): androidx.compose.foundation.layout.FlexAlignContent"""
    SpaceBetween: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignContent.SpaceBetween(): androidx.compose.foundation.layout.FlexAlignContent"""
    Start: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignContent.Start(): androidx.compose.foundation.layout.FlexAlignContent"""
    Stretch: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignContent.Stretch(): androidx.compose.foundation.layout.FlexAlignContent"""

class FlexAlignItems:
    """Kotlin: androidx.compose.foundation.layout.FlexAlignItems"""
    Baseline: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignItems.Baseline(): androidx.compose.foundation.layout.FlexAlignItems"""
    Center: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignItems.Center(): androidx.compose.foundation.layout.FlexAlignItems"""
    End: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignItems.End(): androidx.compose.foundation.layout.FlexAlignItems"""
    Start: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignItems.Start(): androidx.compose.foundation.layout.FlexAlignItems"""
    Stretch: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignItems.Stretch(): androidx.compose.foundation.layout.FlexAlignItems"""

class FlexAlignSelf:
    """Kotlin: androidx.compose.foundation.layout.FlexAlignSelf"""
    Auto: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignSelf.Auto(): androidx.compose.foundation.layout.FlexAlignSelf"""
    Baseline: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignSelf.Baseline(): androidx.compose.foundation.layout.FlexAlignSelf"""
    Center: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignSelf.Center(): androidx.compose.foundation.layout.FlexAlignSelf"""
    End: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignSelf.End(): androidx.compose.foundation.layout.FlexAlignSelf"""
    Start: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignSelf.Start(): androidx.compose.foundation.layout.FlexAlignSelf"""
    Stretch: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexAlignSelf.Stretch(): androidx.compose.foundation.layout.FlexAlignSelf"""

class FlexBasis:
    """Kotlin: androidx.compose.foundation.layout.FlexBasis"""
    Auto: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexBasis.Auto(): androidx.compose.foundation.layout.FlexBasis"""

class FlexDirection:
    """Kotlin: androidx.compose.foundation.layout.FlexDirection"""
    Column: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexDirection.Column(): androidx.compose.foundation.layout.FlexDirection"""
    ColumnReverse: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexDirection.ColumnReverse(): androidx.compose.foundation.layout.FlexDirection"""
    Row: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexDirection.Row(): androidx.compose.foundation.layout.FlexDirection"""
    RowReverse: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexDirection.RowReverse(): androidx.compose.foundation.layout.FlexDirection"""

class FlexJustifyContent:
    """Kotlin: androidx.compose.foundation.layout.FlexJustifyContent"""
    Center: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexJustifyContent.Center(): androidx.compose.foundation.layout.FlexJustifyContent"""
    End: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexJustifyContent.End(): androidx.compose.foundation.layout.FlexJustifyContent"""
    SpaceAround: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexJustifyContent.SpaceAround(): androidx.compose.foundation.layout.FlexJustifyContent"""
    SpaceBetween: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexJustifyContent.SpaceBetween(): androidx.compose.foundation.layout.FlexJustifyContent"""
    SpaceEvenly: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexJustifyContent.SpaceEvenly(): androidx.compose.foundation.layout.FlexJustifyContent"""
    Start: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexJustifyContent.Start(): androidx.compose.foundation.layout.FlexJustifyContent"""

class FlexWrap:
    """Kotlin: androidx.compose.foundation.layout.FlexWrap"""
    NoWrap: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexWrap.NoWrap(): androidx.compose.foundation.layout.FlexWrap"""
    Wrap: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexWrap.Wrap(): androidx.compose.foundation.layout.FlexWrap"""
    WrapReverse: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlexWrap.WrapReverse(): androidx.compose.foundation.layout.FlexWrap"""

class FlowColumnOverflow:
    """Kotlin: androidx.compose.foundation.layout.FlowColumnOverflow"""
    Clip: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlowColumnOverflow.Clip(): androidx.compose.foundation.layout.FlowColumnOverflow"""
    Visible: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlowColumnOverflow.Visible(): androidx.compose.foundation.layout.FlowColumnOverflow"""

class FlowRowOverflow:
    """Kotlin: androidx.compose.foundation.layout.FlowRowOverflow"""
    Clip: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlowRowOverflow.Clip(): androidx.compose.foundation.layout.FlowRowOverflow"""
    Visible: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.FlowRowOverflow.Visible(): androidx.compose.foundation.layout.FlowRowOverflow"""

class GridFlow:
    """Kotlin: androidx.compose.foundation.layout.GridFlow"""
    Column: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.GridFlow.Column(): androidx.compose.foundation.layout.GridFlow"""
    Row: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.GridFlow.Row(): androidx.compose.foundation.layout.GridFlow"""

class GridScope:
    """Kotlin: androidx.compose.foundation.layout.GridScope"""
    GridIndexUnspecified: _t.ClassVar[int]
    """Kotlin: androidx.compose.foundation.layout.GridScope.GridIndexUnspecified(): kotlin.Int"""
    MaxGridIndex: _t.ClassVar[int]
    """Kotlin: androidx.compose.foundation.layout.GridScope.MaxGridIndex(): kotlin.Int"""

class GridTrackSize:
    """Kotlin: androidx.compose.foundation.layout.GridTrackSize"""
    Auto: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.GridTrackSize.Auto(): androidx.compose.foundation.layout.GridTrackSize"""
    MaxContent: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.GridTrackSize.MaxContent(): androidx.compose.foundation.layout.GridTrackSize"""
    MinContent: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.GridTrackSize.MinContent(): androidx.compose.foundation.layout.GridTrackSize"""

class WindowInsetsSides:
    """Kotlin: androidx.compose.foundation.layout.WindowInsetsSides"""
    Bottom: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.WindowInsetsSides.Bottom(): androidx.compose.foundation.layout.WindowInsetsSides"""
    End: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.WindowInsetsSides.End(): androidx.compose.foundation.layout.WindowInsetsSides"""
    Horizontal: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.WindowInsetsSides.Horizontal(): androidx.compose.foundation.layout.WindowInsetsSides"""
    Left: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.WindowInsetsSides.Left(): androidx.compose.foundation.layout.WindowInsetsSides"""
    Right: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.WindowInsetsSides.Right(): androidx.compose.foundation.layout.WindowInsetsSides"""
    Start: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.WindowInsetsSides.Start(): androidx.compose.foundation.layout.WindowInsetsSides"""
    Top: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.WindowInsetsSides.Top(): androidx.compose.foundation.layout.WindowInsetsSides"""
    Vertical: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.foundation.layout.WindowInsetsSides.Vertical(): androidx.compose.foundation.layout.WindowInsetsSides"""
