# GENERATED by tools/gen_stubs.py from python-multiplatform's Kotlin-named stubs (artifact kotlin-stubs, workflow run 37077627980, commit 86012ca0, Compose 1.11.1). Do not edit.
# Methods are reached by snake_case names, but their keyword arguments keep Kotlin's names: the runtime does not translate a method's keywords yet.
import typing as _t
import pythonx.compose.ui

class _ColorFilter_asDesktopColorFilter(_t.Protocol):
    def __call__(self) -> _t.Any: ...

class _ColorFilter_asSkiaColorFilter(_t.Protocol):
    def __call__(self) -> _t.Any: ...

class _PathEffect_asDesktopPathEffect(_t.Protocol):
    def __call__(self) -> _t.Any: ...

class _PathEffect_asSkiaPathEffect(_t.Protocol):
    def __call__(self) -> _t.Any: ...

class _RenderEffect_asDesktopImageFilter(_t.Protocol):
    def __call__(self) -> _t.Any: ...

class Brush:
    """Kotlin: androidx.compose.ui.graphics.Brush"""

class ColorFilter:
    """Kotlin: androidx.compose.ui.graphics.ColorFilter"""
    as_desktop_color_filter: _t.ClassVar[_ColorFilter_asDesktopColorFilter]
    as_skia_color_filter: _t.ClassVar[_ColorFilter_asSkiaColorFilter]

class ColorProducer:
    """Kotlin: androidx.compose.ui.graphics.ColorProducer"""

class GraphicsContext:
    """Kotlin: androidx.compose.ui.graphics.GraphicsContext"""

class Outline:
    """Kotlin: androidx.compose.ui.graphics.Outline"""

class PathEffect:
    """Kotlin: androidx.compose.ui.graphics.PathEffect"""
    as_desktop_path_effect: _t.ClassVar[_PathEffect_asDesktopPathEffect]
    as_skia_path_effect: _t.ClassVar[_PathEffect_asSkiaPathEffect]

class PathSegment:
    """Kotlin: androidx.compose.ui.graphics.PathSegment"""

class RenderEffect:
    """Kotlin: androidx.compose.ui.graphics.RenderEffect"""
    as_desktop_image_filter: _t.ClassVar[_RenderEffect_asDesktopImageFilter]

class Shader:
    """Kotlin: androidx.compose.ui.graphics.Shader"""

class Shape:
    """Kotlin: androidx.compose.ui.graphics.Shape"""

def BlurEffect(radius_x: float, radius_y: float, edge_treatment: _t.Any = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.BlurEffect(radiusX: kotlin.Float, radiusY: kotlin.Float, edgeTreatment: androidx.compose.ui.graphics.TileMode): androidx.compose.ui.graphics.BlurEffect"""
    ...

def Canvas(image: _t.Any) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Canvas(image: androidx.compose.ui.graphics.ImageBitmap): androidx.compose.ui.graphics.Canvas"""
    ...

def Color__Float_Float_Float_Float_ColorSpace(red: float, green: float, blue: float, alpha: float = ..., color_space: _t.Any = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Color(red: kotlin.Float, green: kotlin.Float, blue: kotlin.Float, alpha: kotlin.Float, colorSpace: androidx.compose.ui.graphics.colorspace.ColorSpace): androidx.compose.ui.graphics.Color"""
    ...

def Color__Int(color: int) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Color(color: kotlin.Int): androidx.compose.ui.graphics.Color"""
    ...

def Color__Int_Int_Int_Int(red: int, green: int, blue: int, alpha: int = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Color(red: kotlin.Int, green: kotlin.Int, blue: kotlin.Int, alpha: kotlin.Int): androidx.compose.ui.graphics.Color"""
    ...

def Color__Long(color: int) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Color(color: kotlin.Long): androidx.compose.ui.graphics.Color"""
    ...

def CompositeShader(dst: Shader, src: Shader, blend_mode: _t.Any) -> Shader:
    """Kotlin: androidx.compose.ui.graphics.CompositeShader(dst: androidx.compose.ui.graphics.Shader, src: androidx.compose.ui.graphics.Shader, blendMode: androidx.compose.ui.graphics.BlendMode): androidx.compose.ui.graphics.Shader"""
    ...

def GraphicsLayerScope() -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.GraphicsLayerScope(): androidx.compose.ui.graphics.GraphicsLayerScope"""
    ...

def ImageBitmap(width: int, height: int, config: _t.Any = ..., has_alpha: bool = ..., color_space: _t.Any = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.ImageBitmap(width: kotlin.Int, height: kotlin.Int, config: androidx.compose.ui.graphics.ImageBitmapConfig, hasAlpha: kotlin.Boolean, colorSpace: androidx.compose.ui.graphics.colorspace.ColorSpace): androidx.compose.ui.graphics.ImageBitmap"""
    ...

def ImageShader(image: _t.Any, tile_mode_x: _t.Any = ..., tile_mode_y: _t.Any = ...) -> Shader:
    """Kotlin: androidx.compose.ui.graphics.ImageShader(image: androidx.compose.ui.graphics.ImageBitmap, tileModeX: androidx.compose.ui.graphics.TileMode, tileModeY: androidx.compose.ui.graphics.TileMode): androidx.compose.ui.graphics.Shader"""
    ...

def OffsetEffect(offset_x: float, offset_y: float) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.OffsetEffect(offsetX: kotlin.Float, offsetY: kotlin.Float): androidx.compose.ui.graphics.OffsetEffect"""
    ...

def Paint() -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Paint(): androidx.compose.ui.graphics.Paint"""
    ...

def Path() -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Path(): androidx.compose.ui.graphics.Path"""
    ...

def PathHitTester(path: _t.Any, tolerance: float = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.PathHitTester(path: androidx.compose.ui.graphics.Path, tolerance: kotlin.Float): androidx.compose.ui.graphics.PathHitTester"""
    ...

def PathIterator(path: _t.Any, conic_evaluation: _t.Any = ..., tolerance: float = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.PathIterator(path: androidx.compose.ui.graphics.Path, conicEvaluation: androidx.compose.ui.graphics.PathIterator.ConicEvaluation, tolerance: kotlin.Float): androidx.compose.ui.graphics.PathIterator"""
    ...

def PathMeasure() -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.PathMeasure(): androidx.compose.ui.graphics.PathMeasure"""
    ...

def ShaderBrush(shader: Shader) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.ShaderBrush(shader: androidx.compose.ui.graphics.Shader): androidx.compose.ui.graphics.ShaderBrush"""
    ...

def SkiaGraphicsContext(measure_draw_bounds: bool = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.SkiaGraphicsContext(measureDrawBounds: kotlin.Boolean): androidx.compose.ui.graphics.SkiaGraphicsContext"""
    ...

def TransformOrigin(pivot_fraction_x: float, pivot_fraction_y: float) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.TransformOrigin(pivotFractionX: kotlin.Float, pivotFractionY: kotlin.Float): androidx.compose.ui.graphics.TransformOrigin"""
    ...

def add_outline(receiver: _t.Any, /, outline: Outline) -> None:
    """Kotlin: androidx.compose.ui.graphics.Path.addOutline(outline: androidx.compose.ui.graphics.Outline): kotlin.Unit"""
    ...

def add_svg(receiver: _t.Any, /, path_data: str) -> None:
    """Kotlin: androidx.compose.ui.graphics.Path.addSvg(pathData: kotlin.String): kotlin.Unit"""
    ...

def as_compose_canvas(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: org.jetbrains.skia.Canvas.asComposeCanvas(): androidx.compose.ui.graphics.Canvas"""
    ...

def as_compose_color_filter(receiver: _t.Any, /) -> ColorFilter:
    """Kotlin: org.jetbrains.skia.ColorFilter.asComposeColorFilter(): androidx.compose.ui.graphics.ColorFilter"""
    ...

def as_compose_image_bitmap(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: org.jetbrains.skia.Bitmap.asComposeImageBitmap(): androidx.compose.ui.graphics.ImageBitmap"""
    ...

def as_compose_paint(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: org.jetbrains.skia.Paint.asComposePaint(): androidx.compose.ui.graphics.Paint"""
    ...

def as_compose_path(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: org.jetbrains.skia.Path.asComposePath(): androidx.compose.ui.graphics.Path"""
    ...

def as_compose_path_effect__PathEffect(receiver: _t.Any, /) -> PathEffect:
    """Kotlin: org.jetbrains.skia.PathEffect.asComposePathEffect(): androidx.compose.ui.graphics.PathEffect"""
    ...

def as_compose_path_effect__PathMeasure(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: org.jetbrains.skia.PathMeasure.asComposePathEffect(): androidx.compose.ui.graphics.PathMeasure"""
    ...

def as_compose_render_effect(receiver: _t.Any, /) -> RenderEffect:
    """Kotlin: org.jetbrains.skia.ImageFilter.asComposeRenderEffect(): androidx.compose.ui.graphics.RenderEffect"""
    ...

def as_compose_shader(receiver: _t.Any, /) -> Shader:
    """Kotlin: org.jetbrains.skia.Shader.asComposeShader(): androidx.compose.ui.graphics.Shader"""
    ...

def as_desktop_bitmap(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.ImageBitmap.asDesktopBitmap(): org.jetbrains.skia.Bitmap"""
    ...

def as_desktop_color_filter(receiver: ColorFilter, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.ColorFilter.asDesktopColorFilter(): org.jetbrains.skia.ColorFilter"""
    ...

def as_desktop_image_filter(receiver: RenderEffect, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.RenderEffect.asDesktopImageFilter(): org.jetbrains.skia.ImageFilter"""
    ...

def as_desktop_path(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Path.asDesktopPath(): org.jetbrains.skia.Path"""
    ...

def as_desktop_path_effect(receiver: PathEffect, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.PathEffect.asDesktopPathEffect(): org.jetbrains.skia.PathEffect"""
    ...

def as_image_bitmap__Bitmap(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: org.jetbrains.skia.Bitmap.asImageBitmap(): androidx.compose.ui.graphics.ImageBitmap"""
    ...

def as_image_bitmap__Image(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: org.jetbrains.skia.Image.asImageBitmap(): androidx.compose.ui.graphics.ImageBitmap"""
    ...

def as_skia_bitmap(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.ImageBitmap.asSkiaBitmap(): org.jetbrains.skia.Bitmap"""
    ...

def as_skia_color_filter(receiver: ColorFilter, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.ColorFilter.asSkiaColorFilter(): org.jetbrains.skia.ColorFilter"""
    ...

def as_skia_path(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Path.asSkiaPath(): org.jetbrains.skia.Path"""
    ...

def as_skia_path_effect(receiver: PathEffect, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.PathEffect.asSkiaPathEffect(): org.jetbrains.skia.PathEffect"""
    ...

def as_skia_path_measure(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.PathMeasure.asSkiaPathMeasure(): org.jetbrains.skia.PathMeasure"""
    ...

def composite_over(receiver: _t.Any, /, background: _t.Any) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Color.compositeOver(background: androidx.compose.ui.graphics.Color): androidx.compose.ui.graphics.Color"""
    ...

def compute_direction(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Path.computeDirection(): androidx.compose.ui.graphics.Path.Direction"""
    ...

def copy(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Path.copy(): androidx.compose.ui.graphics.Path"""
    ...

def decode_to_image_bitmap(receiver: bytes, /) -> _t.Any:
    """Kotlin: kotlin.ByteArray.decodeToImageBitmap(): androidx.compose.ui.graphics.ImageBitmap"""
    ...

def draw_outline__Outline_Brush_Float_DrawStyle_ColorFilter_BlendMode(receiver: _t.Any, /, outline: Outline, brush: Brush, alpha: float = ..., style: _t.Any = ..., color_filter: ColorFilter | None = ..., blend_mode: _t.Any = ...) -> None:
    """Kotlin: androidx.compose.ui.graphics.drawscope.DrawScope.drawOutline(outline: androidx.compose.ui.graphics.Outline, brush: androidx.compose.ui.graphics.Brush, alpha: kotlin.Float, style: androidx.compose.ui.graphics.drawscope.DrawStyle, colorFilter: androidx.compose.ui.graphics.ColorFilter?, blendMode: androidx.compose.ui.graphics.BlendMode): kotlin.Unit"""
    ...

def draw_outline__Outline_Color_Float_DrawStyle_ColorFilter_BlendMode(receiver: _t.Any, /, outline: Outline, color: _t.Any, alpha: float = ..., style: _t.Any = ..., color_filter: ColorFilter | None = ..., blend_mode: _t.Any = ...) -> None:
    """Kotlin: androidx.compose.ui.graphics.drawscope.DrawScope.drawOutline(outline: androidx.compose.ui.graphics.Outline, color: androidx.compose.ui.graphics.Color, alpha: kotlin.Float, style: androidx.compose.ui.graphics.drawscope.DrawStyle, colorFilter: androidx.compose.ui.graphics.ColorFilter?, blendMode: androidx.compose.ui.graphics.BlendMode): kotlin.Unit"""
    ...

def draw_outline__Outline_Paint(receiver: _t.Any, /, outline: Outline, paint: _t.Any) -> None:
    """Kotlin: androidx.compose.ui.graphics.Canvas.drawOutline(outline: androidx.compose.ui.graphics.Outline, paint: androidx.compose.ui.graphics.Paint): kotlin.Unit"""
    ...

def evaluate_cubic(p1: float, p2: float, t: float) -> float:
    """Kotlin: androidx.compose.ui.graphics.evaluateCubic(p1: kotlin.Float, p2: kotlin.Float, t: kotlin.Float): kotlin.Float"""
    ...

def evaluate_y(segment: PathSegment, t: float) -> float:
    """Kotlin: androidx.compose.ui.graphics.evaluateY(segment: androidx.compose.ui.graphics.PathSegment, t: kotlin.Float): kotlin.Float"""
    ...

def find_first_cubic_root(p0: float, p1: float, p2: float, p3: float) -> float:
    """Kotlin: androidx.compose.ui.graphics.findFirstCubicRoot(p0: kotlin.Float, p1: kotlin.Float, p2: kotlin.Float, p3: kotlin.Float): kotlin.Float"""
    ...

def find_first_root(segment: PathSegment, fraction: float) -> float:
    """Kotlin: androidx.compose.ui.graphics.findFirstRoot(segment: androidx.compose.ui.graphics.PathSegment, fraction: kotlin.Float): kotlin.Float"""
    ...

def graphics_layer__Float_Float_Float_Float_Float_Float_Float_Float_Float_Float_TransformOrigin_Shape_Boolean_RenderEffect_Color_Color_CompositingStrategy_BlendMode_ColorFilter(receiver: pythonx.compose.ui.Modifier, /, scale_x: float, scale_y: float, alpha: float, translation_x: float, translation_y: float, shadow_elevation: float, rotation_x: float, rotation_y: float, rotation_z: float, camera_distance: float, transform_origin: _t.Any, shape: Shape, clip: bool, render_effect: RenderEffect | None, ambient_shadow_color: _t.Any, spot_shadow_color: _t.Any, compositing_strategy: _t.Any, blend_mode: _t.Any, color_filter: ColorFilter | None) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.graphicsLayer(scaleX: kotlin.Float, scaleY: kotlin.Float, alpha: kotlin.Float, translationX: kotlin.Float, translationY: kotlin.Float, shadowElevation: kotlin.Float, rotationX: kotlin.Float, rotationY: kotlin.Float, rotationZ: kotlin.Float, cameraDistance: kotlin.Float, transformOrigin: androidx.compose.ui.graphics.TransformOrigin, shape: androidx.compose.ui.graphics.Shape, clip: kotlin.Boolean, renderEffect: androidx.compose.ui.graphics.RenderEffect?, ambientShadowColor: androidx.compose.ui.graphics.Color, spotShadowColor: androidx.compose.ui.graphics.Color, compositingStrategy: androidx.compose.ui.graphics.CompositingStrategy, blendMode: androidx.compose.ui.graphics.BlendMode, colorFilter: androidx.compose.ui.graphics.ColorFilter?): androidx.compose.ui.Modifier"""
    ...

def graphics_layer__Unit(receiver: pythonx.compose.ui.Modifier, /, block: _t.Callable[[_t.Any], None]) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.graphicsLayer(block: kotlin.Function1): androidx.compose.ui.Modifier"""
    ...

def is_identity(receiver: _t.Any, /) -> bool:
    """Kotlin: androidx.compose.ui.graphics.Matrix.isIdentity(): kotlin.Boolean"""
    ...

def is_supported__BlendMode(receiver: _t.Any, /) -> bool:
    """Kotlin: androidx.compose.ui.graphics.BlendMode.isSupported(): kotlin.Boolean"""
    ...

def is_supported__TileMode(receiver: _t.Any, /) -> bool:
    """Kotlin: androidx.compose.ui.graphics.TileMode.isSupported(): kotlin.Boolean"""
    ...

def lerp__Color_Color_Float(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.lerp(start: androidx.compose.ui.graphics.Color, stop: androidx.compose.ui.graphics.Color, fraction: kotlin.Float): androidx.compose.ui.graphics.Color"""
    ...

def lerp__Shadow_Shadow_Float(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.lerp(start: androidx.compose.ui.graphics.Shadow, stop: androidx.compose.ui.graphics.Shadow, fraction: kotlin.Float): androidx.compose.ui.graphics.Shadow"""
    ...

def luminance(receiver: _t.Any, /) -> float:
    """Kotlin: androidx.compose.ui.graphics.Color.luminance(): kotlin.Float"""
    ...

def materialize_skia_path(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Path.materializeSkiaPath(): org.jetbrains.skia.Path"""
    ...

def prepare_transformation_matrix(matrix: _t.Any, pivot_x: float, pivot_y: float, translation_x: float, translation_y: float, rotation_x: float, rotation_y: float, rotation_z: float, scale_x: float, scale_y: float, camera_distance: float) -> None:
    """Kotlin: androidx.compose.ui.graphics.prepareTransformationMatrix(matrix: androidx.compose.ui.graphics.Matrix, pivotX: kotlin.Float, pivotY: kotlin.Float, translationX: kotlin.Float, translationY: kotlin.Float, rotationX: kotlin.Float, rotationY: kotlin.Float, rotationZ: kotlin.Float, scaleX: kotlin.Float, scaleY: kotlin.Float, cameraDistance: kotlin.Float): kotlin.Unit"""
    ...

def remember_graphics_layer() -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.rememberGraphicsLayer(): androidx.compose.ui.graphics.layer.GraphicsLayer"""
    ...

def reverse(receiver: _t.Any, /, destination: _t.Any = ...) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Path.reverse(destination: androidx.compose.ui.graphics.Path): androidx.compose.ui.graphics.Path"""
    ...

def rotate(receiver: _t.Any, /, degrees: float, pivot_x: float, pivot_y: float) -> None:
    """Kotlin: androidx.compose.ui.graphics.Canvas.rotate(degrees: kotlin.Float, pivotX: kotlin.Float, pivotY: kotlin.Float): kotlin.Unit"""
    ...

def rotate_rad(receiver: _t.Any, /, radians: float, pivot_x: float = ..., pivot_y: float = ...) -> None:
    """Kotlin: androidx.compose.ui.graphics.Canvas.rotateRad(radians: kotlin.Float, pivotX: kotlin.Float, pivotY: kotlin.Float): kotlin.Unit"""
    ...

def scale(receiver: _t.Any, /, sx: float, sy: float = ..., *, pivot_x: float, pivot_y: float) -> None:
    """Kotlin: androidx.compose.ui.graphics.Canvas.scale(sx: kotlin.Float, sy: kotlin.Float, pivotX: kotlin.Float, pivotY: kotlin.Float): kotlin.Unit"""
    ...

def take_or_else(receiver: _t.Any, /, block: _t.Callable[[], _t.Any]) -> _t.Any:
    """Kotlin: androidx.compose.ui.graphics.Color.takeOrElse(block: kotlin.Function0): androidx.compose.ui.graphics.Color"""
    ...

def to_argb(receiver: _t.Any, /) -> int:
    """Kotlin: androidx.compose.ui.graphics.Color.toArgb(): kotlin.Int"""
    ...

def to_compose_color_filter(receiver: _t.Any, /) -> ColorFilter:
    """Kotlin: org.jetbrains.skia.ColorFilter.toComposeColorFilter(): androidx.compose.ui.graphics.ColorFilter"""
    ...

def to_compose_image_bitmap(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: org.jetbrains.skia.Image.toComposeImageBitmap(): androidx.compose.ui.graphics.ImageBitmap"""
    ...

def to_compose_rect(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: org.jetbrains.skia.Rect.toComposeRect(): androidx.compose.ui.geometry.Rect"""
    ...

def to_skia_r_rect(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.geometry.RoundRect.toSkiaRRect(): org.jetbrains.skia.RRect"""
    ...

def to_skia_rect(receiver: _t.Any, /) -> _t.Any:
    """Kotlin: androidx.compose.ui.geometry.Rect.toSkiaRect(): org.jetbrains.skia.Rect"""
    ...

def to_svg(receiver: _t.Any, /, as_document: bool = ...) -> str:
    """Kotlin: androidx.compose.ui.graphics.Path.toSvg(asDocument: kotlin.Boolean): kotlin.String"""
    ...

def tooling_graphics_layer(receiver: pythonx.compose.ui.Modifier, /) -> pythonx.compose.ui.Modifier:
    """Kotlin: androidx.compose.ui.Modifier.toolingGraphicsLayer(): androidx.compose.ui.Modifier"""
    ...

def with_save(receiver: _t.Any, /, block: _t.Callable[[], None]) -> None:
    """Kotlin: androidx.compose.ui.graphics.Canvas.withSave(block: kotlin.Function0): kotlin.Unit"""
    ...

def with_save_layer(receiver: _t.Any, /, bounds: _t.Any, paint: _t.Any, block: _t.Callable[[], None]) -> None:
    """Kotlin: androidx.compose.ui.graphics.Canvas.withSaveLayer(bounds: androidx.compose.ui.geometry.Rect, paint: androidx.compose.ui.graphics.Paint, block: kotlin.Function0): kotlin.Unit"""
    ...

@_t.overload
def Color(red: float, green: float, blue: float, alpha: float = ..., color_space: _t.Any = ...) -> _t.Any: ...
@_t.overload
def Color(color: int) -> _t.Any: ...  # type: ignore[overload-cannot-match]
@_t.overload
def Color(red: int, green: int, blue: int, alpha: int = ...) -> _t.Any: ...  # type: ignore[overload-cannot-match]
@_t.overload
def Color(color: int) -> _t.Any: ...  # type: ignore[overload-cannot-match]

@_t.overload
def as_compose_path_effect(receiver: _t.Any, /) -> PathEffect: ...
@_t.overload
def as_compose_path_effect(receiver: _t.Any, /) -> _t.Any: ...  # type: ignore[overload-cannot-match]

@_t.overload
def as_image_bitmap(receiver: _t.Any, /) -> _t.Any: ...
@_t.overload
def as_image_bitmap(receiver: _t.Any, /) -> _t.Any: ...  # type: ignore[overload-cannot-match]

@_t.overload
def draw_outline(receiver: _t.Any, /, outline: Outline, brush: Brush, alpha: float = ..., style: _t.Any = ..., color_filter: ColorFilter | None = ..., blend_mode: _t.Any = ...) -> None: ...
@_t.overload
def draw_outline(receiver: _t.Any, /, outline: Outline, color: _t.Any, alpha: float = ..., style: _t.Any = ..., color_filter: ColorFilter | None = ..., blend_mode: _t.Any = ...) -> None: ...  # type: ignore[overload-cannot-match]
@_t.overload
def draw_outline(receiver: _t.Any, /, outline: Outline, paint: _t.Any) -> None: ...  # type: ignore[overload-cannot-match]

@_t.overload
def graphics_layer(receiver: pythonx.compose.ui.Modifier, /, scale_x: float, scale_y: float, alpha: float, translation_x: float, translation_y: float, shadow_elevation: float, rotation_x: float, rotation_y: float, rotation_z: float, camera_distance: float, transform_origin: _t.Any, shape: Shape, clip: bool, render_effect: RenderEffect | None, ambient_shadow_color: _t.Any, spot_shadow_color: _t.Any, compositing_strategy: _t.Any, blend_mode: _t.Any, color_filter: ColorFilter | None) -> pythonx.compose.ui.Modifier: ...
@_t.overload
def graphics_layer(receiver: pythonx.compose.ui.Modifier, /, block: _t.Callable[[_t.Any], None]) -> pythonx.compose.ui.Modifier: ...  # type: ignore[overload-cannot-match]

@_t.overload
def is_supported(receiver: _t.Any, /) -> bool: ...
@_t.overload
def is_supported(receiver: _t.Any, /) -> bool: ...  # type: ignore[overload-cannot-match]

@_t.overload
def lerp(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any: ...
@_t.overload
def lerp(start: _t.Any, stop: _t.Any, fraction: float) -> _t.Any: ...  # type: ignore[overload-cannot-match]

class BlendMode:
    """Kotlin: androidx.compose.ui.graphics.BlendMode"""
    Clear: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Clear(): androidx.compose.ui.graphics.BlendMode"""
    Color: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Color(): androidx.compose.ui.graphics.BlendMode"""
    ColorBurn: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.ColorBurn(): androidx.compose.ui.graphics.BlendMode"""
    ColorDodge: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.ColorDodge(): androidx.compose.ui.graphics.BlendMode"""
    Darken: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Darken(): androidx.compose.ui.graphics.BlendMode"""
    Difference: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Difference(): androidx.compose.ui.graphics.BlendMode"""
    Dst: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Dst(): androidx.compose.ui.graphics.BlendMode"""
    DstAtop: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.DstAtop(): androidx.compose.ui.graphics.BlendMode"""
    DstIn: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.DstIn(): androidx.compose.ui.graphics.BlendMode"""
    DstOut: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.DstOut(): androidx.compose.ui.graphics.BlendMode"""
    DstOver: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.DstOver(): androidx.compose.ui.graphics.BlendMode"""
    Exclusion: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Exclusion(): androidx.compose.ui.graphics.BlendMode"""
    Hardlight: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Hardlight(): androidx.compose.ui.graphics.BlendMode"""
    Hue: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Hue(): androidx.compose.ui.graphics.BlendMode"""
    Lighten: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Lighten(): androidx.compose.ui.graphics.BlendMode"""
    Luminosity: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Luminosity(): androidx.compose.ui.graphics.BlendMode"""
    Modulate: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Modulate(): androidx.compose.ui.graphics.BlendMode"""
    Multiply: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Multiply(): androidx.compose.ui.graphics.BlendMode"""
    Overlay: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Overlay(): androidx.compose.ui.graphics.BlendMode"""
    Plus: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Plus(): androidx.compose.ui.graphics.BlendMode"""
    Saturation: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Saturation(): androidx.compose.ui.graphics.BlendMode"""
    Screen: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Screen(): androidx.compose.ui.graphics.BlendMode"""
    Softlight: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Softlight(): androidx.compose.ui.graphics.BlendMode"""
    Src: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Src(): androidx.compose.ui.graphics.BlendMode"""
    SrcAtop: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.SrcAtop(): androidx.compose.ui.graphics.BlendMode"""
    SrcIn: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.SrcIn(): androidx.compose.ui.graphics.BlendMode"""
    SrcOut: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.SrcOut(): androidx.compose.ui.graphics.BlendMode"""
    SrcOver: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.SrcOver(): androidx.compose.ui.graphics.BlendMode"""
    Xor: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.BlendMode.Xor(): androidx.compose.ui.graphics.BlendMode"""

class ClipOp:
    """Kotlin: androidx.compose.ui.graphics.ClipOp"""
    Difference: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.ClipOp.Difference(): androidx.compose.ui.graphics.ClipOp"""
    Intersect: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.ClipOp.Intersect(): androidx.compose.ui.graphics.ClipOp"""

class CompositingStrategy:
    """Kotlin: androidx.compose.ui.graphics.CompositingStrategy"""
    Auto: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.CompositingStrategy.Auto(): androidx.compose.ui.graphics.CompositingStrategy"""
    ModulateAlpha: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.CompositingStrategy.ModulateAlpha(): androidx.compose.ui.graphics.CompositingStrategy"""
    Offscreen: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.CompositingStrategy.Offscreen(): androidx.compose.ui.graphics.CompositingStrategy"""

class FilterQuality:
    """Kotlin: androidx.compose.ui.graphics.FilterQuality"""
    High: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.FilterQuality.High(): androidx.compose.ui.graphics.FilterQuality"""
    Low: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.FilterQuality.Low(): androidx.compose.ui.graphics.FilterQuality"""
    Medium: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.FilterQuality.Medium(): androidx.compose.ui.graphics.FilterQuality"""

class ImageBitmapConfig:
    """Kotlin: androidx.compose.ui.graphics.ImageBitmapConfig"""
    Alpha8: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.ImageBitmapConfig.Alpha8(): androidx.compose.ui.graphics.ImageBitmapConfig"""
    Argb8888: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.ImageBitmapConfig.Argb8888(): androidx.compose.ui.graphics.ImageBitmapConfig"""
    F16: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.ImageBitmapConfig.F16(): androidx.compose.ui.graphics.ImageBitmapConfig"""
    Gpu: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.ImageBitmapConfig.Gpu(): androidx.compose.ui.graphics.ImageBitmapConfig"""
    Rgb565: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.ImageBitmapConfig.Rgb565(): androidx.compose.ui.graphics.ImageBitmapConfig"""

class Matrix:
    """Kotlin: androidx.compose.ui.graphics.Matrix"""
    Perspective0: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.Matrix.Perspective0(): kotlin.Int"""
    Perspective1: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.Matrix.Perspective1(): kotlin.Int"""
    Perspective2: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.Matrix.Perspective2(): kotlin.Int"""
    ScaleX: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.Matrix.ScaleX(): kotlin.Int"""
    ScaleY: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.Matrix.ScaleY(): kotlin.Int"""
    ScaleZ: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.Matrix.ScaleZ(): kotlin.Int"""
    SkewX: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.Matrix.SkewX(): kotlin.Int"""
    SkewY: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.Matrix.SkewY(): kotlin.Int"""
    TranslateX: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.Matrix.TranslateX(): kotlin.Int"""
    TranslateY: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.Matrix.TranslateY(): kotlin.Int"""
    TranslateZ: _t.ClassVar[int]
    """Kotlin: androidx.compose.ui.graphics.Matrix.TranslateZ(): kotlin.Int"""

class PaintingStyle:
    """Kotlin: androidx.compose.ui.graphics.PaintingStyle"""
    Fill: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.PaintingStyle.Fill(): androidx.compose.ui.graphics.PaintingStyle"""
    Stroke: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.PaintingStyle.Stroke(): androidx.compose.ui.graphics.PaintingStyle"""

class PathFillType:
    """Kotlin: androidx.compose.ui.graphics.PathFillType"""
    EvenOdd: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.PathFillType.EvenOdd(): androidx.compose.ui.graphics.PathFillType"""
    NonZero: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.PathFillType.NonZero(): androidx.compose.ui.graphics.PathFillType"""

class PathOperation:
    """Kotlin: androidx.compose.ui.graphics.PathOperation"""
    Difference: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.PathOperation.Difference(): androidx.compose.ui.graphics.PathOperation"""
    Intersect: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.PathOperation.Intersect(): androidx.compose.ui.graphics.PathOperation"""
    ReverseDifference: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.PathOperation.ReverseDifference(): androidx.compose.ui.graphics.PathOperation"""
    Union: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.PathOperation.Union(): androidx.compose.ui.graphics.PathOperation"""
    Xor: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.PathOperation.Xor(): androidx.compose.ui.graphics.PathOperation"""

class PointMode:
    """Kotlin: androidx.compose.ui.graphics.PointMode"""
    Lines: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.PointMode.Lines(): androidx.compose.ui.graphics.PointMode"""
    Points: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.PointMode.Points(): androidx.compose.ui.graphics.PointMode"""
    Polygon: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.PointMode.Polygon(): androidx.compose.ui.graphics.PointMode"""

class Shadow:
    """Kotlin: androidx.compose.ui.graphics.Shadow"""

class StampedPathEffectStyle:
    """Kotlin: androidx.compose.ui.graphics.StampedPathEffectStyle"""
    Morph: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.StampedPathEffectStyle.Morph(): androidx.compose.ui.graphics.StampedPathEffectStyle"""
    Rotate: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.StampedPathEffectStyle.Rotate(): androidx.compose.ui.graphics.StampedPathEffectStyle"""
    Translate: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.StampedPathEffectStyle.Translate(): androidx.compose.ui.graphics.StampedPathEffectStyle"""

class StrokeCap:
    """Kotlin: androidx.compose.ui.graphics.StrokeCap"""
    Butt: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.StrokeCap.Butt(): androidx.compose.ui.graphics.StrokeCap"""
    Round: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.StrokeCap.Round(): androidx.compose.ui.graphics.StrokeCap"""
    Square: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.StrokeCap.Square(): androidx.compose.ui.graphics.StrokeCap"""

class StrokeJoin:
    """Kotlin: androidx.compose.ui.graphics.StrokeJoin"""
    Bevel: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.StrokeJoin.Bevel(): androidx.compose.ui.graphics.StrokeJoin"""
    Miter: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.StrokeJoin.Miter(): androidx.compose.ui.graphics.StrokeJoin"""
    Round: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.StrokeJoin.Round(): androidx.compose.ui.graphics.StrokeJoin"""

class TileMode:
    """Kotlin: androidx.compose.ui.graphics.TileMode"""
    Clamp: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.TileMode.Clamp(): androidx.compose.ui.graphics.TileMode"""
    Decal: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.TileMode.Decal(): androidx.compose.ui.graphics.TileMode"""
    Mirror: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.TileMode.Mirror(): androidx.compose.ui.graphics.TileMode"""
    Repeated: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.TileMode.Repeated(): androidx.compose.ui.graphics.TileMode"""

class VertexMode:
    """Kotlin: androidx.compose.ui.graphics.VertexMode"""
    TriangleFan: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.VertexMode.TriangleFan(): androidx.compose.ui.graphics.VertexMode"""
    TriangleStrip: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.VertexMode.TriangleStrip(): androidx.compose.ui.graphics.VertexMode"""
    Triangles: _t.ClassVar[_t.Any]
    """Kotlin: androidx.compose.ui.graphics.VertexMode.Triangles(): androidx.compose.ui.graphics.VertexMode"""
