# GENERATED by python-multiplatform-gradle-plugin. Do not edit.

import typing as _t
import androidx.compose.foundation.layout

class _Modifier_fillMaxWidth(_t.Protocol):
    def __call__(self) -> Modifier: ...

class _Modifier_padding(_t.Protocol):
    @_t.overload
    def __call__(self, all: float) -> Modifier: ...
    @_t.overload
    def __call__(self, paddingValues: _t.Any) -> Modifier: ...  # type: ignore[overload-cannot-match]

class _Modifier_padding__PaddingValues(_t.Protocol):
    def __call__(self, paddingValues: _t.Any) -> Modifier: ...

class _Modifier_zIndex(_t.Protocol):
    def __call__(self, zIndex: float) -> Modifier: ...

class _Modifier_column(_t.Protocol):
    def __call__(self, scope: androidx.compose.foundation.layout.ColumnScope) -> Modifier: ...

class Alignment:
    """Kotlin: androidx.compose.ui.Alignment"""
    Center: _t.ClassVar[_t.Any]
    CenterHorizontally: _t.ClassVar[_t.Any]
    End: _t.ClassVar[_t.Any]
    Top: _t.ClassVar[_t.Any]

class Modifier:
    """Kotlin: androidx.compose.ui.Modifier"""
    column: _t.ClassVar[_Modifier_column]
    fillMaxWidth: _t.ClassVar[_Modifier_fillMaxWidth]
    padding: _t.ClassVar[_Modifier_padding]
    padding__PaddingValues: _t.ClassVar[_Modifier_padding__PaddingValues]
    zIndex: _t.ClassVar[_Modifier_zIndex]

def describeModifier(modifier: Modifier) -> str:
    """Kotlin: androidx.compose.ui.describeModifier(modifier: androidx.compose.ui.Modifier): kotlin.String"""
    ...

def toURLString(raw: str) -> str:
    """Kotlin: androidx.compose.ui.toURLString(raw: kotlin.String): kotlin.String"""
    ...
