# GENERATED by python-multiplatform-gradle-plugin. Do not edit.

import typing as _t

class Horizontal:
    """Kotlin: androidx.compose.ui.Alignment.Horizontal"""

class Vertical:
    """Kotlin: androidx.compose.ui.Alignment.Vertical"""

Center: _t.Any
"""Kotlin: androidx.compose.ui.Alignment.Center(): androidx.compose.ui.Alignment"""

End: Horizontal
"""Kotlin: androidx.compose.ui.Alignment.End(): androidx.compose.ui.Alignment.Horizontal"""

Top: Vertical
"""Kotlin: androidx.compose.ui.Alignment.Top(): androidx.compose.ui.Alignment.Vertical"""
