# GENERATED by python-multiplatform-gradle-plugin. Do not edit.

import typing as _t
import androidx.compose.ui.Alignment

class Horizontal:
    """Kotlin: androidx.compose.foundation.layout.Arrangement.Horizontal"""

class HorizontalOrVertical(Horizontal, Vertical):
    """Kotlin: androidx.compose.foundation.layout.Arrangement.HorizontalOrVertical"""

class Vertical:
    """Kotlin: androidx.compose.foundation.layout.Arrangement.Vertical"""

End: Horizontal
"""Kotlin: androidx.compose.foundation.layout.Arrangement.End(): androidx.compose.foundation.layout.Arrangement.Horizontal"""

SpaceBetween: HorizontalOrVertical
"""Kotlin: androidx.compose.foundation.layout.Arrangement.SpaceBetween(): androidx.compose.foundation.layout.Arrangement.HorizontalOrVertical"""

Top: Vertical
"""Kotlin: androidx.compose.foundation.layout.Arrangement.Top(): androidx.compose.foundation.layout.Arrangement.Vertical"""

def aligned__Horizontal(alignment: androidx.compose.ui.Alignment.Horizontal) -> Horizontal:
    """Kotlin: androidx.compose.foundation.layout.Arrangement.aligned(alignment: androidx.compose.ui.Alignment.Horizontal): androidx.compose.foundation.layout.Arrangement.Horizontal"""
    ...

def aligned__Vertical(alignment: androidx.compose.ui.Alignment.Vertical) -> Vertical:
    """Kotlin: androidx.compose.foundation.layout.Arrangement.aligned(alignment: androidx.compose.ui.Alignment.Vertical): androidx.compose.foundation.layout.Arrangement.Vertical"""
    ...

def spacedBy__Dp(space: float) -> HorizontalOrVertical:
    """Kotlin: androidx.compose.foundation.layout.Arrangement.spacedBy(space: androidx.compose.ui.unit.Dp): androidx.compose.foundation.layout.Arrangement.HorizontalOrVertical"""
    ...
