"""Generate `pythonx.compose` stubs from the binder's Kotlin-named stubs, by the runtime's own rule.

    python3 tools/gen_stubs.py <kotlin-stub-root> [--out pythonx/compose/..]

`<kotlin-stub-root>` is what python-multiplatform's `PythonStubsTask` writes: one
`androidx/compose/.../__init__.pyi` per Kotlin package, Kotlin names unchanged. For each module in
`pythonx-map.toml`, this reads the stub of the Kotlin package it maps to and writes the Pythonic one
next to the module's `__init__.py`:

- a function or constant is renamed with `pythonx.compose._reexport.python_name`, the function the
  runtime resolves names with, so an editor completes what the interpreter answers;
- a parameter is renamed with `snake_case`, except the positional-only `receiver` and anonymous
  `__aN` slots, which a caller never writes by name;
- every explicit overload (`padding__Dp`, `padding__Dp_Dp`) also contributes an `@overload` of its
  base name (`padding`), which is the name the runtime's dispatcher answers to, fewest parameters
  first because a type checker takes the first match;
- a nested object stub (`Arrangement/__init__.pyi`) is converted the same way, one level down;
- names the module's own `__init__.py` defines (`runtime.Composable`) are carried over, because a
  `.pyi` beside a module replaces everything a type checker knows about it.

Nothing here names a Kotlin declaration; it is the same rule `_reexport.py` applies at run time.
"""

from __future__ import annotations

import argparse
import ast
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from pythonx.compose._reexport import manifest, python_name, snake_case  # noqa: E402

HEADER = "# GENERATED by tools/gen_stubs.py from python-multiplatform's Kotlin-named stubs. Do not edit.\n"
STUB_NAME = "__init__.pyi"


def _keeps_its_name(name: str) -> bool:
    return name == "receiver" or name.startswith("__a")


def _rename_arguments(arguments: ast.arguments) -> ast.arguments:
    for group in (arguments.posonlyargs, arguments.args, arguments.kwonlyargs):
        for argument in group:
            if not _keeps_its_name(argument.arg):
                argument.arg = snake_case(argument.arg)
    return arguments


def _arity(arguments: ast.arguments) -> int:
    return len(arguments.posonlyargs) + len(arguments.args) + len(arguments.kwonlyargs)


def _overload(function: ast.FunctionDef, name: str) -> ast.FunctionDef:
    copy = ast.parse(ast.unparse(function)).body[0]
    copy.name = name
    copy.decorator_list = [ast.Name(id="overload", ctx=ast.Load())] + copy.decorator_list
    return copy


def convert(source: str) -> str:
    """One Kotlin-named stub module, rewritten to the Pythonic surface."""
    tree = ast.parse(source)
    body: list[ast.stmt] = []
    overloads: dict[str, list[ast.FunctionDef]] = defaultdict(list)
    for node in tree.body:
        if isinstance(node, ast.FunctionDef):
            node.name = python_name(node.name)
            _rename_arguments(node.args)
            base, sep, _ = node.name.partition("__")
            if sep:
                overloads[base].append(node)
            body.append(node)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            node.target.id = python_name(node.target.id)
            body.append(node)
        elif isinstance(node, ast.ClassDef):
            for member in node.body:
                if isinstance(member, ast.FunctionDef) and not member.name.startswith("__"):
                    member.name = python_name(member.name)
                    _rename_arguments(member.args)
            body.append(node)
        else:
            body.append(node)
    defined = {node.name for node in body if isinstance(node, ast.FunctionDef)}
    for base, variants in overloads.items():
        if base in defined:
            continue
        # mypy picks the first matching `@overload`, so the order is the contract: fewest parameters
        # first, ties kept in table order -- the order the binder's dispatcher tries them in.
        ordered = sorted(variants, key=lambda variant: _arity(variant.args))
        body.extend(_overload(variant, base) for variant in ordered)
    lines = [HEADER]
    if overloads:
        lines.append("from typing import overload\n")
    lines.extend(ast.unparse(node) + "\n" for node in body)
    return "\n".join(lines)


def own_definitions(init_py: Path) -> list[str]:
    """Stub text for the public functions and classes a package's own `__init__.py` defines."""
    if not init_py.is_file():
        return []
    stubs = []
    for node in ast.parse(init_py.read_text(encoding="utf-8")).body:
        if isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
            node.body = [ast.Expr(ast.Constant(...))]
            node.decorator_list = []
            stubs.append(ast.unparse(node) + "\n")
        elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            stubs.append(f"class {node.name}: ...\n")
    return stubs


def generate(kotlin_root: Path, package_root: Path) -> dict[Path, str]:
    """Every stub this manifest yields: output path -> text. Writes nothing."""
    out: dict[Path, str] = {}
    for module_name, kotlin_package in manifest()["modules"].items():
        module_dir = package_root.joinpath(*module_name.split(".")[1:])
        kotlin_dir = kotlin_root.joinpath(*kotlin_package.split("."))
        own = own_definitions(module_dir / "__init__.py")
        source = kotlin_dir / STUB_NAME
        text = convert(source.read_text(encoding="utf-8")) if source.is_file() else HEADER
        if own:
            text += "\n" + "\n".join(own)
        out[module_dir / STUB_NAME] = text
        if kotlin_dir.is_dir():
            for nested in sorted(kotlin_dir.iterdir()):
                nested_stub = nested / STUB_NAME
                if nested.is_dir() and nested.name[:1].isupper() and nested_stub.is_file():
                    out[module_dir / nested.name / STUB_NAME] = convert(nested_stub.read_text(encoding="utf-8"))
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("kotlin_root", type=Path)
    parser.add_argument("--out", type=Path, default=REPO / "pythonx")
    args = parser.parse_args(argv)
    if not args.kotlin_root.is_dir():
        parser.error(f"{args.kotlin_root} is not a directory of Kotlin-named stubs")
    for path, text in generate(args.kotlin_root, args.out).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
