"""Generate `pythonx.compose` stubs from the binder's Kotlin-named stubs, by the runtime's own rule.

    python3 tools/gen_stubs.py <kotlin-stubs.zip | kotlin-stub-root> [--out pythonx/compose/..]

The input is what python-multiplatform's `PythonStubsTask` writes, either as its CI artefact
`kotlin-stubs` (a zip, read in place) or unpacked: one `androidx/compose/.../__init__.pyi` per Kotlin
package, Kotlin names unchanged. For each module in `pythonx-map.toml`, this reads the stub of the
Kotlin package it maps to and writes the Pythonic one next to the module's `__init__.py`:

- a module function or constant is renamed with `pythonx.compose._reexport.python_name`, the
  function the runtime resolves names with, so an editor completes what the interpreter answers;
- a parameter is renamed with `snake_case`, except the positional-only `receiver` and anonymous
  `__aN` slots, which a caller never writes by name; keyword-only markers stay;
- the binder's own `@overload` sets are kept in its order (with its `# type: ignore` comments). An
  input with explicit overloads only (`padding__Dp`, the first upstream format) also gets
  `@overload`s of the base name, fewest parameters first because a type checker takes the first
  match;
- a stub class keeps its name. Its members are renamed with `python_name`, which is the binder's
  member-resolver rule, and the parameters of a member's callable protocol are snake_case like a
  module function's, because the resolver also translates a method's keywords (the receiver and
  anonymous slots keep their names). The stubs are Pythonic-only: a method's Kotlin keyword still
  works at run time and is a type error here. A static method (a function of a Kotlin object) is
  reached through `KotlinObject`, so its parameters are snake_case too;
- a Kotlin object served as a sub-package (`Alignment`) becomes a class in its parent module's stub,
  whether the input has it as `<Object>/__init__.pyi` or already as a class in the parent stub
  (python-multiplatform #44). A sub-package directory holding only `__init__.pyi` would be a
  namespace package at run time and shadow the `KotlinObject` the re-export rule serves. An object
  whose name the parent uses for a function is left out: at run time that name is the function;
- an object's constants are also grouped by the type nested in it that their docstring declares
  them as (`Alignment.End(): Alignment.Horizontal`), as a class nested in the object's class
  (`Alignment.Horizontal.End`), the runtime's `ConstantGroup` rule; a member of that name wins;
- a reference to another Kotlin package names the `pythonx.compose` module the manifest lists first
  for it, and its import is rewritten to match; a package the manifest does not map, or a name the
  target stub does not declare as a class, becomes `typing.Any`;
- a module that maps a Kotlin package an earlier module already maps re-exports that module, and
  the manifest's `[aliases]` are re-exported, because at run time those names are the same objects;
- names the module's own `__init__.py` defines (`runtime.Composable`) are carried over, because a
  `.pyi` beside a module replaces everything a type checker knows about it; so is a bare
  annotation (`app_root: State`), the way a module declares a name its `__getattr__` creates.

Nothing here names a Kotlin declaration; it is the same rule `_reexport.py` applies at run time.
The output is deterministic: the same input regenerates the same text.
"""

from __future__ import annotations

import argparse
import ast
import keyword
import re
import sys
import zipfile
from functools import cached_property
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from pythonx.compose._reexport import manifest, python_name, snake_case  # noqa: E402

STUB_NAME = "__init__.pyi"
TYPING = "_t"
_ANY = f"{TYPING}.Any"


def header(source: str) -> str:
    return f"# GENERATED by tools/gen_stubs.py from {source}. Do not edit.\n"


# ---------------------------------------------------------------------------------------------- input


class KotlinStubs:
    """The Kotlin-named stubs, from a zip (read in place) or a directory, keyed by package."""

    def __init__(self, path: Path):
        self.path = Path(path)
        self.files: dict[str, str] = {}
        if self.path.is_file() and zipfile.is_zipfile(self.path):
            # Read in place: the artefact holds paths that differ only in case
            # (`ui/graphics/shadow/` and `ui/graphics/Shadow/`), which a case-insensitive disk merges.
            with zipfile.ZipFile(self.path) as archive:
                for name in archive.namelist():
                    if name.endswith((".pyi", ".md")):
                        self.files[name] = archive.read(name).decode("utf-8")
        elif self.path.is_dir():
            for file in self.path.rglob("*"):
                if file.is_file() and file.suffix in (".pyi", ".md"):
                    self.files[file.relative_to(self.path).as_posix()] = file.read_text(encoding="utf-8")
        else:
            raise FileNotFoundError(f"{self.path} is neither a zip nor a directory of Kotlin-named stubs")

    def stub(self, kotlin_package: str) -> str | None:
        return self.files.get(kotlin_package.replace(".", "/") + "/" + STUB_NAME)

    def objects(self, kotlin_package: str) -> list[str]:
        """Kotlin objects served as sub-packages of [kotlin_package] (`Alignment`), sorted."""
        prefix = kotlin_package.replace(".", "/") + "/"
        found = set()
        for name in self.files:
            if name.startswith(prefix) and name.endswith("/" + STUB_NAME):
                child = name[len(prefix):-len("/" + STUB_NAME)]
                if child[:1].isupper() and "/" not in child:
                    found.add(child)
        return sorted(found)

    @cached_property
    def provenance(self) -> str:
        """Where the input came from, for the generated header: the artefact's README, if any."""
        readme = self.files.get("README.md", "")
        details = [f"artifact {self.path.stem}"]
        for label, pattern in (
            ("workflow run", r"actions/runs/(\d+)"),
            ("commit", r"python-multiplatform commit \| ([0-9a-f]{8})"),
            ("Compose", r"\| Compose \| ([0-9][^ |]*)"),
        ):
            match = re.search(pattern, readme)
            if match:
                details.append(f"{label} {match.group(1)}")
        return "python-multiplatform's Kotlin-named stubs (" + ", ".join(details) + ")"


def parse(source: str, dropped: list[str] | None = None) -> ast.Module:
    """A stub's syntax tree, with `# type: ignore` comments kept.

    A Kotlin constant named like a Python keyword (`FilterQuality.None`) makes the upstream stub
    unparsable; it cannot be written as an attribute in Python either, so its line (and its
    docstring) is blanked and named in [dropped]. Any other syntax error is raised.
    """
    lines = source.split("\n")
    while True:
        try:
            return ast.parse("\n".join(lines), type_comments=True)
        except SyntaxError as error:
            index = (error.lineno or 0) - 1
            match = re.match(r"\s*(\w+)\s*:", lines[index]) if 0 <= index < len(lines) else None
            if match is None or not keyword.iskeyword(match.group(1)):
                raise
            if dropped is not None:
                dropped.append(match.group(1))
            lines[index] = ""
            if index + 1 < len(lines) and lines[index + 1].lstrip().startswith('"""'):
                lines[index + 1] = ""


# ------------------------------------------------------------------------------------------ renaming


def _keeps_its_name(name: str) -> bool:
    return name == "receiver" or name.startswith("__a")


def _rename_arguments(arguments: ast.arguments) -> ast.arguments:
    for group in (arguments.posonlyargs, arguments.args, arguments.kwonlyargs):
        for argument in group:
            if not _keeps_its_name(argument.arg):
                argument.arg = snake_case(argument.arg)
    return arguments


def _arity(arguments: ast.arguments) -> int:
    return len(arguments.posonlyargs) + len(arguments.args) + len(arguments.kwonlyargs)


def _is_overload(function: ast.FunctionDef) -> bool:
    return any(ast.unparse(d) in ("overload", f"{TYPING}.overload") for d in function.decorator_list)


def _is_static(function: ast.FunctionDef) -> bool:
    return any(ast.unparse(d) == "staticmethod" for d in function.decorator_list)


def _is_protocol(cls: ast.ClassDef) -> bool:
    return any(ast.unparse(base) in (f"{TYPING}.Protocol", "Protocol") for base in cls.bases)


def _annotation(text: str) -> ast.expr:
    return ast.parse(text, mode="eval").body


def _overload(function: ast.FunctionDef, name: str) -> ast.FunctionDef:
    copy = ast.parse(ast.unparse(function)).body[0]
    copy.name = name
    copy.decorator_list = [_annotation(f"{TYPING}.overload")] + copy.decorator_list
    return copy


def _name_of(node: ast.stmt) -> str | None:
    if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
        return node.name
    if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
        return node.target.id
    return None


def _mark_ignores(tree: ast.Module) -> None:
    """Carry each `# type: ignore[...]` onto the definition its line belongs to."""
    tags = {ignore.lineno: ignore.tag for ignore in tree.type_ignores}
    if not tags:
        return
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AnnAssign)) and node.lineno in tags:
            node.type_ignore = tags[node.lineno]


_DECLARED_CONSTANT = re.compile(r"Kotlin: (?P<owner>[\w.]+)\.\w+\(\): (?P<type>[\w.]+)$")


def _add_constant_groups(cls: ast.ClassDef, kotlin_name: str) -> None:
    """Nest in [cls] a class per type nested in it that its constants are declared as (SPEC S7.1).

    The runtime's `ConstantGroup` rule, read off the stub: a constant whose docstring
    (`Kotlin: <kotlin_name>.End(): <kotlin_name>.Horizontal`) declares it as exactly
    `<kotlin_name>.<G>`, for one simple upper-case name `G`, is repeated in `class G`, which is
    emitted unless [cls] already has a member named `G` (a Kotlin member wins). A constant declared
    as anything else -- [cls] itself, a deeper or a foreign type -- stays flat only.
    """
    members = {_name_of(node) for node in cls.body} - {None}
    groups: dict[str, list[ast.stmt]] = {}
    for index, node in enumerate(cls.body):
        if not (isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name)):
            continue
        following = cls.body[index + 1] if index + 1 < len(cls.body) else None
        if not (isinstance(following, ast.Expr) and isinstance(following.value, ast.Constant)
                and isinstance(following.value.value, str)):
            continue
        declared = _DECLARED_CONSTANT.match(following.value.value.strip())
        if declared is None or declared["owner"] != kotlin_name:
            continue
        group = declared["type"][len(kotlin_name) + 1:] if declared["type"].startswith(kotlin_name + ".") else ""
        if not group[:1].isupper() or "." in group or group in members:
            continue
        groups.setdefault(group, []).extend(
            ast.parse(ast.unparse(statement)).body[0] for statement in (node, following)
        )
    for group in sorted(groups):
        doc = f"Kotlin: the constants of {kotlin_name} declared as {kotlin_name}.{group}"
        cls.body.append(ast.ClassDef(
            name=group, bases=[], keywords=[], decorator_list=[],
            body=[ast.Expr(ast.Constant(doc))] + groups[group],
        ))


# -------------------------------------------------------------------------------------- references


class _References(ast.NodeTransformer):
    """Rewrite `androidx.compose.ui.Modifier` to `pythonx.compose.ui.Modifier`, or to `Any`."""

    def __init__(self, converter: "Converter", kotlin_package: str, imported: set[str]):
        self.converter = converter
        self.kotlin_package = kotlin_package
        self.imported = imported
        self.used: set[str] = set()

    def visit_Attribute(self, node: ast.Attribute) -> ast.expr:
        dotted = ast.unparse(node)
        root = dotted.split(".", 1)[0]
        if root == TYPING or not all(
            isinstance(n, (ast.Attribute, ast.Name, ast.expr_context)) for n in ast.walk(node)
        ):
            return self.generic_visit(node)
        package = max(
            (module for module in self.imported | {self.kotlin_package} if dotted.startswith(module + ".")),
            key=len, default=None,
        )
        if package is None:
            return self.generic_visit(node)
        rest = dotted[len(package) + 1:]
        if package == self.kotlin_package:
            return _annotation(rest) if self.converter.declares(package, rest) else _annotation(_ANY)
        target = self.converter.first_module.get(package)
        if target is None or not self.converter.declares(package, rest):
            return _annotation(_ANY)
        self.used.add(target)
        return _annotation(f"{target}.{rest}")


# -------------------------------------------------------------------------------------- conversion


class Converter:
    """Converts the stubs of one input against the manifest; collects what it had to leave out."""

    def __init__(self, stubs: KotlinStubs):
        self.stubs = stubs
        self.notes: list[str] = []
        self.first_module: dict[str, str] = {}
        for module_name, kotlin_package in manifest()["modules"].items():
            self.first_module.setdefault(kotlin_package, module_name)
        self._declared: dict[str, set[str]] = {}

    # What a Kotlin package's stub declares as a class (what a reference may name).
    def declares(self, kotlin_package: str, dotted: str) -> bool:
        if kotlin_package not in self._declared:
            declared: set[str] = set()
            source = self.stubs.stub(kotlin_package)
            functions: set[str] = set()
            if source is not None:
                tree = parse(source)

                def collect(prefix: str, body: list[ast.stmt]) -> None:
                    for node in body:
                        if isinstance(node, ast.ClassDef):
                            declared.add(prefix + node.name)
                            collect(prefix + node.name + ".", node.body)

                collect("", tree.body)
                functions = {_name_of(n) for n in tree.body if not isinstance(n, ast.ClassDef)} - {None}
            declared.update(name for name in self.stubs.objects(kotlin_package) if name not in functions)
            self._declared[kotlin_package] = declared
        return dotted in self._declared[kotlin_package]

    def convert(self, source: str, kotlin_package: str = "", module_name: str = "") -> str:
        """One Kotlin-named stub module, rewritten to the Pythonic surface."""
        dropped: list[str] = []
        tree = parse(source, dropped)
        _mark_ignores(tree)
        for name in dropped:
            self.notes.append(f"{kotlin_package}: constant {name!r} is a Python keyword; left out")
        imported = {
            alias.name for node in tree.body if isinstance(node, ast.Import) for alias in node.names
            if alias.name != "typing"
        }
        body: list[ast.stmt] = []
        explicit: dict[str, list[ast.FunctionDef]] = {}
        for node in tree.body:
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                continue
            if isinstance(node, ast.FunctionDef):
                node.name = python_name(node.name)
                _rename_arguments(node.args)
                base, sep, _ = node.name.partition("__")
                if sep:
                    explicit.setdefault(base, []).append(node)
            elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
                node.target.id = python_name(node.target.id)
            elif isinstance(node, ast.ClassDef):
                self._convert_class(node)
            body.append(node)

        defined = {node.name for node in body if isinstance(node, ast.FunctionDef)}
        for base, variants in explicit.items():
            if base in defined:
                continue  # the binder's own overload set (current format) stands as it is
            ordered = sorted(variants, key=lambda variant: _arity(variant.args))
            body.extend(_overload(variant, base) for variant in ordered)

        for name in self.stubs.objects(kotlin_package) if kotlin_package else ():
            self._add_object(body, kotlin_package, name, imported)
        for node in body:
            if isinstance(node, ast.ClassDef) and not _is_protocol(node):
                _add_constant_groups(node, f"{kotlin_package}.{node.name}")

        self._check_unique(body, kotlin_package)
        references = _References(self, kotlin_package, imported)
        body = [references.visit(node) for node in body]

        lines = [header(self.stubs.provenance), "import typing as _t\n"]
        lines.extend(f"import {module}\n" for module in sorted(references.used))
        for source_module, names in sorted(manifest().get("aliases", {}).get(module_name, {}).items()):
            lines.extend(f"from {source_module} import {name} as {name}\n" for name in sorted(names))
        lines.append("\n")
        lines.append(_emit_module(body))
        return "".join(lines)

    def _convert_class(self, cls: ast.ClassDef) -> None:
        if _is_protocol(cls):
            # A member's callable protocol: its `__call__` is the method, whose keywords the runtime
            # translates like a module function's.
            for member in cls.body:
                if isinstance(member, ast.FunctionDef) and member.name == "__call__":
                    _rename_arguments(member.args)
            return
        for member in cls.body:
            if isinstance(member, ast.AnnAssign) and isinstance(member.target, ast.Name):
                member.target.id = python_name(member.target.id)
            elif isinstance(member, ast.FunctionDef) and not member.name.startswith("__"):
                member.name = python_name(member.name)
                if _is_static(member):
                    # A function of a Kotlin object: `KotlinObject` translates its keywords.
                    _rename_arguments(member.args)
            elif isinstance(member, ast.ClassDef):
                self._convert_class(member)

    def _add_object(self, body: list[ast.stmt], kotlin_package: str, name: str, imported: set[str]) -> None:
        """Fold the object stub `<package>/<name>/__init__.pyi` into a class of the parent."""
        existing = {_name_of(node): node for node in body}
        holder = existing.get(name)
        if holder is not None and not isinstance(holder, ast.ClassDef):
            self.notes.append(
                f"{kotlin_package}.{name}: the object is shadowed by the module's {name!r} "
                "(a function at run time); left out"
            )
            return
        dropped: list[str] = []
        tree = parse(self.stubs.stub(f"{kotlin_package}.{name}") or "", dropped)
        _mark_ignores(tree)
        for constant in dropped:
            self.notes.append(f"{kotlin_package}.{name}: constant {constant!r} is a Python keyword; left out")
        imported.update(
            alias.name for node in tree.body if isinstance(node, ast.Import) for alias in node.names
            if alias.name != "typing"
        )
        groups: list[list[ast.stmt]] = []  # each member with the docstring that follows it
        for node in tree.body:
            if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
                node.target.id = python_name(node.target.id)
                if not ast.unparse(node.annotation).startswith(f"{TYPING}.ClassVar["):
                    node.annotation = _annotation(f"{TYPING}.ClassVar[{ast.unparse(node.annotation)}]")
                groups.append([node])
            elif isinstance(node, ast.FunctionDef):
                node.name = python_name(node.name)
                _rename_arguments(node.args)
                node.decorator_list = [ast.Name(id="staticmethod", ctx=ast.Load())] + [
                    d for d in node.decorator_list if ast.unparse(d) != "staticmethod"
                ]
                groups.append([node])
            elif isinstance(node, ast.Expr) and groups and isinstance(groups[-1][0], ast.AnnAssign):
                groups[-1].append(node)
        if holder is None:
            holder = ast.ClassDef(
                name=name, bases=[], keywords=[], decorator_list=[],
                body=[ast.Expr(ast.Constant(f"Kotlin: {kotlin_package}.{name}"))],
            )
            body.append(holder)
        present = {_name_of(member) for member in holder.body}
        for group in groups:
            if _name_of(group[0]) not in present:
                holder.body.extend(group)

    def _check_unique(self, body: list[ast.stmt], kotlin_package: str) -> None:
        """The runtime refuses two Kotlin names that become one Pythonic name; so does the stub."""
        seen: dict[str, str] = {}
        for node in body:
            name = _name_of(node)
            if name is None or (isinstance(node, ast.FunctionDef) and _is_overload(node)):
                continue
            if name in seen:
                raise ValueError(f"{kotlin_package}: two declarations become {name!r}")
            seen[name] = type(node).__name__


# ------------------------------------------------------------------------------------------ output


def _docstring(text: str) -> str:
    if '"""' in text or "\\" in text or text.endswith('"'):
        return repr(text)
    return f'"""{text}"""'


def _parameter(argument: ast.arg, default: ast.expr | None) -> str:
    text = argument.arg
    if argument.annotation is not None:
        text += f": {ast.unparse(argument.annotation)}"
        if default is not None:
            text += f" = {ast.unparse(default)}"
    elif default is not None:
        text += f"={ast.unparse(default)}"
    return text


def _parameters(arguments: ast.arguments) -> str:
    positional = arguments.posonlyargs + arguments.args
    defaults = [None] * (len(positional) - len(arguments.defaults)) + list(arguments.defaults)
    parts = [_parameter(a, d) for a, d in zip(positional, defaults)]
    if arguments.posonlyargs:
        parts.insert(len(arguments.posonlyargs), "/")
    if arguments.vararg is not None:
        parts.append("*" + _parameter(arguments.vararg, None))
    elif arguments.kwonlyargs:
        parts.append("*")
    parts.extend(_parameter(a, d) for a, d in zip(arguments.kwonlyargs, arguments.kw_defaults))
    if arguments.kwarg is not None:
        parts.append("**" + _parameter(arguments.kwarg, None))
    return ", ".join(parts)


def _ignore(node: ast.AST) -> str:
    tag = getattr(node, "type_ignore", None)
    return f"  # type: ignore{tag}" if tag is not None else ""


def _emit(node: ast.stmt, indent: str = "") -> list[str]:
    if isinstance(node, ast.FunctionDef):
        lines = [f"{indent}@{ast.unparse(d)}" for d in node.decorator_list]
        head = f"{indent}def {node.name}({_parameters(node.args)})"
        if node.returns is not None:
            head += f" -> {ast.unparse(node.returns)}"
        head += ":"
        doc = ast.get_docstring(node, clean=False)
        if doc is None:
            lines.append(f"{head} ...{_ignore(node)}")
        else:
            lines += [f"{head}{_ignore(node)}", f"{indent}    {_docstring(doc)}", f"{indent}    ..."]
        return lines
    if isinstance(node, ast.ClassDef):
        bases = ", ".join(ast.unparse(b) for b in node.bases)
        lines = [f"{indent}class {node.name}({bases}):" if bases else f"{indent}class {node.name}:"]
        for member in node.body:
            lines += _emit(member, indent + "    ")
        if len(lines) == 1:
            lines.append(f"{indent}    ...")
        return lines
    if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
        return [f"{indent}{_docstring(node.value.value)}"]
    return [f"{indent}{ast.unparse(node)}{_ignore(node)}"]


def _emit_module(body: list[ast.stmt]) -> str:
    out: list[str] = []
    previous: ast.stmt | None = None
    for node in body:
        attached = previous is not None and (
            (isinstance(node, ast.Expr) and isinstance(previous, ast.AnnAssign))
            or (isinstance(node, ast.FunctionDef) and isinstance(previous, ast.FunctionDef)
                and _is_overload(node) and _is_overload(previous) and node.name == previous.name)
        )
        if previous is not None and not attached:
            out.append("")
        out.extend(_emit(node))
        previous = node
    return "\n".join(out) + "\n" if out else ""


def own_definitions(init_py: Path) -> list[str]:
    """Stub text for the public functions and classes a package's own `__init__.py` defines."""
    if not init_py.is_file():
        return []
    stubs = []
    for node in ast.parse(init_py.read_text(encoding="utf-8")).body:
        if isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
            node.body = [ast.Expr(ast.Constant(...))]
            node.decorator_list = []
            stubs.append(ast.unparse(node) + "\n")
        elif (
            isinstance(node, ast.AnnAssign)
            and node.value is None
            and isinstance(node.target, ast.Name)
            and not node.target.id.startswith("_")
        ):
            # A name the module answers through its own `__getattr__` (`runtime.app_root`).
            stubs.append(ast.unparse(node) + "\n")
        elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            stubs.append(f"class {node.name}: ...\n")
    return stubs


def generate(kotlin_stubs: Path, package_root: Path, notes: list[str] | None = None) -> dict[Path, str]:
    """Every stub this manifest yields: output path -> text. Writes nothing.

    [kotlin_stubs] is the artefact zip or a directory; what had to be left out is appended to [notes].
    """
    stubs = KotlinStubs(kotlin_stubs)
    converter = Converter(stubs)
    out: dict[Path, str] = {}
    for module_name, kotlin_package in manifest()["modules"].items():
        module_dir = package_root.joinpath(*module_name.split(".")[1:])
        first = converter.first_module[kotlin_package]
        source = stubs.stub(kotlin_package)
        if first != module_name:
            # The same Kotlin package under a second name: at run time, the same objects.
            text = header(stubs.provenance) + f"from {first} import *\n"
        elif source is not None:
            text = converter.convert(source, kotlin_package, module_name)
        else:
            text = header(stubs.provenance)
        own = own_definitions(module_dir / "__init__.py")
        if own:
            text += "\n" + "\n".join(own)
        out[module_dir / STUB_NAME] = text
    if notes is not None:
        notes.extend(converter.notes)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("kotlin_stubs", type=Path, help="the `kotlin-stubs` zip, or a directory of Kotlin-named stubs")
    parser.add_argument("--out", type=Path, default=REPO / "pythonx")
    args = parser.parse_args(argv)
    if not args.kotlin_stubs.exists():
        parser.error(f"{args.kotlin_stubs} does not exist")
    notes: list[str] = []
    for path, text in generate(args.kotlin_stubs, args.out, notes).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(path)
    for note in notes:
        print(f"left out: {note}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
