# GENERATED by python-multiplatform-gradle-plugin. Do not edit.

import typing as _t
import androidx.compose.ui.unit

class Scene:
    """Kotlin: androidx.compose.ui.Scene"""
    @property
    def layoutDirection(self) -> androidx.compose.ui.unit.LayoutDirection:
        """Kotlin property: androidx.compose.ui.Scene.layoutDirection (androidx.compose.ui.Scene.layoutDirection: androidx.compose.ui.unit.LayoutDirection)"""
        ...
    @layoutDirection.setter
    def layoutDirection(self, value: androidx.compose.ui.unit.LayoutDirection) -> None:
        """Kotlin property: androidx.compose.ui.Scene.layoutDirection="""
        ...
    @property
    def isMinimized(self) -> bool:
        """Kotlin property: androidx.compose.ui.Scene.isMinimized (androidx.compose.ui.Scene.isMinimized: kotlin.Boolean)"""
        ...
    @isMinimized.setter
    def isMinimized(self, value: bool) -> None:
        """Kotlin property: androidx.compose.ui.Scene.isMinimized="""
        ...
