# GENERATED by python-multiplatform-gradle-plugin. Do not edit.

import typing as _t
import androidx.compose.ui.graphics.vector

class Filled:
    """Kotlin: androidx.compose.material.icons.Icons.Filled"""
    @property
    def Add(self) -> androidx.compose.ui.graphics.vector.ImageVector:
        """Kotlin property: androidx.compose.material.icons.filled.Add (androidx.compose.material.icons.Icons.Filled.Add: androidx.compose.ui.graphics.vector.ImageVector)"""
        ...

class AutoMirrored:
    """Kotlin: container of nested classes"""
    class Filled:
        """Kotlin: androidx.compose.material.icons.Icons.AutoMirrored.Filled"""
        @property
        def ArrowBack(self) -> androidx.compose.ui.graphics.vector.ImageVector:
            """Kotlin property: androidx.compose.material.icons.automirrored.filled.ArrowBack (androidx.compose.material.icons.Icons.AutoMirrored.Filled.ArrowBack: androidx.compose.ui.graphics.vector.ImageVector)"""
            ...

Default: Filled
"""Kotlin: androidx.compose.material.icons.Icons.Default(): androidx.compose.material.icons.Icons.Filled"""
